"""Compliance framework definitions and check mappings."""

FRAMEWORKS = {
    "CIS-AWS-1.5": {
        "name": "CIS Amazon Web Services Foundations Benchmark v1.5",
        "description": "Center for Internet Security AWS benchmark",
        "checks": [
            "iam_root_mfa_enabled", "iam_password_policy_strong", "iam_password_policy_rotation",
            "iam_user_mfa_enabled", "iam_access_key_rotation", "s3_bucket_public_access_blocked",
            "s3_bucket_encryption_enabled", "s3_bucket_logging_enabled", "ec2_sg_open_port_22",
            "ec2_sg_open_port_3389", "ec2_ebs_volume_encrypted", "ec2_imdsv2_required",
            "rds_encryption_enabled", "rds_public_access_disabled", "cloudtrail_multiregion",
            "cloudtrail_log_validation", "cloudtrail_encrypted", "kms_key_rotation_enabled",
            "vpc_flow_logs_enabled", "guardduty_enabled", "config_recorder_enabled",
            "eks_cluster_logging", "eks_endpoint_public_access",
        ],
    },
    "CIS-Azure-2.0": {
        "name": "CIS Microsoft Azure Foundations Benchmark v2.0",
        "description": "Center for Internet Security Azure benchmark",
        "checks": [
            "azure_iam_owner_count", "azure_storage_https_only", "azure_storage_tls_12",
            "azure_storage_no_public_access", "azure_nsg_open_port_22", "azure_nsg_open_port_3389",
            "azure_network_watcher_enabled", "azure_vm_disk_encryption", "azure_sql_auditing_enabled",
            "azure_sql_tls_12", "azure_keyvault_soft_delete", "azure_keyvault_purge_protection",
            "azure_monitor_log_profile", "azure_appservice_https_only", "azure_appservice_tls_12",
        ],
    },
    "CIS-GCP-2.0": {
        "name": "CIS Google Cloud Platform Foundation Benchmark v2.0",
        "description": "Center for Internet Security GCP benchmark",
        "checks": [
            "gcp_iam_no_public_access", "gcp_compute_no_external_ip", "gcp_compute_os_login",
            "gcp_storage_uniform_access", "gcp_sql_no_public_ip", "gcp_sql_ssl_required",
            "gcp_kms_key_rotation", "gcp_gke_private_cluster", "gcp_gke_network_policy",
            "gcp_firewall_open_22", "gcp_firewall_open_3389",
        ],
    },
    "CIS-OCI-2.0": {
        "name": "CIS Oracle Cloud Infrastructure Foundations Benchmark v2.0",
        "description": "Center for Internet Security OCI benchmark",
        "checks": [
            "oci_iam_api_key_rotation", "oci_iam_user_mfa_enabled", "oci_iam_admin_mfa_enabled",
            "oci_iam_password_length", "oci_iam_password_uppercase", "oci_iam_password_lowercase",
            "oci_iam_password_numeric", "oci_iam_password_special", "oci_iam_secret_key_rotation",
            "oci_iam_policy_no_wildcard", "oci_network_sl_no_ssh_open", "oci_network_sl_no_rdp_open",
            "oci_network_nsg_no_unrestricted_ingress", "oci_network_vcn_flow_logs",
            "oci_compute_secure_boot", "oci_compute_imds_v2", "oci_compute_boot_volume_transit_encryption",
            "oci_storage_volume_cmk_encryption", "oci_storage_boot_volume_cmk_encryption",
            "oci_objectstorage_bucket_public_access", "oci_objectstorage_bucket_cmk_encryption",
            "oci_objectstorage_bucket_versioning", "oci_objectstorage_bucket_emit_events",
            "oci_db_autonomous_cmk_encryption", "oci_db_autonomous_private_endpoint",
            "oci_db_system_backup_enabled", "oci_vault_key_rotation",
            "oci_logging_audit_retention", "oci_logging_log_groups_exist",
            "oci_cloud_guard_enabled", "oci_notifications_security_topic_exists",
            "oci_functions_app_nsg_assigned", "oci_functions_app_tracing_enabled",
            "oci_functions_provisioned_concurrency",
            "oci_container_instance_restart_policy", "oci_container_instance_graceful_shutdown",
            "oci_container_registry_public_repo", "oci_container_registry_immutable_artifacts",
            "oci_filestorage_cmk_encryption", "oci_filestorage_mount_target_nsg",
            "oci_filestorage_export_privileged_port",
            "oci_oke_cluster_public_endpoint", "oci_oke_cluster_nsg_assigned",
            "oci_oke_image_verification", "oci_oke_kubernetes_version",
            "oci_oke_nodepool_nsg_assigned",
            "oci_lb_nsg_assigned", "oci_lb_listener_https", "oci_lb_backend_health",
            "oci_mysql_backup_enabled", "oci_mysql_pitr_enabled", "oci_mysql_crash_recovery",
            "oci_mysql_deletion_protection", "oci_mysql_high_availability",
        ],
    },
    "NIST-800-53": {
        "name": "NIST SP 800-53 Rev. 5",
        "description": "Security and Privacy Controls for Information Systems",
        "checks": "all",
    },
    "NIST-CSF": {
        "name": "NIST Cybersecurity Framework",
        "description": "Framework for Improving Critical Infrastructure Cybersecurity",
        "checks": "all_saas",
    },
    "ISO-27001": {
        "name": "ISO/IEC 27001:2022",
        "description": "Information security management systems",
        "checks": "all_saas",
    },
    "PCI-DSS-3.2.1": {
        "name": "PCI DSS v3.2.1",
        "description": "Payment Card Industry Data Security Standard",
        "checks": [
            "iam_root_mfa_enabled", "iam_user_mfa_enabled", "s3_bucket_public_access_blocked",
            "s3_bucket_encryption_enabled", "s3_bucket_logging_enabled",
            "rds_encryption_enabled", "rds_public_access_disabled",
            "cloudtrail_log_validation", "cloudtrail_encrypted",
            "kms_key_rotation_enabled", "vpc_flow_logs_enabled", "guardduty_enabled",
        ],
    },
    "HIPAA": {
        "name": "HIPAA Security Rule",
        "description": "Health Insurance Portability and Accountability Act",
        "checks": [
            "s3_bucket_encryption_enabled", "ec2_ebs_volume_encrypted",
            "rds_encryption_enabled", "rds_backup_enabled",
            "cloudtrail_encrypted", "sns_topic_encrypted", "sqs_queue_encrypted",
            "efs_encryption_enabled", "dynamodb_table_encrypted_kms",
        ],
    },
    "SOC2": {
        "name": "SOC 2 Type II",
        "description": "Service Organization Control 2",
        "checks": [
            "s3_bucket_versioning_enabled", "rds_multi_az_enabled", "rds_backup_enabled",
            "secretsmanager_rotation_enabled", "dynamodb_pitr_enabled",
            "cloudwatch_log_group_retention",
        ],
    },
    "GDPR": {
        "name": "GDPR",
        "description": "General Data Protection Regulation",
        "checks": [
            "s3_bucket_encryption_enabled", "rds_encryption_enabled",
            "ec2_ebs_volume_encrypted", "cloudtrail_encrypted",
        ],
    },
}
