"""M365 CIS v6.0.1 Evaluator Registry — 142 controls, ~93% automated."""
from .section_1_admin import SECTION_1_EVALUATORS
from .section_2_4_defender import SECTION_2_EVALUATORS, SECTION_3_EVALUATORS, SECTION_4_EVALUATORS
from .section_5_entra import SECTION_5_EVALUATORS
from .section_6_9_exch_sp_teams import (
    SECTION_6_EVALUATORS, SECTION_7_EVALUATORS,
    SECTION_8_EVALUATORS, SECTION_9_EVALUATORS,
)
from .supplements import SUPPLEMENTS

EVALUATOR_REGISTRY: dict[str, callable] = {}
EVALUATOR_REGISTRY.update(SECTION_1_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_2_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_3_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_4_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_5_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_6_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_7_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_8_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_9_EVALUATORS)

# Override manual stubs with automated implementations
EVALUATOR_REGISTRY.update(SUPPLEMENTS)

assert len(EVALUATOR_REGISTRY) == 142, f"Expected 142, got {len(EVALUATOR_REGISTRY)}"
__all__ = ["EVALUATOR_REGISTRY"]
