"""Check definitions for Alibaba Cloud.

Auto-generated from alibaba scanner. 57 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Alibaba Cloud check definitions."""
    return [
        CheckDefinition(
            check_id="ali_ack_cloud_monitor",
            title="ACK cluster has Cloud Monitor integration enabled",
            description="ACK cluster has Cloud Monitor integration enabled.",
            severity="medium",
            provider="alibaba",
            service="ack",
            category="Compliance",
            tags=["ack"],
        ),
        CheckDefinition(
            check_id="ali_ack_log_service",
            title="ACK cluster has Log Service (SLS) integration enabled",
            description="ACK cluster has Log Service (SLS) integration enabled.",
            severity="high",
            provider="alibaba",
            service="ack",
            category="Compliance",
            tags=["ack"],
        ),
        CheckDefinition(
            check_id="ali_ack_network_policy",
            title="ACK cluster has network policy plugin enabled (Terway/Calico)",
            description="ACK cluster has network policy plugin enabled (Terway/Calico).",
            severity="medium",
            provider="alibaba",
            service="ack",
            category="Compliance",
            tags=["ack"],
        ),
        CheckDefinition(
            check_id="ali_ack_no_basic_auth",
            title="ACK cluster does not use basic authentication",
            description="ACK cluster does not use basic authentication.",
            severity="high",
            provider="alibaba",
            service="ack",
            category="Compliance",
            tags=["ack"],
        ),
        CheckDefinition(
            check_id="ali_ack_private_cluster",
            title="ACK cluster API server is not publicly accessible",
            description="ACK cluster API server is not publicly accessible.",
            severity="high",
            provider="alibaba",
            service="ack",
            category="Compliance",
            tags=["ack"],
        ),
        CheckDefinition(
            check_id="ali_ack_rbac_enabled",
            title="ACK cluster has RBAC authorization enabled",
            description="ACK cluster has RBAC authorization enabled.",
            severity="high",
            provider="alibaba",
            service="ack",
            category="Compliance",
            tags=["ack"],
        ),
        CheckDefinition(
            check_id="ali_actiontrail_enabled",
            title="ActionTrail logging is enabled",
            description="ActionTrail logging is enabled.",
            severity="high",
            provider="alibaba",
            service="actiontrail",
            category="Compliance",
            tags=["actiontrail"],
        ),
        CheckDefinition(
            check_id="ali_actiontrail_logging_active",
            title="ActionTrail trail is actively logging",
            description="ActionTrail trail is actively logging.",
            severity="high",
            provider="alibaba",
            service="actiontrail",
            category="Compliance",
            tags=["actiontrail", "logging"],
        ),
        CheckDefinition(
            check_id="ali_actiontrail_multi_region",
            title="ActionTrail trail covers all regions",
            description="ActionTrail trail covers all regions.",
            severity="medium",
            provider="alibaba",
            service="actiontrail",
            category="Compliance",
            tags=["actiontrail"],
        ),
        CheckDefinition(
            check_id="ali_actiontrail_oss_not_public",
            title="ActionTrail log OSS bucket is not publicly accessible",
            description="ActionTrail log OSS bucket is not publicly accessible.",
            severity="critical",
            provider="alibaba",
            service="actiontrail",
            category="Compliance",
            tags=["actiontrail", "public-access"],
        ),
        CheckDefinition(
            check_id="ali_ecs_deletion_protection",
            title="ECS instance has deletion protection enabled",
            description="ECS instance has deletion protection enabled.",
            severity="low",
            provider="alibaba",
            service="ecs",
            category="Container",
            tags=["ecs"],
        ),
        CheckDefinition(
            check_id="ali_ecs_disk_encryption",
            title="ECS disk is encrypted",
            description="ECS disk is encrypted.",
            severity="high",
            provider="alibaba",
            service="ecs",
            category="Container",
            tags=["ecs", "encryption"],
        ),
        CheckDefinition(
            check_id="ali_ecs_no_public_ip",
            title="ECS instance does not have a public IP address",
            description="ECS instance does not have a public IP address.",
            severity="medium",
            provider="alibaba",
            service="ecs",
            category="Container",
            tags=["ecs", "public-access"],
        ),
        CheckDefinition(
            check_id="ali_ecs_sg_no_public_ingress",
            title="Security group does not allow unrestricted ingress",
            description="Security group does not allow unrestricted ingress.",
            severity="high",
            provider="alibaba",
            service="ecs",
            category="Container",
            tags=["ecs", "security-group", "public-access"],
        ),
        CheckDefinition(
            check_id="ali_ecs_sg_no_rdp_open",
            title="Security group does not allow unrestricted RDP (port 3389) from 0.0.0.0/0",
            description="Security group does not allow unrestricted RDP (port 3389) from 0.0.0.0/0.",
            severity="high",
            provider="alibaba",
            service="ecs",
            category="Container",
            tags=["ecs", "security-group", "rdp"],
        ),
        CheckDefinition(
            check_id="ali_ecs_sg_no_ssh_open",
            title="Security group does not allow unrestricted SSH (port 22) from 0.0.0.0/0",
            description="Security group does not allow unrestricted SSH (port 22) from 0.0.0.0/0.",
            severity="high",
            provider="alibaba",
            service="ecs",
            category="Container",
            tags=["ecs", "security-group", "ssh"],
        ),
        CheckDefinition(
            check_id="ali_ecs_vpc_network",
            title="ECS instance uses VPC network (not classic)",
            description="ECS instance uses VPC network (not classic).",
            severity="high",
            provider="alibaba",
            service="ecs",
            category="Container",
            tags=["ecs", "networking"],
        ),
        CheckDefinition(
            check_id="ali_kms_cmk_enabled",
            title="KMS CMK is in Enabled state",
            description="KMS CMK is in Enabled state.",
            severity="low",
            provider="alibaba",
            service="kms",
            category="Encryption",
            tags=["kms"],
        ),
        CheckDefinition(
            check_id="ali_kms_key_rotation",
            title="KMS CMK has automatic rotation enabled",
            description="KMS CMK has automatic rotation enabled.",
            severity="medium",
            provider="alibaba",
            service="kms",
            category="Encryption",
            tags=["kms", "rotation"],
        ),
        CheckDefinition(
            check_id="ali_oss_encryption_enabled",
            title="OSS bucket has server-side encryption enabled",
            description="OSS bucket has server-side encryption enabled.",
            severity="high",
            provider="alibaba",
            service="oss",
            category="Storage",
            tags=["oss", "encryption"],
        ),
        CheckDefinition(
            check_id="ali_oss_https_only",
            title="OSS bucket enforces HTTPS-only access",
            description="OSS bucket enforces HTTPS-only access.",
            severity="medium",
            provider="alibaba",
            service="oss",
            category="Storage",
            tags=["oss", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="ali_oss_lifecycle_configured",
            title="OSS bucket has lifecycle rules configured",
            description="OSS bucket has lifecycle rules configured.",
            severity="low",
            provider="alibaba",
            service="oss",
            category="Storage",
            tags=["oss"],
        ),
        CheckDefinition(
            check_id="ali_oss_logging_enabled",
            title="OSS bucket has access logging enabled",
            description="OSS bucket has access logging enabled.",
            severity="medium",
            provider="alibaba",
            service="oss",
            category="Storage",
            tags=["oss", "logging"],
        ),
        CheckDefinition(
            check_id="ali_oss_no_public_access",
            title="OSS bucket is not publicly accessible",
            description="OSS bucket is not publicly accessible.",
            severity="critical",
            provider="alibaba",
            service="oss",
            category="Storage",
            tags=["oss", "public-access"],
        ),
        CheckDefinition(
            check_id="ali_oss_versioning_enabled",
            title="OSS bucket has versioning enabled",
            description="OSS bucket has versioning enabled.",
            severity="low",
            provider="alibaba",
            service="oss",
            category="Storage",
            tags=["oss"],
        ),
        CheckDefinition(
            check_id="ali_ram_access_key_rotation",
            title="RAM user access key is rotated within 90 days",
            description="RAM user access key is rotated within 90 days.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram", "rotation"],
        ),
        CheckDefinition(
            check_id="ali_ram_mfa_enabled",
            title="RAM user has MFA enabled",
            description="RAM user has MFA enabled.",
            severity="high",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram", "mfa"],
        ),
        CheckDefinition(
            check_id="ali_ram_no_wildcard_policy",
            title="RAM policy does not allow full *:* administrative privileges",
            description="RAM policy does not allow full *:* administrative privileges.",
            severity="critical",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_expiry",
            title="RAM password policy expires passwords within 365 days",
            description="RAM password policy expires passwords within 365 days.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_length",
            title="RAM password policy requires minimum length of 14 or greater",
            description="RAM password policy requires minimum length of 14 or greater.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_lockout",
            title="RAM password policy blocks logon after 5 incorrect attempts",
            description="RAM password policy blocks logon after 5 incorrect attempts.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_lowercase",
            title="RAM password policy requires at least one lowercase letter",
            description="RAM password policy requires at least one lowercase letter.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_number",
            title="RAM password policy requires at least one number",
            description="RAM password policy requires at least one number.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_policy",
            title="RAM password policy meets complexity requirements",
            description="RAM password policy meets complexity requirements.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_reuse",
            title="RAM password policy prevents password reuse",
            description="RAM password policy prevents password reuse.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_symbol",
            title="RAM password policy requires at least one symbol",
            description="RAM password policy requires at least one symbol.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_password_uppercase",
            title="RAM password policy requires at least one uppercase letter",
            description="RAM password policy requires at least one uppercase letter.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_policies_groups_only",
            title="RAM policies should be attached to groups/roles, not directly to users",
            description="RAM policies should be attached to groups/roles, not directly to users.",
            severity="medium",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_ram_unused_users",
            title="RAM user has logged in within the last 90 days",
            description="RAM user has logged in within the last 90 days.",
            severity="low",
            provider="alibaba",
            service="ram",
            category="Compliance",
            tags=["ram"],
        ),
        CheckDefinition(
            check_id="ali_rds_audit_enabled",
            title="RDS instance has SQL auditing (SQL Explorer) enabled",
            description="RDS instance has SQL auditing (SQL Explorer) enabled.",
            severity="medium",
            provider="alibaba",
            service="rds",
            category="Database",
            tags=["rds", "audit"],
        ),
        CheckDefinition(
            check_id="ali_rds_backup_retention",
            title="RDS instance has backup retention of at least 7 days",
            description="RDS instance has backup retention of at least 7 days.",
            severity="medium",
            provider="alibaba",
            service="rds",
            category="Database",
            tags=["rds", "backup", "retention"],
        ),
        CheckDefinition(
            check_id="ali_rds_encryption_enabled",
            title="RDS instance has encryption enabled (TDE)",
            description="RDS instance has encryption enabled (TDE).",
            severity="high",
            provider="alibaba",
            service="rds",
            category="Database",
            tags=["rds", "encryption"],
        ),
        CheckDefinition(
            check_id="ali_rds_no_public_access",
            title="RDS instance is not publicly accessible",
            description="RDS instance is not publicly accessible.",
            severity="critical",
            provider="alibaba",
            service="rds",
            category="Database",
            tags=["rds", "public-access"],
        ),
        CheckDefinition(
            check_id="ali_rds_not_open_world",
            title="RDS instance whitelist does not allow 0.0.0.0/0",
            description="RDS instance whitelist does not allow 0.0.0.0/0.",
            severity="critical",
            provider="alibaba",
            service="rds",
            category="Database",
            tags=["rds"],
        ),
        CheckDefinition(
            check_id="ali_rds_ssl_enabled",
            title="RDS instance has SSL enabled",
            description="RDS instance has SSL enabled.",
            severity="high",
            provider="alibaba",
            service="rds",
            category="Database",
            tags=["rds", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="ali_sas_advanced_edition",
            title="Security Center is at least Advanced edition",
            description="Security Center is at least Advanced edition.",
            severity="high",
            provider="alibaba",
            service="security_center",
            category="Compliance",
            tags=["security_center"],
        ),
        CheckDefinition(
            check_id="ali_sas_agents_installed",
            title="Security Center agents installed and online on all instances",
            description="Security Center agents installed and online on all instances.",
            severity="high",
            provider="alibaba",
            service="security_center",
            category="Compliance",
            tags=["security_center"],
        ),
        CheckDefinition(
            check_id="ali_sas_notification_enabled",
            title="Security Center notification contacts are configured",
            description="Security Center notification contacts are configured.",
            severity="medium",
            provider="alibaba",
            service="security_center",
            category="Compliance",
            tags=["security_center"],
        ),
        CheckDefinition(
            check_id="ali_sas_vuln_scan_enabled",
            title="Security Center vulnerability scanning is active",
            description="Security Center vulnerability scanning is active.",
            severity="medium",
            provider="alibaba",
            service="security_center",
            category="Compliance",
            tags=["security_center"],
        ),
        CheckDefinition(
            check_id="ali_security_center_enabled",
            title="Security Center (Threat Detection) is enabled",
            description="Security Center (Threat Detection) is enabled.",
            severity="high",
            provider="alibaba",
            service="security_center",
            category="Compliance",
            tags=["security_center"],
        ),
        CheckDefinition(
            check_id="ali_slb_access_logs",
            title="SLB has access logs enabled",
            description="SLB has access logs enabled.",
            severity="medium",
            provider="alibaba",
            service="slb",
            category="Compliance",
            tags=["slb"],
        ),
        CheckDefinition(
            check_id="ali_slb_https_listener",
            title="SLB uses HTTPS listeners",
            description="SLB uses HTTPS listeners.",
            severity="high",
            provider="alibaba",
            service="slb",
            category="Compliance",
            tags=["slb", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="ali_sls_retention_365",
            title="SLS log store retention is at least 365 days",
            description="SLS log store retention is at least 365 days.",
            severity="medium",
            provider="alibaba",
            service="sls",
            category="Compliance",
            tags=["sls", "retention"],
        ),
        CheckDefinition(
            check_id="ali_vpc_flow_logs",
            title="VPC has flow logs enabled",
            description="VPC has flow logs enabled.",
            severity="medium",
            provider="alibaba",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="ali_vpc_nacl_associated",
            title="Network ACL is associated with vSwitches",
            description="Network ACL is associated with vSwitches.",
            severity="medium",
            provider="alibaba",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="ali_waf_domains_configured",
            title="WAF has protected domains configured",
            description="WAF has protected domains configured.",
            severity="medium",
            provider="alibaba",
            service="waf",
            category="Networking",
            tags=["waf"],
        ),
        CheckDefinition(
            check_id="ali_waf_enabled",
            title="WAF instance is active",
            description="WAF instance is active.",
            severity="high",
            provider="alibaba",
            service="waf",
            category="Networking",
            tags=["waf"],
        ),
    ]
