"""Check definitions for AWS.

Auto-generated from aws scanner. 89 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all AWS check definitions."""
    return [
        CheckDefinition(
            check_id="acm_certificate_expiry",
            title="ACM certificate is not expired or expiring soon",
            description="ACM certificate is not expired or expiring soon.",
            severity="high",
            provider="aws",
            service="acm",
            category="Encryption",
            tags=["acm"],
        ),
        CheckDefinition(
            check_id="apigateway_rest_api_logging",
            title="API Gateway REST API stage has logging enabled",
            description="API Gateway REST API stage has logging enabled.",
            severity="medium",
            provider="aws",
            service="apigateway",
            category="Compliance",
            tags=["apigateway", "logging"],
        ),
        CheckDefinition(
            check_id="apigateway_waf_enabled",
            title="API Gateway REST API has WAF associated",
            description="API Gateway REST API has WAF associated.",
            severity="medium",
            provider="aws",
            service="apigateway",
            category="Compliance",
            tags=["apigateway", "waf"],
        ),
        CheckDefinition(
            check_id="backup_plan_exists",
            title="AWS Backup plan exists in region",
            description="AWS Backup plan exists in region.",
            severity="medium",
            provider="aws",
            service="backup",
            category="Backup",
            tags=["backup"],
        ),
        CheckDefinition(
            check_id="backup_vault_encrypted",
            title="AWS Backup vault is encrypted",
            description="AWS Backup vault is encrypted.",
            severity="high",
            provider="aws",
            service="backup",
            category="Backup",
            tags=["backup", "encryption"],
        ),
        CheckDefinition(
            check_id="cloudfront_https_only",
            title="CloudFront distribution enforces HTTPS",
            description="CloudFront distribution enforces HTTPS.",
            severity="high",
            provider="aws",
            service="cloudfront",
            category="CDN",
            tags=["cloudfront", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudfront_waf_enabled",
            title="CloudFront distribution has WAF enabled",
            description="CloudFront distribution has WAF enabled.",
            severity="medium",
            provider="aws",
            service="cloudfront",
            category="CDN",
            tags=["cloudfront", "waf"],
        ),
        CheckDefinition(
            check_id="cloudtrail_enabled",
            title="CloudTrail is enabled",
            description="CloudTrail is enabled.",
            severity="critical",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_encrypted",
            title="CloudTrail logs are encrypted with KMS",
            description="CloudTrail logs are encrypted with KMS.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail", "encryption"],
        ),
        CheckDefinition(
            check_id="cloudtrail_integrated_cloudwatch",
            title="CloudTrail is integrated with CloudWatch Logs",
            description="CloudTrail is integrated with CloudWatch Logs.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_log_validation",
            title="CloudTrail log file validation is enabled",
            description="CloudTrail log file validation is enabled.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_multiregion",
            title="CloudTrail is multi-region",
            description="CloudTrail is multi-region.",
            severity="high",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_s3_bucket_logging",
            title="CloudTrail S3 bucket has access logging enabled",
            description="CloudTrail S3 bucket has access logging enabled.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail", "logging"],
        ),
        CheckDefinition(
            check_id="cloudtrail_s3_object_read_events",
            title="CloudTrail logs S3 object-level read events",
            description="CloudTrail logs S3 object-level read events.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_s3_object_write_events",
            title="CloudTrail logs S3 object-level write events",
            description="CloudTrail logs S3 object-level write events.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudwatch_log_group_encrypted",
            title="CloudWatch log group is encrypted",
            description="CloudWatch log group is encrypted.",
            severity="medium",
            provider="aws",
            service="cloudwatch",
            category="Logging",
            tags=["cloudwatch", "encryption"],
        ),
        CheckDefinition(
            check_id="cloudwatch_log_group_retention",
            title="CloudWatch log group has retention policy",
            description="CloudWatch log group has retention policy.",
            severity="low",
            provider="aws",
            service="cloudwatch",
            category="Logging",
            tags=["cloudwatch", "retention"],
        ),
        CheckDefinition(
            check_id="config_recorder_enabled",
            title="AWS Config recorder is enabled",
            description="AWS Config recorder is enabled.",
            severity="medium",
            provider="aws",
            service="config",
            category="Compliance",
            tags=["config"],
        ),
        CheckDefinition(
            check_id="dynamodb_pitr_enabled",
            title="DynamoDB table has PITR enabled",
            description="DynamoDB table has PITR enabled.",
            severity="medium",
            provider="aws",
            service="dynamodb",
            category="Database",
            tags=["dynamodb"],
        ),
        CheckDefinition(
            check_id="dynamodb_table_encrypted_kms",
            title="DynamoDB table is encrypted with KMS",
            description="DynamoDB table is encrypted with KMS.",
            severity="medium",
            provider="aws",
            service="dynamodb",
            category="Database",
            tags=["dynamodb", "encryption", "kms"],
        ),
        CheckDefinition(
            check_id="ec2_default_sg_no_traffic",
            title="Default security group restricts all traffic",
            description="Default security group restricts all traffic.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ec2_ebs_default_encryption",
            title="EBS default encryption is enabled",
            description="EBS default encryption is enabled.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "encryption"],
        ),
        CheckDefinition(
            check_id="ec2_ebs_volume_encrypted",
            title="EBS volume is encrypted",
            description="EBS volume is encrypted.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "encryption"],
        ),
        CheckDefinition(
            check_id="ec2_imdsv2_required",
            title="EC2 instance requires IMDSv2",
            description="EC2 instance requires IMDSv2.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2"],
        ),
        CheckDefinition(
            check_id="ec2_instance_no_public_ip",
            title="EC2 instance does not have a public IP address",
            description="EC2 instance does not have a public IP address.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "public-access"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_ipv6_wide_open",
            title="ec2_sg_no_ipv6_wide_open",
            description="ec2_sg_no_ipv6_wide_open.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_wide_open_ports",
            title="Security group does not allow wide port ranges to 0.0.0.0/0",
            description="Security group does not allow wide port ranges to 0.0.0.0/0.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ecr_image_scanning",
            title="ECR repository has image scanning on push enabled",
            description="ECR repository has image scanning on push enabled.",
            severity="medium",
            provider="aws",
            service="ecr",
            category="Container",
            tags=["ecr"],
        ),
        CheckDefinition(
            check_id="ecr_lifecycle_policy",
            title="ECR repository has lifecycle policy configured",
            description="ECR repository has lifecycle policy configured.",
            severity="low",
            provider="aws",
            service="ecr",
            category="Container",
            tags=["ecr"],
        ),
        CheckDefinition(
            check_id="ecs_cluster_container_insights",
            title="ECS cluster has Container Insights enabled",
            description="ECS cluster has Container Insights enabled.",
            severity="low",
            provider="aws",
            service="ecs",
            category="Container",
            tags=["ecs"],
        ),
        CheckDefinition(
            check_id="efs_encryption_enabled",
            title="EFS file system is encrypted",
            description="EFS file system is encrypted.",
            severity="high",
            provider="aws",
            service="efs",
            category="Storage",
            tags=["efs", "encryption"],
        ),
        CheckDefinition(
            check_id="eks_cluster_logging",
            title="EKS cluster has API logging enabled",
            description="EKS cluster has API logging enabled.",
            severity="medium",
            provider="aws",
            service="eks",
            category="Container",
            tags=["eks", "logging"],
        ),
        CheckDefinition(
            check_id="eks_endpoint_public_access",
            title="EKS cluster endpoint is not publicly accessible",
            description="EKS cluster endpoint is not publicly accessible.",
            severity="high",
            provider="aws",
            service="eks",
            category="Container",
            tags=["eks", "public-access"],
        ),
        CheckDefinition(
            check_id="eks_secrets_encrypted",
            title="EKS cluster has secrets encryption enabled",
            description="EKS cluster has secrets encryption enabled.",
            severity="high",
            provider="aws",
            service="eks",
            category="Container",
            tags=["eks", "encryption"],
        ),
        CheckDefinition(
            check_id="elasticache_encryption_rest",
            title="ElastiCache cluster has encryption at rest",
            description="ElastiCache cluster has encryption at rest.",
            severity="high",
            provider="aws",
            service="elasticache",
            category="Database",
            tags=["elasticache", "encryption"],
        ),
        CheckDefinition(
            check_id="elasticache_encryption_transit",
            title="ElastiCache cluster has encryption in transit",
            description="ElastiCache cluster has encryption in transit.",
            severity="high",
            provider="aws",
            service="elasticache",
            category="Database",
            tags=["elasticache", "encryption"],
        ),
        CheckDefinition(
            check_id="es_encryption_at_rest",
            title="Elasticsearch domain has encryption at rest",
            description="Elasticsearch domain has encryption at rest.",
            severity="high",
            provider="aws",
            service="elasticsearch",
            category="Database",
            tags=["elasticsearch", "encryption"],
        ),
        CheckDefinition(
            check_id="es_node_to_node_encryption",
            title="Elasticsearch domain has node-to-node encryption",
            description="Elasticsearch domain has node-to-node encryption.",
            severity="medium",
            provider="aws",
            service="elasticsearch",
            category="Database",
            tags=["elasticsearch", "encryption"],
        ),
        CheckDefinition(
            check_id="guardduty_enabled",
            title="GuardDuty is enabled",
            description="GuardDuty is enabled.",
            severity="high",
            provider="aws",
            service="guardduty",
            category="Threat Detection",
            tags=["guardduty"],
        ),
        CheckDefinition(
            check_id="iam_access_analyzer_enabled",
            title="IAM Access Analyzer is enabled",
            description="IAM Access Analyzer is enabled.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_access_key_rotation",
            title="IAM access key is rotated within 90 days",
            description="IAM access key is rotated within 90 days.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="iam_cloudshell_fullaccess_restricted",
            title="AWSCloudShellFullAccess policy is not attached to any entity",
            description="AWSCloudShellFullAccess policy is not attached to any entity.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_group_no_inline_policies",
            title="IAM group does not have inline policies",
            description="IAM group does not have inline policies.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_no_root_access_key",
            title="Root account has no access keys",
            description="Root account has no access keys.",
            severity="critical",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_no_star_policies",
            title="IAM policy does not allow full *:* admin access",
            description="IAM policy does not allow full *:* admin access.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_exists",
            title="IAM password policy is configured",
            description="IAM password policy is configured.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_reuse_prevention",
            title="IAM password policy prevents password reuse (24 or more)",
            description="IAM password policy prevents password reuse (24 or more).",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_rotation",
            title="IAM password policy enforces rotation within 90 days",
            description="IAM password policy enforces rotation within 90 days.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_strong",
            title="IAM password policy requires strong passwords",
            description="IAM password policy requires strong passwords.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_root_mfa_enabled",
            title="Root account has MFA enabled",
            description="Root account has MFA enabled.",
            severity="critical",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "mfa"],
        ),
        CheckDefinition(
            check_id="iam_ssl_certificate_expiry",
            title="IAM SSL/TLS certificate is not expired or expiring soon",
            description="IAM SSL/TLS certificate is not expired or expiring soon.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="iam_support_role_created",
            title="IAM Support role has been created for AWS Support access",
            description="IAM Support role has been created for AWS Support access.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_mfa_enabled",
            title="IAM user has MFA enabled",
            description="IAM user has MFA enabled.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "mfa"],
        ),
        CheckDefinition(
            check_id="iam_user_no_attached_policies",
            title="IAM user receives permissions only through groups",
            description="IAM user receives permissions only through groups.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_no_inline_policies",
            title="IAM user does not have inline policies",
            description="IAM user does not have inline policies.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_single_active_access_key",
            title="IAM user has at most one active access key",
            description="IAM user has at most one active access key.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_unused_credentials_45days",
            title="IAM user credentials used within last 45 days",
            description="IAM user credentials used within last 45 days.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="kms_key_rotation_enabled",
            title="KMS key rotation is enabled",
            description="KMS key rotation is enabled.",
            severity="medium",
            provider="aws",
            service="kms",
            category="Encryption",
            tags=["kms", "rotation"],
        ),
        CheckDefinition(
            check_id="lambda_env_no_secrets",
            title="Lambda function environment variables do not contain secrets",
            description="Lambda function environment variables do not contain secrets.",
            severity="high",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda"],
        ),
        CheckDefinition(
            check_id="lambda_runtime_supported",
            title="Lambda function uses supported runtime",
            description="Lambda function uses supported runtime.",
            severity="medium",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda"],
        ),
        CheckDefinition(
            check_id="lambda_vpc_configured",
            title="Lambda function runs in VPC",
            description="Lambda function runs in VPC.",
            severity="low",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda", "networking"],
        ),
        CheckDefinition(
            check_id="macie_enabled",
            title="Amazon Macie is enabled",
            description="Amazon Macie is enabled.",
            severity="medium",
            provider="aws",
            service="macie",
            category="Compliance",
            tags=["macie"],
        ),
        CheckDefinition(
            check_id="rds_auto_minor_upgrade",
            title="RDS instance has auto minor version upgrade enabled",
            description="RDS instance has auto minor version upgrade enabled.",
            severity="low",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds"],
        ),
        CheckDefinition(
            check_id="rds_backup_enabled",
            title="RDS instance has automated backups enabled",
            description="RDS instance has automated backups enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "backup"],
        ),
        CheckDefinition(
            check_id="rds_deletion_protection",
            title="RDS instance has deletion protection enabled",
            description="RDS instance has deletion protection enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds"],
        ),
        CheckDefinition(
            check_id="rds_encryption_enabled",
            title="RDS instance has encryption enabled",
            description="RDS instance has encryption enabled.",
            severity="high",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "encryption"],
        ),
        CheckDefinition(
            check_id="rds_iam_auth_enabled",
            title="RDS instance has IAM authentication enabled",
            description="RDS instance has IAM authentication enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "iam"],
        ),
        CheckDefinition(
            check_id="rds_multi_az_enabled",
            title="RDS instance has Multi-AZ enabled",
            description="RDS instance has Multi-AZ enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds"],
        ),
        CheckDefinition(
            check_id="rds_public_access_disabled",
            title="RDS instance is not publicly accessible",
            description="RDS instance is not publicly accessible.",
            severity="critical",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "public-access"],
        ),
        CheckDefinition(
            check_id="redshift_audit_logging",
            title="Redshift cluster has audit logging enabled",
            description="Redshift cluster has audit logging enabled.",
            severity="medium",
            provider="aws",
            service="redshift",
            category="Database",
            tags=["redshift", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="redshift_cluster_encrypted",
            title="Redshift cluster is encrypted at rest",
            description="Redshift cluster is encrypted at rest.",
            severity="high",
            provider="aws",
            service="redshift",
            category="Database",
            tags=["redshift", "encryption"],
        ),
        CheckDefinition(
            check_id="redshift_cluster_no_public",
            title="Redshift cluster is not publicly accessible",
            description="Redshift cluster is not publicly accessible.",
            severity="critical",
            provider="aws",
            service="redshift",
            category="Database",
            tags=["redshift", "public-access"],
        ),
        CheckDefinition(
            check_id="s3_bucket_encryption_enabled",
            title="S3 bucket has default encryption enabled",
            description="S3 bucket has default encryption enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "encryption"],
        ),
        CheckDefinition(
            check_id="s3_bucket_logging_enabled",
            title="S3 bucket has access logging enabled",
            description="S3 bucket has access logging enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "logging"],
        ),
        CheckDefinition(
            check_id="s3_bucket_mfa_delete",
            title="S3 bucket has MFA Delete enabled",
            description="S3 bucket has MFA Delete enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "mfa", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="s3_bucket_object_lock",
            title="S3 bucket has Object Lock enabled",
            description="S3 bucket has Object Lock enabled.",
            severity="low",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3"],
        ),
        CheckDefinition(
            check_id="s3_bucket_public_access_blocked",
            title="S3 bucket has public access blocked",
            description="S3 bucket has public access blocked.",
            severity="high",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "public-access"],
        ),
        CheckDefinition(
            check_id="s3_bucket_ssl_required",
            title="S3 bucket requires SSL/TLS for data transfer",
            description="S3 bucket requires SSL/TLS for data transfer.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="s3_bucket_versioning_enabled",
            title="S3 bucket has versioning enabled",
            description="S3 bucket has versioning enabled.",
            severity="low",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3"],
        ),
        CheckDefinition(
            check_id="secretsmanager_rotation_enabled",
            title="Secrets Manager secret has rotation enabled",
            description="Secrets Manager secret has rotation enabled.",
            severity="medium",
            provider="aws",
            service="secretsmanager",
            category="Container",
            tags=["secretsmanager", "rotation"],
        ),
        CheckDefinition(
            check_id="securityhub_enabled",
            title="AWS Security Hub is enabled",
            description="AWS Security Hub is enabled.",
            severity="medium",
            provider="aws",
            service="securityhub",
            category="Compliance",
            tags=["securityhub"],
        ),
        CheckDefinition(
            check_id="sns_topic_encrypted",
            title="SNS topic is encrypted",
            description="SNS topic is encrypted.",
            severity="medium",
            provider="aws",
            service="sns",
            category="Logging",
            tags=["sns", "encryption"],
        ),
        CheckDefinition(
            check_id="sns_topic_no_public_access",
            title="SNS topic does not allow public access",
            description="SNS topic does not allow public access.",
            severity="high",
            provider="aws",
            service="sns",
            category="Logging",
            tags=["sns", "public-access"],
        ),
        CheckDefinition(
            check_id="sqs_queue_encrypted",
            title="SQS queue is encrypted",
            description="SQS queue is encrypted.",
            severity="medium",
            provider="aws",
            service="sqs",
            category="Networking",
            tags=["sqs", "encryption"],
        ),
        CheckDefinition(
            check_id="ssm_managed_instances",
            title="All EC2 instances are managed by SSM",
            description="All EC2 instances are managed by SSM.",
            severity="medium",
            provider="aws",
            service="ssm",
            category="Compliance",
            tags=["ssm"],
        ),
        CheckDefinition(
            check_id="vpc_default_sg_restricts_all",
            title="VPC default security group restricts all traffic",
            description="VPC default security group restricts all traffic.",
            severity="high",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="vpc_flow_logs_enabled",
            title="VPC flow logs are enabled",
            description="VPC flow logs are enabled.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="vpc_no_unrestricted_nacl",
            title="VPC NACL does not allow unrestricted inbound traffic",
            description="VPC NACL does not allow unrestricted inbound traffic.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="waf_web_acl_exists",
            title="WAF Web ACL exists in region",
            description="WAF Web ACL exists in region.",
            severity="medium",
            provider="aws",
            service="waf",
            category="Networking",
            tags=["waf"],
        ),
    ]
