"""Check definitions for AWS.

Auto-generated from aws scanner. 154 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all AWS check definitions."""
    return [
        # --- ACM ---
        CheckDefinition(
            check_id="acm_certificate_expiry",
            title="ACM certificate is not expired or expiring soon",
            description="ACM certificate is not expired or expiring soon.",
            severity="high",
            provider="aws",
            service="acm",
            category="Encryption",
            tags=["acm"],
        ),
        CheckDefinition(
            check_id="acm_certificate_transparency_logging",
            title="ACM certificate has transparency logging enabled",
            description="ACM certificate has transparency logging enabled.",
            severity="low",
            provider="aws",
            service="acm",
            category="Encryption",
            tags=["acm", "logging"],
        ),
        # --- API Gateway ---
        CheckDefinition(
            check_id="apigateway_rest_api_logging",
            title="API Gateway REST API stage has logging enabled",
            description="API Gateway REST API stage has logging enabled.",
            severity="medium",
            provider="aws",
            service="apigateway",
            category="Compliance",
            tags=["apigateway", "logging"],
        ),
        CheckDefinition(
            check_id="apigateway_waf_enabled",
            title="API Gateway REST API has WAF associated",
            description="API Gateway REST API has WAF associated.",
            severity="medium",
            provider="aws",
            service="apigateway",
            category="Compliance",
            tags=["apigateway", "waf"],
        ),
        # --- Backup ---
        CheckDefinition(
            check_id="backup_plan_exists",
            title="AWS Backup plan exists in region",
            description="AWS Backup plan exists in region.",
            severity="medium",
            provider="aws",
            service="backup",
            category="Backup",
            tags=["backup"],
        ),
        CheckDefinition(
            check_id="backup_vault_encrypted",
            title="AWS Backup vault is encrypted",
            description="AWS Backup vault is encrypted.",
            severity="high",
            provider="aws",
            service="backup",
            category="Backup",
            tags=["backup", "encryption"],
        ),
        CheckDefinition(
            check_id="backup_vault_lock_enabled",
            title="AWS Backup vault has vault lock enabled",
            description="AWS Backup vault has vault lock enabled.",
            severity="medium",
            provider="aws",
            service="backup",
            category="Backup",
            tags=["backup", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="backup_plan_frequency_adequate",
            title="AWS Backup plan has adequate backup frequency",
            description="AWS Backup plan has adequate backup frequency.",
            severity="medium",
            provider="aws",
            service="backup",
            category="Backup",
            tags=["backup"],
        ),
        # --- CloudFront ---
        CheckDefinition(
            check_id="cloudfront_https_only",
            title="CloudFront distribution enforces HTTPS",
            description="CloudFront distribution enforces HTTPS.",
            severity="high",
            provider="aws",
            service="cloudfront",
            category="CDN",
            tags=["cloudfront", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudfront_waf_enabled",
            title="CloudFront distribution has WAF enabled",
            description="CloudFront distribution has WAF enabled.",
            severity="medium",
            provider="aws",
            service="cloudfront",
            category="CDN",
            tags=["cloudfront", "waf"],
        ),
        CheckDefinition(
            check_id="cloudfront_oai_oac_configured",
            title="CloudFront distribution uses OAI or OAC for S3 origins",
            description="CloudFront distribution uses OAI or OAC for S3 origins.",
            severity="high",
            provider="aws",
            service="cloudfront",
            category="CDN",
            tags=["cloudfront", "s3"],
        ),
        # --- CloudTrail ---
        CheckDefinition(
            check_id="cloudtrail_enabled",
            title="CloudTrail is enabled",
            description="CloudTrail is enabled.",
            severity="critical",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_encrypted",
            title="CloudTrail logs are encrypted with KMS",
            description="CloudTrail logs are encrypted with KMS.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail", "encryption"],
        ),
        CheckDefinition(
            check_id="cloudtrail_integrated_cloudwatch",
            title="CloudTrail is integrated with CloudWatch Logs",
            description="CloudTrail is integrated with CloudWatch Logs.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_log_validation",
            title="CloudTrail log file validation is enabled",
            description="CloudTrail log file validation is enabled.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_multiregion",
            title="CloudTrail is multi-region",
            description="CloudTrail is multi-region.",
            severity="high",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_s3_bucket_logging",
            title="CloudTrail S3 bucket has access logging enabled",
            description="CloudTrail S3 bucket has access logging enabled.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail", "logging"],
        ),
        CheckDefinition(
            check_id="cloudtrail_s3_object_read_events",
            title="CloudTrail logs S3 object-level read events",
            description="CloudTrail logs S3 object-level read events.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        CheckDefinition(
            check_id="cloudtrail_s3_object_write_events",
            title="CloudTrail logs S3 object-level write events",
            description="CloudTrail logs S3 object-level write events.",
            severity="medium",
            provider="aws",
            service="cloudtrail",
            category="Logging",
            tags=["cloudtrail"],
        ),
        # --- CloudWatch ---
        CheckDefinition(
            check_id="cloudwatch_log_group_encrypted",
            title="CloudWatch log group is encrypted",
            description="CloudWatch log group is encrypted.",
            severity="medium",
            provider="aws",
            service="cloudwatch",
            category="Logging",
            tags=["cloudwatch", "encryption"],
        ),
        CheckDefinition(
            check_id="cloudwatch_log_group_retention",
            title="CloudWatch log group has retention policy",
            description="CloudWatch log group has retention policy.",
            severity="low",
            provider="aws",
            service="cloudwatch",
            category="Logging",
            tags=["cloudwatch", "retention"],
        ),
        CheckDefinition(
            check_id="cloudwatch_alarm_configured",
            title="CloudWatch alarms are configured for critical metrics",
            description="CloudWatch alarms are configured for critical metrics.",
            severity="medium",
            provider="aws",
            service="cloudwatch",
            category="Logging",
            tags=["cloudwatch", "monitoring"],
        ),
        # --- Config ---
        CheckDefinition(
            check_id="config_recorder_enabled",
            title="AWS Config recorder is enabled",
            description="AWS Config recorder is enabled.",
            severity="medium",
            provider="aws",
            service="config",
            category="Compliance",
            tags=["config"],
        ),
        CheckDefinition(
            check_id="config_rules_compliant",
            title="AWS Config rules are in compliant state",
            description="AWS Config rules are in compliant state.",
            severity="medium",
            provider="aws",
            service="config",
            category="Compliance",
            tags=["config"],
        ),
        # --- Detective ---
        CheckDefinition(
            check_id="detective_enabled",
            title="Amazon Detective is enabled",
            description="Amazon Detective is enabled.",
            severity="medium",
            provider="aws",
            service="detective",
            category="Threat Detection",
            tags=["detective"],
        ),
        # --- DocumentDB ---
        CheckDefinition(
            check_id="documentdb_cluster_encrypted",
            title="DocumentDB cluster is encrypted at rest",
            description="DocumentDB cluster is encrypted at rest.",
            severity="high",
            provider="aws",
            service="documentdb",
            category="Database",
            tags=["documentdb", "encryption"],
        ),
        # --- DynamoDB ---
        CheckDefinition(
            check_id="dynamodb_pitr_enabled",
            title="DynamoDB table has PITR enabled",
            description="DynamoDB table has PITR enabled.",
            severity="medium",
            provider="aws",
            service="dynamodb",
            category="Database",
            tags=["dynamodb"],
        ),
        CheckDefinition(
            check_id="dynamodb_table_encrypted_kms",
            title="DynamoDB table is encrypted with KMS",
            description="DynamoDB table is encrypted with KMS.",
            severity="medium",
            provider="aws",
            service="dynamodb",
            category="Database",
            tags=["dynamodb", "encryption", "kms"],
        ),
        # --- EC2 / Compute ---
        CheckDefinition(
            check_id="ec2_default_sg_no_traffic",
            title="Default security group restricts all traffic",
            description="Default security group restricts all traffic.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ec2_ebs_default_encryption",
            title="EBS default encryption is enabled",
            description="EBS default encryption is enabled.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "encryption"],
        ),
        CheckDefinition(
            check_id="ec2_ebs_volume_encrypted",
            title="EBS volume is encrypted",
            description="EBS volume is encrypted.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "encryption"],
        ),
        CheckDefinition(
            check_id="ec2_imdsv2_required",
            title="EC2 instance requires IMDSv2",
            description="EC2 instance requires IMDSv2.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2"],
        ),
        CheckDefinition(
            check_id="ec2_instance_no_public_ip",
            title="EC2 instance does not have a public IP address",
            description="EC2 instance does not have a public IP address.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "public-access"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_ipv6_wide_open",
            title="ec2_sg_no_ipv6_wide_open",
            description="ec2_sg_no_ipv6_wide_open.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_wide_open_ports",
            title="Security group does not allow wide port ranges to 0.0.0.0/0",
            description="Security group does not allow wide port ranges to 0.0.0.0/0.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ec2_ami_encrypted",
            title="EC2 AMI snapshots are encrypted",
            description="EC2 AMI snapshots are encrypted.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "encryption"],
        ),
        CheckDefinition(
            check_id="ec2_launch_template_no_public_ip",
            title="EC2 launch template does not assign public IP by default",
            description="EC2 launch template does not assign public IP by default.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "public-access"],
        ),
        CheckDefinition(
            check_id="ec2_autoscaling_health_check",
            title="Auto Scaling group has ELB health check configured",
            description="Auto Scaling group has ELB health check configured.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "autoscaling"],
        ),
        CheckDefinition(
            check_id="ec2_elb_cross_zone_enabled",
            title="ELB has cross-zone load balancing enabled",
            description="ELB has cross-zone load balancing enabled.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "elb"],
        ),
        CheckDefinition(
            check_id="ec2_elb_deletion_protection",
            title="ELB has deletion protection enabled",
            description="ELB has deletion protection enabled.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "elb", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="ec2_elb_access_logging",
            title="ELB has access logging enabled",
            description="ELB has access logging enabled.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "elb", "logging"],
        ),
        CheckDefinition(
            check_id="ec2_nat_gateway_high_availability",
            title="NAT Gateway is deployed in multiple AZs for high availability",
            description="NAT Gateway is deployed in multiple AZs for high availability.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "networking"],
        ),
        CheckDefinition(
            check_id="ec2_eni_security_group_attached",
            title="ENI has security group attached",
            description="ENI has security group attached.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group", "networking"],
        ),
        # --- ECR ---
        CheckDefinition(
            check_id="ecr_image_scanning",
            title="ECR repository has image scanning on push enabled",
            description="ECR repository has image scanning on push enabled.",
            severity="medium",
            provider="aws",
            service="ecr",
            category="Container",
            tags=["ecr"],
        ),
        CheckDefinition(
            check_id="ecr_lifecycle_policy",
            title="ECR repository has lifecycle policy configured",
            description="ECR repository has lifecycle policy configured.",
            severity="low",
            provider="aws",
            service="ecr",
            category="Container",
            tags=["ecr"],
        ),
        # --- ECS ---
        CheckDefinition(
            check_id="ecs_cluster_container_insights",
            title="ECS cluster has Container Insights enabled",
            description="ECS cluster has Container Insights enabled.",
            severity="low",
            provider="aws",
            service="ecs",
            category="Container",
            tags=["ecs"],
        ),
        CheckDefinition(
            check_id="ecs_task_definition_no_privileged",
            title="ECS task definition does not use privileged containers",
            description="ECS task definition does not use privileged containers.",
            severity="high",
            provider="aws",
            service="ecs",
            category="Container",
            tags=["ecs"],
        ),
        CheckDefinition(
            check_id="ecs_fargate_latest_platform",
            title="ECS Fargate service uses latest platform version",
            description="ECS Fargate service uses latest platform version.",
            severity="low",
            provider="aws",
            service="ecs",
            category="Container",
            tags=["ecs"],
        ),
        # --- EFS ---
        CheckDefinition(
            check_id="efs_encryption_enabled",
            title="EFS file system is encrypted",
            description="EFS file system is encrypted.",
            severity="high",
            provider="aws",
            service="efs",
            category="Storage",
            tags=["efs", "encryption"],
        ),
        # --- EKS ---
        CheckDefinition(
            check_id="eks_cluster_logging",
            title="EKS cluster has API logging enabled",
            description="EKS cluster has API logging enabled.",
            severity="medium",
            provider="aws",
            service="eks",
            category="Container",
            tags=["eks", "logging"],
        ),
        CheckDefinition(
            check_id="eks_endpoint_public_access",
            title="EKS cluster endpoint is not publicly accessible",
            description="EKS cluster endpoint is not publicly accessible.",
            severity="high",
            provider="aws",
            service="eks",
            category="Container",
            tags=["eks", "public-access"],
        ),
        CheckDefinition(
            check_id="eks_secrets_encrypted",
            title="EKS cluster has secrets encryption enabled",
            description="EKS cluster has secrets encryption enabled.",
            severity="high",
            provider="aws",
            service="eks",
            category="Container",
            tags=["eks", "encryption"],
        ),
        # --- ElastiCache ---
        CheckDefinition(
            check_id="elasticache_encryption_rest",
            title="ElastiCache cluster has encryption at rest",
            description="ElastiCache cluster has encryption at rest.",
            severity="high",
            provider="aws",
            service="elasticache",
            category="Database",
            tags=["elasticache", "encryption"],
        ),
        CheckDefinition(
            check_id="elasticache_encryption_transit",
            title="ElastiCache cluster has encryption in transit",
            description="ElastiCache cluster has encryption in transit.",
            severity="high",
            provider="aws",
            service="elasticache",
            category="Database",
            tags=["elasticache", "encryption"],
        ),
        # --- Elasticsearch ---
        CheckDefinition(
            check_id="es_encryption_at_rest",
            title="Elasticsearch domain has encryption at rest",
            description="Elasticsearch domain has encryption at rest.",
            severity="high",
            provider="aws",
            service="elasticsearch",
            category="Database",
            tags=["elasticsearch", "encryption"],
        ),
        CheckDefinition(
            check_id="es_node_to_node_encryption",
            title="Elasticsearch domain has node-to-node encryption",
            description="Elasticsearch domain has node-to-node encryption.",
            severity="medium",
            provider="aws",
            service="elasticsearch",
            category="Database",
            tags=["elasticsearch", "encryption"],
        ),
        # --- EventBridge ---
        CheckDefinition(
            check_id="eventbridge_rules_configured",
            title="EventBridge rules are configured for security events",
            description="EventBridge rules are configured for security events.",
            severity="medium",
            provider="aws",
            service="eventbridge",
            category="Logging",
            tags=["eventbridge", "monitoring"],
        ),
        # --- GuardDuty ---
        CheckDefinition(
            check_id="guardduty_enabled",
            title="GuardDuty is enabled",
            description="GuardDuty is enabled.",
            severity="high",
            provider="aws",
            service="guardduty",
            category="Threat Detection",
            tags=["guardduty"],
        ),
        # --- IAM ---
        CheckDefinition(
            check_id="iam_access_analyzer_enabled",
            title="IAM Access Analyzer is enabled",
            description="IAM Access Analyzer is enabled.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_access_key_rotation",
            title="IAM access key is rotated within 90 days",
            description="IAM access key is rotated within 90 days.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="iam_cloudshell_fullaccess_restricted",
            title="AWSCloudShellFullAccess policy is not attached to any entity",
            description="AWSCloudShellFullAccess policy is not attached to any entity.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_group_no_inline_policies",
            title="IAM group does not have inline policies",
            description="IAM group does not have inline policies.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_no_root_access_key",
            title="Root account has no access keys",
            description="Root account has no access keys.",
            severity="critical",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_no_star_policies",
            title="IAM policy does not allow full *:* admin access",
            description="IAM policy does not allow full *:* admin access.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_exists",
            title="IAM password policy is configured",
            description="IAM password policy is configured.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_reuse_prevention",
            title="IAM password policy prevents password reuse (24 or more)",
            description="IAM password policy prevents password reuse (24 or more).",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_rotation",
            title="IAM password policy enforces rotation within 90 days",
            description="IAM password policy enforces rotation within 90 days.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="iam_password_policy_strong",
            title="IAM password policy requires strong passwords",
            description="IAM password policy requires strong passwords.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_root_mfa_enabled",
            title="Root account has MFA enabled",
            description="Root account has MFA enabled.",
            severity="critical",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "mfa"],
        ),
        CheckDefinition(
            check_id="iam_ssl_certificate_expiry",
            title="IAM SSL/TLS certificate is not expired or expiring soon",
            description="IAM SSL/TLS certificate is not expired or expiring soon.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="iam_support_role_created",
            title="IAM Support role has been created for AWS Support access",
            description="IAM Support role has been created for AWS Support access.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_mfa_enabled",
            title="IAM user has MFA enabled",
            description="IAM user has MFA enabled.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "mfa"],
        ),
        CheckDefinition(
            check_id="iam_user_no_attached_policies",
            title="IAM user receives permissions only through groups",
            description="IAM user receives permissions only through groups.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_no_inline_policies",
            title="IAM user does not have inline policies",
            description="IAM user does not have inline policies.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_single_active_access_key",
            title="IAM user has at most one active access key",
            description="IAM user has at most one active access key.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_unused_credentials_45days",
            title="IAM user credentials used within last 45 days",
            description="IAM user credentials used within last 45 days.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_credential_report_generated",
            title="IAM credential report has been generated recently",
            description="IAM credential report has been generated recently.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_user_last_activity_reviewed",
            title="IAM user last activity has been reviewed within 90 days",
            description="IAM user last activity has been reviewed within 90 days.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_unused_credentials_disabled",
            title="IAM unused credentials are disabled",
            description="IAM unused credentials are disabled.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_organizations_scp_enabled",
            title="AWS Organizations service control policies are enabled",
            description="AWS Organizations service control policies are enabled.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "organizations"],
        ),
        CheckDefinition(
            check_id="iam_cross_account_role_restricted",
            title="Cross-account IAM roles have restricted trust policies",
            description="Cross-account IAM roles have restricted trust policies.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_policy_no_star_resource",
            title="IAM policy does not use wildcard resource with service actions",
            description="IAM policy does not use wildcard resource with service actions.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_sso_configured",
            title="AWS IAM Identity Center (SSO) is configured",
            description="AWS IAM Identity Center (SSO) is configured.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "sso"],
        ),
        CheckDefinition(
            check_id="iam_saml_provider_configured",
            title="SAML identity provider is configured for federated access",
            description="SAML identity provider is configured for federated access.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "saml"],
        ),
        # --- Inspector ---
        CheckDefinition(
            check_id="inspector_enabled",
            title="Amazon Inspector is enabled",
            description="Amazon Inspector is enabled.",
            severity="medium",
            provider="aws",
            service="inspector",
            category="Compliance",
            tags=["inspector"],
        ),
        # --- KMS ---
        CheckDefinition(
            check_id="kms_key_rotation_enabled",
            title="KMS key rotation is enabled",
            description="KMS key rotation is enabled.",
            severity="medium",
            provider="aws",
            service="kms",
            category="Encryption",
            tags=["kms", "rotation"],
        ),
        # --- Lambda ---
        CheckDefinition(
            check_id="lambda_env_no_secrets",
            title="Lambda function environment variables do not contain secrets",
            description="Lambda function environment variables do not contain secrets.",
            severity="high",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda"],
        ),
        CheckDefinition(
            check_id="lambda_runtime_supported",
            title="Lambda function uses supported runtime",
            description="Lambda function uses supported runtime.",
            severity="medium",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda"],
        ),
        CheckDefinition(
            check_id="lambda_vpc_configured",
            title="Lambda function runs in VPC",
            description="Lambda function runs in VPC.",
            severity="low",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda", "networking"],
        ),
        CheckDefinition(
            check_id="lambda_concurrency_limit_configured",
            title="Lambda function has reserved concurrency limit configured",
            description="Lambda function has reserved concurrency limit configured.",
            severity="low",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda"],
        ),
        # --- Macie ---
        CheckDefinition(
            check_id="macie_enabled",
            title="Amazon Macie is enabled",
            description="Amazon Macie is enabled.",
            severity="medium",
            provider="aws",
            service="macie",
            category="Compliance",
            tags=["macie"],
        ),
        # --- Neptune ---
        CheckDefinition(
            check_id="neptune_audit_logging_enabled",
            title="Neptune cluster has audit logging enabled",
            description="Neptune cluster has audit logging enabled.",
            severity="medium",
            provider="aws",
            service="neptune",
            category="Database",
            tags=["neptune", "logging", "audit"],
        ),
        # --- RDS ---
        CheckDefinition(
            check_id="rds_auto_minor_upgrade",
            title="RDS instance has auto minor version upgrade enabled",
            description="RDS instance has auto minor version upgrade enabled.",
            severity="low",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds"],
        ),
        CheckDefinition(
            check_id="rds_backup_enabled",
            title="RDS instance has automated backups enabled",
            description="RDS instance has automated backups enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "backup"],
        ),
        CheckDefinition(
            check_id="rds_deletion_protection",
            title="RDS instance has deletion protection enabled",
            description="RDS instance has deletion protection enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds"],
        ),
        CheckDefinition(
            check_id="rds_encryption_enabled",
            title="RDS instance has encryption enabled",
            description="RDS instance has encryption enabled.",
            severity="high",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "encryption"],
        ),
        CheckDefinition(
            check_id="rds_iam_auth_enabled",
            title="RDS instance has IAM authentication enabled",
            description="RDS instance has IAM authentication enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "iam"],
        ),
        CheckDefinition(
            check_id="rds_multi_az_enabled",
            title="RDS instance has Multi-AZ enabled",
            description="RDS instance has Multi-AZ enabled.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds"],
        ),
        CheckDefinition(
            check_id="rds_public_access_disabled",
            title="RDS instance is not publicly accessible",
            description="RDS instance is not publicly accessible.",
            severity="critical",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "public-access"],
        ),
        CheckDefinition(
            check_id="rds_performance_insights_enabled",
            title="RDS instance has Performance Insights enabled",
            description="RDS instance has Performance Insights enabled.",
            severity="low",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "monitoring"],
        ),
        CheckDefinition(
            check_id="rds_enhanced_monitoring_enabled",
            title="RDS instance has enhanced monitoring enabled",
            description="RDS instance has enhanced monitoring enabled.",
            severity="low",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "monitoring"],
        ),
        # --- Redshift ---
        CheckDefinition(
            check_id="redshift_audit_logging",
            title="Redshift cluster has audit logging enabled",
            description="Redshift cluster has audit logging enabled.",
            severity="medium",
            provider="aws",
            service="redshift",
            category="Database",
            tags=["redshift", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="redshift_cluster_encrypted",
            title="Redshift cluster is encrypted at rest",
            description="Redshift cluster is encrypted at rest.",
            severity="high",
            provider="aws",
            service="redshift",
            category="Database",
            tags=["redshift", "encryption"],
        ),
        CheckDefinition(
            check_id="redshift_cluster_no_public",
            title="Redshift cluster is not publicly accessible",
            description="Redshift cluster is not publicly accessible.",
            severity="critical",
            provider="aws",
            service="redshift",
            category="Database",
            tags=["redshift", "public-access"],
        ),
        # --- Route53 ---
        CheckDefinition(
            check_id="route53_dnssec_enabled",
            title="Route 53 hosted zone has DNSSEC signing enabled",
            description="Route 53 hosted zone has DNSSEC signing enabled.",
            severity="medium",
            provider="aws",
            service="route53",
            category="Networking",
            tags=["route53", "dns"],
        ),
        # --- S3 ---
        CheckDefinition(
            check_id="s3_bucket_encryption_enabled",
            title="S3 bucket has default encryption enabled",
            description="S3 bucket has default encryption enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "encryption"],
        ),
        CheckDefinition(
            check_id="s3_bucket_logging_enabled",
            title="S3 bucket has access logging enabled",
            description="S3 bucket has access logging enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "logging"],
        ),
        CheckDefinition(
            check_id="s3_bucket_mfa_delete",
            title="S3 bucket has MFA Delete enabled",
            description="S3 bucket has MFA Delete enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "mfa", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="s3_bucket_object_lock",
            title="S3 bucket has Object Lock enabled",
            description="S3 bucket has Object Lock enabled.",
            severity="low",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3"],
        ),
        CheckDefinition(
            check_id="s3_bucket_public_access_blocked",
            title="S3 bucket has public access blocked",
            description="S3 bucket has public access blocked.",
            severity="high",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "public-access"],
        ),
        CheckDefinition(
            check_id="s3_bucket_ssl_required",
            title="S3 bucket requires SSL/TLS for data transfer",
            description="S3 bucket requires SSL/TLS for data transfer.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="s3_bucket_versioning_enabled",
            title="S3 bucket has versioning enabled",
            description="S3 bucket has versioning enabled.",
            severity="low",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3"],
        ),
        CheckDefinition(
            check_id="s3_bucket_replication_enabled",
            title="S3 bucket has cross-region replication enabled",
            description="S3 bucket has cross-region replication enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "backup"],
        ),
        CheckDefinition(
            check_id="s3_bucket_lifecycle_policy",
            title="S3 bucket has lifecycle policy configured",
            description="S3 bucket has lifecycle policy configured.",
            severity="low",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3"],
        ),
        CheckDefinition(
            check_id="s3_access_point_restricted",
            title="S3 access point has restrictive access policy",
            description="S3 access point has restrictive access policy.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "public-access"],
        ),
        CheckDefinition(
            check_id="s3_glacier_vault_lock",
            title="S3 Glacier vault has vault lock policy enabled",
            description="S3 Glacier vault has vault lock policy enabled.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "glacier", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="s3_bucket_event_notifications",
            title="S3 bucket has event notifications configured",
            description="S3 bucket has event notifications configured.",
            severity="low",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "monitoring"],
        ),
        CheckDefinition(
            check_id="s3_access_logging_separate_bucket",
            title="S3 access logging targets a separate bucket",
            description="S3 access logging targets a separate bucket.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "logging"],
        ),
        # --- Secrets Manager ---
        CheckDefinition(
            check_id="secretsmanager_rotation_enabled",
            title="Secrets Manager secret has rotation enabled",
            description="Secrets Manager secret has rotation enabled.",
            severity="medium",
            provider="aws",
            service="secretsmanager",
            category="Encryption",
            tags=["secretsmanager", "rotation"],
        ),
        # --- Security Hub ---
        CheckDefinition(
            check_id="securityhub_enabled",
            title="AWS Security Hub is enabled",
            description="AWS Security Hub is enabled.",
            severity="medium",
            provider="aws",
            service="securityhub",
            category="Compliance",
            tags=["securityhub"],
        ),
        # --- SNS ---
        CheckDefinition(
            check_id="sns_topic_encrypted",
            title="SNS topic is encrypted",
            description="SNS topic is encrypted.",
            severity="medium",
            provider="aws",
            service="sns",
            category="Logging",
            tags=["sns", "encryption"],
        ),
        CheckDefinition(
            check_id="sns_topic_no_public_access",
            title="SNS topic does not allow public access",
            description="SNS topic does not allow public access.",
            severity="high",
            provider="aws",
            service="sns",
            category="Logging",
            tags=["sns", "public-access"],
        ),
        # --- SQS ---
        CheckDefinition(
            check_id="sqs_queue_encrypted",
            title="SQS queue is encrypted",
            description="SQS queue is encrypted.",
            severity="medium",
            provider="aws",
            service="sqs",
            category="Networking",
            tags=["sqs", "encryption"],
        ),
        # --- SSM ---
        CheckDefinition(
            check_id="ssm_managed_instances",
            title="All EC2 instances are managed by SSM",
            description="All EC2 instances are managed by SSM.",
            severity="medium",
            provider="aws",
            service="ssm",
            category="Compliance",
            tags=["ssm"],
        ),
        CheckDefinition(
            check_id="ssm_compliance_status",
            title="Systems Manager managed instances are compliant",
            description="Systems Manager managed instances are compliant.",
            severity="medium",
            provider="aws",
            service="ssm",
            category="Compliance",
            tags=["ssm"],
        ),
        # --- Step Functions ---
        CheckDefinition(
            check_id="stepfunctions_logging_enabled",
            title="Step Functions state machine has logging enabled",
            description="Step Functions state machine has logging enabled.",
            severity="medium",
            provider="aws",
            service="stepfunctions",
            category="Serverless",
            tags=["stepfunctions", "logging"],
        ),
        # --- VPC / Networking ---
        CheckDefinition(
            check_id="vpc_default_sg_restricts_all",
            title="VPC default security group restricts all traffic",
            description="VPC default security group restricts all traffic.",
            severity="high",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="vpc_flow_logs_enabled",
            title="VPC flow logs are enabled",
            description="VPC flow logs are enabled.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="vpc_no_unrestricted_nacl",
            title="VPC NACL does not allow unrestricted inbound traffic",
            description="VPC NACL does not allow unrestricted inbound traffic.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="vpc_peering_dns_resolution_restricted",
            title="VPC peering DNS resolution is restricted to private IPs",
            description="VPC peering DNS resolution is restricted to private IPs.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="vpc_transit_gateway_auto_accept_disabled",
            title="Transit Gateway does not auto-accept shared attachments",
            description="Transit Gateway does not auto-accept shared attachments.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking"],
        ),
        CheckDefinition(
            check_id="vpc_vpn_tunnel_redundancy",
            title="VPN connection has two tunnels configured for redundancy",
            description="VPN connection has two tunnels configured for redundancy.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking", "vpn"],
        ),
        CheckDefinition(
            check_id="vpc_network_firewall_enabled",
            title="AWS Network Firewall is enabled in VPC",
            description="AWS Network Firewall is enabled in VPC.",
            severity="medium",
            provider="aws",
            service="vpc",
            category="Networking",
            tags=["vpc", "networking", "firewall"],
        ),
        # --- WAF ---
        CheckDefinition(
            check_id="waf_web_acl_exists",
            title="WAF Web ACL exists in region",
            description="WAF Web ACL exists in region.",
            severity="medium",
            provider="aws",
            service="waf",
            category="Networking",
            tags=["waf"],
        ),
        CheckDefinition(
            check_id="waf_web_acl_associated",
            title="WAF Web ACL is associated with resources",
            description="WAF Web ACL is associated with resources.",
            severity="medium",
            provider="aws",
            service="waf",
            category="Networking",
            tags=["waf"],
        ),
        # --- Additional IAM ---
        CheckDefinition(
            check_id="iam_root_no_console_login",
            title="Root account has not logged into console recently",
            description="Root account has not logged into console recently.",
            severity="high",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_role_no_inline_policies",
            title="IAM role does not have inline policies",
            description="IAM role does not have inline policies.",
            severity="medium",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="iam_hardware_mfa_root",
            title="Root account has hardware MFA enabled",
            description="Root account has hardware MFA enabled.",
            severity="critical",
            provider="aws",
            service="iam",
            category="Identity",
            tags=["iam", "mfa"],
        ),
        # --- Additional S3 ---
        CheckDefinition(
            check_id="s3_account_level_public_access_blocked",
            title="S3 account-level public access block is enabled",
            description="S3 account-level public access block is enabled.",
            severity="high",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "public-access"],
        ),
        CheckDefinition(
            check_id="s3_bucket_kms_encryption",
            title="S3 bucket uses KMS for server-side encryption",
            description="S3 bucket uses KMS for server-side encryption.",
            severity="medium",
            provider="aws",
            service="s3",
            category="Storage",
            tags=["s3", "encryption", "kms"],
        ),
        # --- Additional EC2/Compute ---
        CheckDefinition(
            check_id="ec2_ebs_snapshot_encrypted",
            title="EBS snapshot is encrypted",
            description="EBS snapshot is encrypted.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "encryption"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_ssh_open",
            title="Security group does not allow SSH from 0.0.0.0/0",
            description="Security group does not allow SSH from 0.0.0.0/0.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_rdp_open",
            title="Security group does not allow RDP from 0.0.0.0/0",
            description="Security group does not allow RDP from 0.0.0.0/0.",
            severity="high",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "security-group"],
        ),
        CheckDefinition(
            check_id="ec2_autoscaling_launch_config_no_public_ip",
            title="Auto Scaling launch configuration does not assign public IP",
            description="Auto Scaling launch configuration does not assign public IP.",
            severity="medium",
            provider="aws",
            service="ec2",
            category="Compute",
            tags=["ec2", "autoscaling", "public-access"],
        ),
        # --- Additional Database ---
        CheckDefinition(
            check_id="rds_snapshot_encrypted",
            title="RDS snapshot is encrypted",
            description="RDS snapshot is encrypted.",
            severity="medium",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "encryption"],
        ),
        CheckDefinition(
            check_id="rds_event_subscription_enabled",
            title="RDS event subscriptions are configured",
            description="RDS event subscriptions are configured.",
            severity="low",
            provider="aws",
            service="rds",
            category="Database",
            tags=["rds", "monitoring"],
        ),
        CheckDefinition(
            check_id="redshift_encryption_in_transit",
            title="Redshift cluster enforces SSL for connections",
            description="Redshift cluster enforces SSL for connections.",
            severity="high",
            provider="aws",
            service="redshift",
            category="Database",
            tags=["redshift", "encryption", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="elasticache_auto_minor_upgrade",
            title="ElastiCache cluster has auto minor version upgrade enabled",
            description="ElastiCache cluster has auto minor version upgrade enabled.",
            severity="low",
            provider="aws",
            service="elasticache",
            category="Database",
            tags=["elasticache"],
        ),
        # --- Additional Logging/Monitoring ---
        CheckDefinition(
            check_id="cloudwatch_alarm_action_configured",
            title="CloudWatch alarm has actions configured",
            description="CloudWatch alarm has actions configured.",
            severity="medium",
            provider="aws",
            service="cloudwatch",
            category="Logging",
            tags=["cloudwatch", "monitoring"],
        ),
        CheckDefinition(
            check_id="guardduty_findings_archived",
            title="GuardDuty high-severity findings are reviewed and archived",
            description="GuardDuty high-severity findings are reviewed and archived.",
            severity="high",
            provider="aws",
            service="guardduty",
            category="Threat Detection",
            tags=["guardduty"],
        ),
        # --- Additional Lambda/Containers ---
        CheckDefinition(
            check_id="lambda_dlq_configured",
            title="Lambda function has dead-letter queue configured",
            description="Lambda function has dead-letter queue configured.",
            severity="low",
            provider="aws",
            service="lambda",
            category="Serverless",
            tags=["lambda"],
        ),
        CheckDefinition(
            check_id="ecs_task_definition_logging",
            title="ECS task definition has logging configured",
            description="ECS task definition has logging configured.",
            severity="medium",
            provider="aws",
            service="ecs",
            category="Container",
            tags=["ecs", "logging"],
        ),
        CheckDefinition(
            check_id="ecr_repository_encrypted",
            title="ECR repository has encryption at rest enabled",
            description="ECR repository has encryption at rest enabled.",
            severity="medium",
            provider="aws",
            service="ecr",
            category="Container",
            tags=["ecr", "encryption"],
        ),
        # --- Additional Encryption/Storage ---
        CheckDefinition(
            check_id="kms_key_not_pending_deletion",
            title="KMS key is not scheduled for deletion",
            description="KMS key is not scheduled for deletion.",
            severity="high",
            provider="aws",
            service="kms",
            category="Encryption",
            tags=["kms"],
        ),
        # --- Supplementary: MITRE/RR orphan resolution ---
        CheckDefinition(
            check_id="ec2_sg_open_port_22",
            title="Security group allows unrestricted SSH access (port 22)",
            description="Security group allows unrestricted SSH access (port 22).",
            severity="high",
            provider="aws",
            service="EC2",
            category="Networking",
            scanner_check_ids=["ec2_sg_open_port_22"],
            source="scanner",
            tags=["ec2", "networking", "ssh"],
        ),
        CheckDefinition(
            check_id="ec2_sg_open_port_3389",
            title="Security group allows unrestricted RDP access (port 3389)",
            description="Security group allows unrestricted RDP access (port 3389).",
            severity="high",
            provider="aws",
            service="EC2",
            category="Networking",
            scanner_check_ids=["ec2_sg_open_port_3389"],
            source="scanner",
            tags=["ec2", "networking", "rdp"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_public_ssh",
            title="Security group does not allow public SSH ingress",
            description="Security group does not allow public SSH ingress.",
            severity="high",
            provider="aws",
            service="EC2",
            category="Networking",
            scanner_check_ids=["ec2_sg_no_public_ssh"],
            rr_relevant=True,
            rr_domains=["D4"],
            source="scanner",
            tags=["ec2", "networking", "ssh"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_public_rdp",
            title="Security group does not allow public RDP ingress",
            description="Security group does not allow public RDP ingress.",
            severity="high",
            provider="aws",
            service="EC2",
            category="Networking",
            scanner_check_ids=["ec2_sg_no_public_rdp"],
            rr_relevant=True,
            rr_domains=["D4"],
            source="scanner",
            tags=["ec2", "networking", "rdp"],
        ),
        CheckDefinition(
            check_id="ec2_sg_no_public_smb",
            title="Security group does not allow public SMB ingress",
            description="Security group does not allow public SMB ingress.",
            severity="high",
            provider="aws",
            service="EC2",
            category="Networking",
            scanner_check_ids=["ec2_sg_no_public_smb"],
            rr_relevant=True,
            rr_domains=["D4"],
            source="scanner",
            tags=["ec2", "networking", "smb"],
        ),
        CheckDefinition(
            check_id="ecs_task_definition_no_root",
            title="ECS task definition does not run as root",
            description="ECS task definition does not run as root.",
            severity="high",
            provider="aws",
            service="ECS",
            category="Container",
            scanner_check_ids=["ecs_task_definition_no_root"],
            source="scanner",
            tags=["ecs", "container", "privilege-escalation"],
        ),
        CheckDefinition(
            check_id="elasticache_encryption_in_transit",
            title="ElastiCache cluster has encryption in transit enabled",
            description="ElastiCache cluster has encryption in transit enabled.",
            severity="high",
            provider="aws",
            service="ElastiCache",
            category="Encryption",
            scanner_check_ids=["elasticache_encryption_in_transit"],
            source="scanner",
            tags=["elasticache", "encryption"],
        ),
        CheckDefinition(
            check_id="elasticsearch_encrypted_at_rest",
            title="Elasticsearch domain is encrypted at rest",
            description="Elasticsearch domain is encrypted at rest.",
            severity="high",
            provider="aws",
            service="Elasticsearch",
            category="Encryption",
            scanner_check_ids=["elasticsearch_encrypted_at_rest"],
            source="scanner",
            tags=["elasticsearch", "encryption"],
        ),
        CheckDefinition(
            check_id="lambda_function_public_access",
            title="Lambda function does not have public access",
            description="Lambda function does not have public access.",
            severity="critical",
            provider="aws",
            service="Lambda",
            category="Serverless",
            scanner_check_ids=["lambda_function_public_access"],
            source="scanner",
            tags=["lambda", "serverless", "public-access"],
        ),
        CheckDefinition(
            check_id="acm_certificate_not_expiring",
            title="ACM certificate is not expiring within 30 days",
            description="ACM certificate is not expiring within 30 days.",
            severity="high",
            provider="aws",
            service="ACM",
            category="Encryption",
            scanner_check_ids=["acm_certificate_not_expiring"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["acm", "encryption", "certificates"],
        ),
        CheckDefinition(
            check_id="backup_cross_account_enabled",
            title="AWS Backup cross-account backup is enabled",
            description="AWS Backup cross-account backup is enabled.",
            severity="high",
            provider="aws",
            service="Backup",
            category="Backup",
            scanner_check_ids=["backup_cross_account_enabled"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["backup", "cross-account"],
        ),
        CheckDefinition(
            check_id="backup_cross_region_enabled",
            title="AWS Backup cross-region backup is enabled",
            description="AWS Backup cross-region backup is enabled.",
            severity="high",
            provider="aws",
            service="Backup",
            category="Backup",
            scanner_check_ids=["backup_cross_region_enabled"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["backup", "cross-region"],
        ),
        CheckDefinition(
            check_id="backup_vault_access_policy_restrictive",
            title="Backup vault access policy is restrictive",
            description="Backup vault access policy is restrictive.",
            severity="high",
            provider="aws",
            service="Backup",
            category="Backup",
            scanner_check_ids=["backup_vault_access_policy_restrictive"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["backup", "access-policy"],
        ),
        CheckDefinition(
            check_id="dynamodb_backup_enabled",
            title="DynamoDB table has backup enabled",
            description="DynamoDB table has backup enabled.",
            severity="medium",
            provider="aws",
            service="DynamoDB",
            category="Database",
            scanner_check_ids=["dynamodb_backup_enabled"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["dynamodb", "backup"],
        ),
        CheckDefinition(
            check_id="ebs_cmk_encryption",
            title="EBS volumes are encrypted with CMK",
            description="EBS volumes are encrypted with customer-managed keys.",
            severity="high",
            provider="aws",
            service="EBS",
            category="Encryption",
            scanner_check_ids=["ebs_cmk_encryption"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["ebs", "encryption", "cmk"],
        ),
        CheckDefinition(
            check_id="ebs_snapshot_lifecycle",
            title="EBS snapshot lifecycle policy is configured",
            description="EBS snapshot lifecycle policy is configured.",
            severity="medium",
            provider="aws",
            service="EBS",
            category="Backup",
            scanner_check_ids=["ebs_snapshot_lifecycle"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["ebs", "backup", "lifecycle"],
        ),
        CheckDefinition(
            check_id="ec2_dlm_policy_configured",
            title="EC2 Data Lifecycle Manager policy is configured",
            description="EC2 Data Lifecycle Manager policy is configured.",
            severity="medium",
            provider="aws",
            service="EC2",
            category="Backup",
            scanner_check_ids=["ec2_dlm_policy_configured"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["ec2", "backup", "dlm"],
        ),
        CheckDefinition(
            check_id="ec2_snapshot_encrypted",
            title="EC2 snapshot is encrypted",
            description="EC2 snapshot is encrypted.",
            severity="high",
            provider="aws",
            service="EC2",
            category="Encryption",
            scanner_check_ids=["ec2_snapshot_encrypted"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["ec2", "encryption", "snapshots"],
        ),
        CheckDefinition(
            check_id="eks_backup_configured",
            title="EKS cluster backup is configured",
            description="EKS cluster backup is configured.",
            severity="high",
            provider="aws",
            service="EKS",
            category="Container",
            scanner_check_ids=["eks_backup_configured"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["eks", "backup", "container"],
        ),
        CheckDefinition(
            check_id="iam_break_glass_account_exists",
            title="IAM break-glass account exists for emergency access",
            description="IAM break-glass account exists for emergency access.",
            severity="high",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_break_glass_account_exists"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "break-glass"],
        ),
        CheckDefinition(
            check_id="iam_cross_account_access_controlled",
            title="IAM cross-account access is controlled",
            description="IAM cross-account access is controlled.",
            severity="high",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_cross_account_access_controlled"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "cross-account"],
        ),
        CheckDefinition(
            check_id="iam_ip_condition_policies",
            title="IAM policies use IP condition restrictions",
            description="IAM policies use IP condition restrictions.",
            severity="medium",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_ip_condition_policies"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "ip-restriction"],
        ),
        CheckDefinition(
            check_id="iam_irsa_enabled_eks",
            title="IAM Roles for Service Accounts (IRSA) is enabled on EKS",
            description="IAM Roles for Service Accounts (IRSA) is enabled on EKS.",
            severity="high",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_irsa_enabled_eks"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "eks", "irsa"],
        ),
        CheckDefinition(
            check_id="iam_no_permanent_admin_access",
            title="No permanent administrative access configured",
            description="No permanent administrative access configured.",
            severity="critical",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_no_permanent_admin_access"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "least-privilege"],
        ),
        CheckDefinition(
            check_id="iam_permission_boundaries_applied",
            title="IAM permission boundaries are applied",
            description="IAM permission boundaries are applied.",
            severity="medium",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_permission_boundaries_applied"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "permission-boundaries"],
        ),
        CheckDefinition(
            check_id="iam_role_max_session_duration",
            title="IAM role maximum session duration is configured",
            description="IAM role maximum session duration is configured.",
            severity="medium",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_role_max_session_duration"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "session"],
        ),
        CheckDefinition(
            check_id="iam_root_no_recent_usage",
            title="Root account has no recent usage",
            description="Root account has no recent usage.",
            severity="critical",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_root_no_recent_usage"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "root"],
        ),
        CheckDefinition(
            check_id="iam_security_contact_configured",
            title="IAM security contact is configured",
            description="IAM security contact is configured.",
            severity="medium",
            provider="aws",
            service="IAM",
            category="Governance",
            scanner_check_ids=["iam_security_contact_configured"],
            rr_relevant=True,
            rr_domains=["D7"],
            source="scanner",
            tags=["iam", "governance", "contact"],
        ),
        CheckDefinition(
            check_id="iam_unused_permissions_cleanup",
            title="Unused IAM permissions are cleaned up",
            description="Unused IAM permissions are cleaned up.",
            severity="medium",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_unused_permissions_cleanup"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "least-privilege"],
        ),
        CheckDefinition(
            check_id="iam_user_single_active_key",
            title="IAM user has only one active access key",
            description="IAM user has only one active access key.",
            severity="medium",
            provider="aws",
            service="IAM",
            category="Identity",
            scanner_check_ids=["iam_user_single_active_key"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["iam", "identity", "access-keys"],
        ),
        CheckDefinition(
            check_id="kms_key_deletion_protection",
            title="KMS key has deletion protection enabled",
            description="KMS key has deletion protection enabled.",
            severity="high",
            provider="aws",
            service="KMS",
            category="Encryption",
            scanner_check_ids=["kms_key_deletion_protection"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["kms", "encryption", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="kms_key_policy_restrictive",
            title="KMS key policy is restrictive",
            description="KMS key policy is restrictive.",
            severity="high",
            provider="aws",
            service="KMS",
            category="Encryption",
            scanner_check_ids=["kms_key_policy_restrictive"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["kms", "encryption", "key-policy"],
        ),
        CheckDefinition(
            check_id="lambda_versioning_enabled",
            title="Lambda function versioning is enabled",
            description="Lambda function versioning is enabled.",
            severity="medium",
            provider="aws",
            service="Lambda",
            category="Serverless",
            scanner_check_ids=["lambda_versioning_enabled"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["lambda", "serverless", "versioning"],
        ),
        CheckDefinition(
            check_id="rds_cmk_encryption",
            title="RDS instance is encrypted with CMK",
            description="RDS instance is encrypted with customer-managed keys.",
            severity="high",
            provider="aws",
            service="RDS",
            category="Database",
            scanner_check_ids=["rds_cmk_encryption"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["rds", "encryption", "cmk"],
        ),
        CheckDefinition(
            check_id="rds_pitr_enabled",
            title="RDS point-in-time recovery is enabled",
            description="RDS point-in-time recovery is enabled.",
            severity="high",
            provider="aws",
            service="RDS",
            category="Backup",
            scanner_check_ids=["rds_pitr_enabled"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["rds", "backup", "pitr"],
        ),
        CheckDefinition(
            check_id="rds_ssl_enforced",
            title="RDS SSL/TLS connections are enforced",
            description="RDS SSL/TLS connections are enforced.",
            severity="high",
            provider="aws",
            service="RDS",
            category="Encryption",
            scanner_check_ids=["rds_ssl_enforced"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["rds", "encryption", "ssl"],
        ),
        CheckDefinition(
            check_id="s3_bucket_cmk_encryption",
            title="S3 bucket is encrypted with CMK",
            description="S3 bucket is encrypted with customer-managed keys.",
            severity="high",
            provider="aws",
            service="S3",
            category="Encryption",
            scanner_check_ids=["s3_bucket_cmk_encryption"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["s3", "encryption", "cmk"],
        ),
        CheckDefinition(
            check_id="s3_bucket_lifecycle_configured",
            title="S3 bucket lifecycle policy is configured",
            description="S3 bucket lifecycle policy is configured.",
            severity="medium",
            provider="aws",
            service="S3",
            category="Storage",
            scanner_check_ids=["s3_bucket_lifecycle_configured"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["s3", "storage", "lifecycle"],
        ),
        CheckDefinition(
            check_id="tagging_compliance",
            title="Resources have required tagging applied",
            description="Resources have required tagging applied.",
            severity="low",
            provider="aws",
            service="General",
            category="Governance",
            scanner_check_ids=["tagging_compliance"],
            rr_relevant=True,
            rr_domains=["D5"],
            source="scanner",
            tags=["governance", "tagging"],
        ),
        CheckDefinition(
            check_id="vpc_environment_segmentation",
            title="VPC environment segmentation is configured",
            description="VPC environment segmentation is configured.",
            severity="high",
            provider="aws",
            service="VPC",
            category="Networking",
            scanner_check_ids=["vpc_environment_segmentation"],
            rr_relevant=True,
            rr_domains=["D4"],
            source="scanner",
            tags=["vpc", "networking", "segmentation"],
        ),
    ]
