"""Check definitions for Azure.

Auto-generated from azure scanner. 124 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Azure check definitions."""
    return [
        CheckDefinition(
            check_id="azure_acr_content_trust",
            title="Container registry has content trust enabled",
            description="Container registry has content trust enabled.",
            severity="medium",
            provider="azure",
            service="devops",
            category="DevOps",
            tags=["devops"],
        ),
        CheckDefinition(
            check_id="azure_acr_vulnerability_scan",
            title="Container registry has vulnerability scanning enabled",
            description="Container registry has vulnerability scanning enabled.",
            severity="high",
            provider="azure",
            service="devops",
            category="DevOps",
            tags=["devops"],
        ),
        CheckDefinition(
            check_id="azure_action_groups_configured",
            title="Action groups are configured for alert routing",
            description="Action groups are configured for alert routing.",
            severity="medium",
            provider="azure",
            service="incidentresponse",
            category="Compliance",
            tags=["incidentresponse"],
        ),
        CheckDefinition(
            check_id="azure_adaptive_app_controls",
            title="Adaptive application controls are enforced on VMs",
            description="Adaptive application controls are enforced on VMs.",
            severity="medium",
            provider="azure",
            service="endpoint",
            category="Compliance",
            tags=["endpoint"],
        ),
        CheckDefinition(
            check_id="azure_aks_aad_integration",
            title="AKS cluster is integrated with Azure AD",
            description="AKS cluster is integrated with Azure AD.",
            severity="medium",
            provider="azure",
            service="containerservice",
            category="Compliance",
            tags=["containerservice"],
        ),
        CheckDefinition(
            check_id="azure_aks_authorized_ip_ranges",
            title="AKS cluster has authorized IP ranges",
            description="AKS cluster has authorized IP ranges.",
            severity="high",
            provider="azure",
            service="containerservice",
            category="Compliance",
            tags=["containerservice"],
        ),
        CheckDefinition(
            check_id="azure_aks_azure_policy_addon",
            title="AKS cluster has Azure Policy add-on enabled",
            description="AKS cluster has Azure Policy add-on enabled.",
            severity="medium",
            provider="azure",
            service="containerservice",
            category="Compliance",
            tags=["containerservice"],
        ),
        CheckDefinition(
            check_id="azure_aks_network_policy",
            title="AKS cluster has network policy configured",
            description="AKS cluster has network policy configured.",
            severity="medium",
            provider="azure",
            service="containerservice",
            category="Compliance",
            tags=["containerservice"],
        ),
        CheckDefinition(
            check_id="azure_aks_rbac_enabled",
            title="AKS cluster has RBAC enabled",
            description="AKS cluster has RBAC enabled.",
            severity="high",
            provider="azure",
            service="containerservice",
            category="Compliance",
            tags=["containerservice"],
        ),
        CheckDefinition(
            check_id="azure_alert_notifications_enabled",
            title="Email notifications are enabled for high severity alerts",
            description="Email notifications are enabled for high severity alerts.",
            severity="high",
            provider="azure",
            service="incidentresponse",
            category="Compliance",
            tags=["incidentresponse"],
        ),
        CheckDefinition(
            check_id="azure_alert_rules_with_actions",
            title="Alert rules are associated with action groups",
            description="Alert rules are associated with action groups.",
            severity="medium",
            provider="azure",
            service="incidentresponse",
            category="Compliance",
            tags=["incidentresponse"],
        ),
        CheckDefinition(
            check_id="azure_appgw_http2_enabled",
            title="Application Gateway has HTTP/2 enabled",
            description="Application Gateway has HTTP/2 enabled.",
            severity="low",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="azure_appgw_tls_12",
            title="Application Gateway enforces TLS 1.2 minimum",
            description="Application Gateway enforces TLS 1.2 minimum.",
            severity="high",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="azure_appgw_waf_enabled",
            title="Application Gateway has WAF enabled",
            description="Application Gateway has WAF enabled.",
            severity="high",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "waf"],
        ),
        CheckDefinition(
            check_id="azure_appservice_client_certs",
            title="App Service has client certificate requirement",
            description="App Service has client certificate requirement.",
            severity="medium",
            provider="azure",
            service="appservice",
            category="Compliance",
            tags=["appservice"],
        ),
        CheckDefinition(
            check_id="azure_appservice_ftp_disabled",
            title="App Service has FTP/FTPS disabled",
            description="App Service has FTP/FTPS disabled.",
            severity="high",
            provider="azure",
            service="appservice",
            category="Compliance",
            tags=["appservice"],
        ),
        CheckDefinition(
            check_id="azure_appservice_http_logging",
            title="App Service has HTTP logging enabled",
            description="App Service has HTTP logging enabled.",
            severity="low",
            provider="azure",
            service="appservice",
            category="Compliance",
            tags=["appservice", "logging"],
        ),
        CheckDefinition(
            check_id="azure_appservice_https_only",
            title="App Service requires HTTPS",
            description="App Service requires HTTPS.",
            severity="high",
            provider="azure",
            service="appservice",
            category="Compliance",
            tags=["appservice", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="azure_appservice_managed_identity",
            title="App Service uses managed identity",
            description="App Service uses managed identity.",
            severity="medium",
            provider="azure",
            service="appservice",
            category="Compliance",
            tags=["appservice"],
        ),
        CheckDefinition(
            check_id="azure_appservice_remote_debugging_off",
            title="App Service has remote debugging disabled",
            description="App Service has remote debugging disabled.",
            severity="high",
            provider="azure",
            service="appservice",
            category="Compliance",
            tags=["appservice"],
        ),
        CheckDefinition(
            check_id="azure_appservice_tls_12",
            title="App Service uses TLS 1.2",
            description="App Service uses TLS 1.2.",
            severity="high",
            provider="azure",
            service="appservice",
            category="Compliance",
            tags=["appservice", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="azure_backup_vault_exists",
            title="Recovery Services vault is configured",
            description="Recovery Services vault is configured.",
            severity="medium",
            provider="azure",
            service="backup",
            category="Backup",
            tags=["backup"],
        ),
        CheckDefinition(
            check_id="azure_backup_vault_redundancy",
            title="Recovery Services vault has appropriate redundancy",
            description="Recovery Services vault has appropriate redundancy.",
            severity="medium",
            provider="azure",
            service="backup",
            category="Backup",
            tags=["backup"],
        ),
        CheckDefinition(
            check_id="azure_bastion_host_exists",
            title="Azure Bastion Host is deployed",
            description="Azure Bastion Host is deployed.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="azure_classic_admins_removed",
            title="Classic subscription administrators are removed",
            description="Classic subscription administrators are removed.",
            severity="high",
            provider="azure",
            service="privilegedaccess",
            category="Compliance",
            tags=["privilegedaccess"],
        ),
        CheckDefinition(
            check_id="azure_critical_operation_alerts",
            title="Activity log alerts cover critical security operations",
            description="Activity log alerts cover critical security operations.",
            severity="high",
            provider="azure",
            service="incidentresponse",
            category="Compliance",
            tags=["incidentresponse"],
        ),
        CheckDefinition(
            check_id="azure_ddos_protection_enabled",
            title="DDoS Protection Standard is enabled on VNets",
            description="DDoS Protection Standard is enabled on VNets.",
            severity="high",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="azure_defender_auto_provisioning",
            title="Auto provisioning of monitoring agent is enabled",
            description="Auto provisioning of monitoring agent is enabled.",
            severity="medium",
            provider="azure",
            service="defender",
            category="Threat Detection",
            tags=["defender"],
        ),
        CheckDefinition(
            check_id="azure_devops_iac_scanning",
            title="Infrastructure as Code templates are scanned for misconfigurations",
            description="Infrastructure as Code templates are scanned for misconfigurations.",
            severity="medium",
            provider="azure",
            service="devops",
            category="DevOps",
            tags=["devops"],
        ),
        CheckDefinition(
            check_id="azure_devops_secret_scanning",
            title="Code repositories have secret scanning enabled",
            description="Code repositories have secret scanning enabled.",
            severity="critical",
            provider="azure",
            service="devops",
            category="DevOps",
            tags=["devops"],
        ),
        CheckDefinition(
            check_id="azure_devops_secure_pipelines",
            title="Deployment pipelines enforce security gates",
            description="Deployment pipelines enforce security gates.",
            severity="high",
            provider="azure",
            service="devops",
            category="DevOps",
            tags=["devops"],
        ),
        CheckDefinition(
            check_id="azure_devops_security_enabled",
            title="DevOps security posture management is enabled",
            description="DevOps security posture management is enabled.",
            severity="high",
            provider="azure",
            service="devops",
            category="DevOps",
            tags=["devops"],
        ),
        CheckDefinition(
            check_id="azure_devops_supply_chain",
            title="Software supply chain security is configured",
            description="Software supply chain security is configured.",
            severity="high",
            provider="azure",
            service="devops",
            category="DevOps",
            tags=["devops"],
        ),
        CheckDefinition(
            check_id="azure_disk_unattached_encrypted",
            title="Unattached disk has encryption beyond platform key",
            description="Unattached disk has encryption beyond platform key.",
            severity="medium",
            provider="azure",
            service="compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="azure_endpoint_protection_installed",
            title="Endpoint protection solution is installed on VMs",
            description="Endpoint protection solution is installed on VMs.",
            severity="critical",
            provider="azure",
            service="endpoint",
            category="Compliance",
            tags=["endpoint"],
        ),
        CheckDefinition(
            check_id="azure_entra_admin_center_restricted",
            title="Access to Entra admin center is restricted",
            description="Access to Entra admin center is restricted.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_admin_password_reset_notification",
            title="Admins are notified when other admins reset passwords",
            description="Admins are notified when other admins reset passwords.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_app_registration_restricted",
            title="Users are restricted from registering applications",
            description="Users are restricted from registering applications.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_custom_banned_passwords",
            title="Custom banned password list is enforced",
            description="Custom banned password list is enforced.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_device_mfa_required",
            title="Device registration requires MFA",
            description="Device registration requires MFA.",
            severity="high",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra", "mfa"],
        ),
        CheckDefinition(
            check_id="azure_entra_global_admin_count",
            title="Global administrator count is between 2 and 4",
            description="Global administrator count is between 2 and 4.",
            severity="high",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_group_membership_restricted",
            title="Group membership visibility is restricted",
            description="Group membership visibility is restricted.",
            severity="low",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_guest_access_restricted",
            title="Guest user access is restricted",
            description="Guest user access is restricted.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_guest_invite_restricted",
            title="Guest invitation is restricted to admins",
            description="Guest invitation is restricted to admins.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_lockout_duration",
            title="Account lockout duration is at least 60 seconds",
            description="Account lockout duration is at least 60 seconds.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_lockout_threshold",
            title="Account lockout threshold is 10 or fewer attempts",
            description="Account lockout threshold is 10 or fewer attempts.",
            severity="high",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_m365_group_creation_restricted",
            title="Microsoft 365 group creation is restricted",
            description="Microsoft 365 group creation is restricted.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_mygroups_restricted",
            title="azure_entra_mygroups_restricted",
            description="azure_entra_mygroups_restricted.",
            severity="low",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_password_reset_notification",
            title="Users are notified on password reset",
            description="Users are notified on password reset.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_passwordless_auth",
            title="Passwordless authentication methods are enabled",
            description="Passwordless authentication methods are enabled.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_restrict_tenant_creation",
            title="Non-admin users are restricted from creating tenants",
            description="Non-admin users are restricted from creating tenants.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_security_group_creation_restricted",
            title="Security group creation is restricted to admins",
            description="Security group creation is restricted to admins.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_sspr_reconfirm_days",
            title="SSPR reconfirmation interval is configured",
            description="SSPR reconfirmation interval is configured.",
            severity="low",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_sspr_two_methods",
            title="SSPR requires two authentication methods",
            description="SSPR requires two authentication methods.",
            severity="high",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_user_consent_disabled",
            title="User consent for applications is disabled or restricted",
            description="User consent for applications is disabled or restricted.",
            severity="high",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_entra_verified_publisher_consent",
            title="User consent is restricted to verified publishers only",
            description="User consent is restricted to verified publishers only.",
            severity="medium",
            provider="azure",
            service="entra",
            category="Compliance",
            tags=["entra"],
        ),
        CheckDefinition(
            check_id="azure_iam_contributor_count",
            title="Contributor role assignments are limited",
            description="Contributor role assignments are limited.",
            severity="medium",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity", "iam"],
        ),
        CheckDefinition(
            check_id="azure_iam_guest_users_reviewed",
            title="Guest user access is limited and reviewed",
            description="Guest user access is limited and reviewed.",
            severity="medium",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity", "iam"],
        ),
        CheckDefinition(
            check_id="azure_iam_managed_identity_usage",
            title="Managed identities are used instead of service principal secrets",
            description="Managed identities are used instead of service principal secrets.",
            severity="medium",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity", "iam"],
        ),
        CheckDefinition(
            check_id="azure_iam_mfa_enabled_all_users",
            title="MFA is enabled for all users",
            description="MFA is enabled for all users.",
            severity="critical",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity", "iam", "mfa"],
        ),
        CheckDefinition(
            check_id="azure_iam_no_custom_owner_roles",
            title="No custom subscription owner roles exist",
            description="No custom subscription owner roles exist.",
            severity="high",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity", "iam"],
        ),
        CheckDefinition(
            check_id="azure_iam_owner_count",
            title="Subscription has limited number of owners",
            description="Subscription has limited number of owners.",
            severity="high",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity", "iam"],
        ),
        CheckDefinition(
            check_id="azure_iam_sp_high_privilege",
            title="Service principals with high privilege roles are limited",
            description="Service principals with high privilege roles are limited.",
            severity="high",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity", "iam"],
        ),
        CheckDefinition(
            check_id="azure_incident_playbooks",
            title="Incident response playbooks are configured",
            description="Incident response playbooks are configured.",
            severity="medium",
            provider="azure",
            service="incidentresponse",
            category="Compliance",
            tags=["incidentresponse"],
        ),
        CheckDefinition(
            check_id="azure_jit_vm_access",
            title="Just-In-Time VM access is configured",
            description="Just-In-Time VM access is configured.",
            severity="high",
            provider="azure",
            service="endpoint",
            category="Compliance",
            tags=["endpoint"],
        ),
        CheckDefinition(
            check_id="azure_keyvault_certificate_validity",
            title="Key Vault certificate has expiration and auto-renewal configured",
            description="Key Vault certificate has expiration and auto-renewal configured.",
            severity="medium",
            provider="azure",
            service="keyvault",
            category="Encryption",
            tags=["keyvault"],
        ),
        CheckDefinition(
            check_id="azure_keyvault_key_expiration",
            title="Key Vault key has expiration date set",
            description="Key Vault key has expiration date set.",
            severity="medium",
            provider="azure",
            service="keyvault",
            category="Encryption",
            tags=["keyvault"],
        ),
        CheckDefinition(
            check_id="azure_keyvault_network_acls",
            title="Key Vault has network ACLs configured",
            description="Key Vault has network ACLs configured.",
            severity="high",
            provider="azure",
            service="keyvault",
            category="Encryption",
            tags=["keyvault"],
        ),
        CheckDefinition(
            check_id="azure_keyvault_purge_protection",
            title="Key Vault has purge protection enabled",
            description="Key Vault has purge protection enabled.",
            severity="medium",
            provider="azure",
            service="keyvault",
            category="Encryption",
            tags=["keyvault"],
        ),
        CheckDefinition(
            check_id="azure_keyvault_rbac_authorization",
            title="Key Vault uses RBAC authorization",
            description="Key Vault uses RBAC authorization.",
            severity="medium",
            provider="azure",
            service="keyvault",
            category="Encryption",
            tags=["keyvault"],
        ),
        CheckDefinition(
            check_id="azure_keyvault_secret_expiration",
            title="Key Vault secret has expiration date set",
            description="Key Vault secret has expiration date set.",
            severity="medium",
            provider="azure",
            service="keyvault",
            category="Encryption",
            tags=["keyvault"],
        ),
        CheckDefinition(
            check_id="azure_keyvault_soft_delete",
            title="Key Vault has soft delete enabled",
            description="Key Vault has soft delete enabled.",
            severity="medium",
            provider="azure",
            service="keyvault",
            category="Encryption",
            tags=["keyvault", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="azure_monitor_diagnostic_settings",
            title="Diagnostic settings configured for subscription",
            description="Diagnostic settings configured for subscription.",
            severity="medium",
            provider="azure",
            service="monitor",
            category="Logging",
            tags=["monitor"],
        ),
        CheckDefinition(
            check_id="azure_monitor_log_profile",
            title="Activity log profile is configured",
            description="Activity log profile is configured.",
            severity="medium",
            provider="azure",
            service="monitor",
            category="Logging",
            tags=["monitor"],
        ),
        CheckDefinition(
            check_id="azure_monitor_log_retention_365",
            title="Activity log retention is at least 365 days",
            description="Activity log retention is at least 365 days.",
            severity="medium",
            provider="azure",
            service="monitor",
            category="Logging",
            tags=["monitor", "retention"],
        ),
        CheckDefinition(
            check_id="azure_network_security_perimeter",
            title="Network Security Perimeter is configured",
            description="Network Security Perimeter is configured.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="azure_network_watcher_enabled",
            title="Network Watcher is enabled in all regions",
            description="Network Watcher is enabled in all regions.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="azure_nsg_default_deny_inbound",
            title="NSG has default deny inbound rule",
            description="NSG has default deny inbound rule.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="azure_nsg_flow_logs_enabled",
            title="NSG flow logs are enabled",
            description="NSG flow logs are enabled.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="azure_nsg_flow_logs_retention",
            title="NSG flow logs have retention ≥ 90 days",
            description="NSG flow logs have retention ≥ 90 days.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "networking", "security-group", "retention"],
        ),
        CheckDefinition(
            check_id="azure_nsg_http_restricted",
            title="NSG restricts inbound HTTP (port 80)",
            description="NSG restricts inbound HTTP (port 80).",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="azure_nsg_udp_restricted",
            title="NSG restricts inbound UDP services",
            description="NSG restricts inbound UDP services.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="azure_pim_jit_access",
            title="Privileged roles use just-in-time access (PIM)",
            description="Privileged roles use just-in-time access (PIM).",
            severity="high",
            provider="azure",
            service="privilegedaccess",
            category="Compliance",
            tags=["privilegedaccess"],
        ),
        CheckDefinition(
            check_id="azure_policy_assignments_exist",
            title="Azure Policy assignments are configured",
            description="Azure Policy assignments are configured.",
            severity="medium",
            provider="azure",
            service="policy",
            category="Compliance",
            tags=["policy"],
        ),
        CheckDefinition(
            check_id="azure_policy_compliance_rate",
            title="Azure Policy compliance rate is above threshold",
            description="Azure Policy compliance rate is above threshold.",
            severity="medium",
            provider="azure",
            service="policy",
            category="Compliance",
            tags=["policy"],
        ),
        CheckDefinition(
            check_id="azure_policy_security_initiative",
            title="Azure Security Benchmark initiative is assigned",
            description="Azure Security Benchmark initiative is assigned.",
            severity="high",
            provider="azure",
            service="policy",
            category="Compliance",
            tags=["policy"],
        ),
        CheckDefinition(
            check_id="azure_postgresql_public_access",
            title="PostgreSQL server has public access restricted",
            description="PostgreSQL server has public access restricted.",
            severity="high",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database", "public-access"],
        ),
        CheckDefinition(
            check_id="azure_private_endpoints_used",
            title="Private endpoints are configured for services",
            description="Private endpoints are configured for services.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="azure_public_ip_ddos_protection",
            title="Public IP has DDoS protection",
            description="Public IP has DDoS protection.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "public-access"],
        ),
        CheckDefinition(
            check_id="azure_public_ip_review",
            title="Public IP addresses are reviewed and necessary",
            description="Public IP addresses are reviewed and necessary.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "public-access"],
        ),
        CheckDefinition(
            check_id="azure_resource_locks_configured",
            title="Resource locks are configured for critical resources",
            description="Resource locks are configured for critical resources.",
            severity="medium",
            provider="azure",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="azure_security_alert_notifications",
            title="Security alert email notifications are enabled",
            description="Security alert email notifications are enabled.",
            severity="medium",
            provider="azure",
            service="defender",
            category="Threat Detection",
            tags=["defender"],
        ),
        CheckDefinition(
            check_id="azure_security_contact_configured",
            title="Security contact email is configured",
            description="Security contact email is configured.",
            severity="medium",
            provider="azure",
            service="defender",
            category="Threat Detection",
            tags=["defender"],
        ),
        CheckDefinition(
            check_id="azure_sentinel_automation_rules",
            title="Microsoft Sentinel has automation rules configured",
            description="Microsoft Sentinel has automation rules configured.",
            severity="high",
            provider="azure",
            service="incidentresponse",
            category="Compliance",
            tags=["incidentresponse"],
        ),
        CheckDefinition(
            check_id="azure_sql_ad_admin_configured",
            title="SQL Server has Azure AD administrator configured",
            description="SQL Server has Azure AD administrator configured.",
            severity="high",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database"],
        ),
        CheckDefinition(
            check_id="azure_sql_atp_enabled",
            title="SQL Server has Advanced Threat Protection enabled",
            description="SQL Server has Advanced Threat Protection enabled.",
            severity="high",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database"],
        ),
        CheckDefinition(
            check_id="azure_sql_auditing_enabled",
            title="SQL Server has auditing enabled",
            description="SQL Server has auditing enabled.",
            severity="high",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database", "audit"],
        ),
        CheckDefinition(
            check_id="azure_sql_public_access_disabled",
            title="SQL Server public network access is disabled",
            description="SQL Server public network access is disabled.",
            severity="high",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database", "public-access"],
        ),
        CheckDefinition(
            check_id="azure_sql_tde_enabled",
            title="SQL Database has TDE enabled",
            description="SQL Database has TDE enabled.",
            severity="high",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database"],
        ),
        CheckDefinition(
            check_id="azure_sql_tls_12",
            title="SQL Server requires TLS 1.2",
            description="SQL Server requires TLS 1.2.",
            severity="high",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="azure_sql_vulnerability_assessment",
            title="SQL Server has Vulnerability Assessment configured",
            description="SQL Server has Vulnerability Assessment configured.",
            severity="medium",
            provider="azure",
            service="database",
            category="Compliance",
            tags=["database"],
        ),
        CheckDefinition(
            check_id="azure_storage_cmk_encryption",
            title="Storage account uses customer-managed keys",
            description="Storage account uses customer-managed keys.",
            severity="medium",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="azure_storage_https_only",
            title="Storage account requires HTTPS",
            description="Storage account requires HTTPS.",
            severity="high",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="azure_storage_infrastructure_encryption",
            title="Storage account has infrastructure encryption enabled",
            description="Storage account has infrastructure encryption enabled.",
            severity="medium",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="azure_storage_key_rotation",
            title="Storage account keys are rotated within 90 days",
            description="Storage account keys are rotated within 90 days.",
            severity="medium",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "rotation"],
        ),
        CheckDefinition(
            check_id="azure_storage_network_default_deny",
            title="Storage account has network rules with default deny",
            description="Storage account has network rules with default deny.",
            severity="high",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        CheckDefinition(
            check_id="azure_storage_no_public_access",
            title="Storage account blocks public blob access",
            description="Storage account blocks public blob access.",
            severity="high",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "public-access"],
        ),
        CheckDefinition(
            check_id="azure_storage_shared_key_disabled",
            title="Storage account has shared key access disabled",
            description="Storage account has shared key access disabled.",
            severity="medium",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        CheckDefinition(
            check_id="azure_storage_soft_delete_blobs",
            title="Storage blob soft delete is enabled",
            description="Storage blob soft delete is enabled.",
            severity="medium",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="azure_storage_soft_delete_files",
            title="Storage file share soft delete is enabled",
            description="Storage file share soft delete is enabled.",
            severity="medium",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "deletion-protection"],
        ),
        CheckDefinition(
            check_id="azure_storage_tls_12",
            title="Storage account uses TLS 1.2",
            description="Storage account uses TLS 1.2.",
            severity="high",
            provider="azure",
            service="storage",
            category="Storage",
            tags=["storage", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="azure_subnet_has_nsg",
            title="Subnet has an associated NSG",
            description="Subnet has an associated NSG.",
            severity="high",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="azure_subscription_transfer_restricted",
            title="Subscription transfers are restricted via policy",
            description="Subscription transfers are restricted via policy.",
            severity="medium",
            provider="azure",
            service="policy",
            category="Compliance",
            tags=["policy"],
        ),
        CheckDefinition(
            check_id="azure_vm_antimalware_extension",
            title="VM has antimalware extension installed",
            description="VM has antimalware extension installed.",
            severity="high",
            provider="azure",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="azure_vm_auto_updates",
            title="VM has automatic OS updates enabled",
            description="VM has automatic OS updates enabled.",
            severity="medium",
            provider="azure",
            service="endpoint",
            category="Compliance",
            tags=["endpoint"],
        ),
        CheckDefinition(
            check_id="azure_vm_disk_encryption",
            title="VM has disk encryption enabled",
            description="VM has disk encryption enabled.",
            severity="high",
            provider="azure",
            service="compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="azure_vm_managed_disks",
            title="VM uses managed disks",
            description="VM uses managed disks.",
            severity="medium",
            provider="azure",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="azure_vm_no_public_ip",
            title="VM does not have direct public IP assignment",
            description="VM does not have direct public IP assignment.",
            severity="medium",
            provider="azure",
            service="compute",
            category="Compute",
            tags=["compute", "public-access"],
        ),
        CheckDefinition(
            check_id="azure_vm_trusted_launch",
            title="VM uses Trusted Launch",
            description="VM uses Trusted Launch.",
            severity="medium",
            provider="azure",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="azure_vm_vulnerability_assessment",
            title="VM has vulnerability assessment solution installed",
            description="VM has vulnerability assessment solution installed.",
            severity="high",
            provider="azure",
            service="endpoint",
            category="Compliance",
            tags=["endpoint"],
        ),
        CheckDefinition(
            check_id="azure_vnet_flow_logs_retention",
            title="VNet flow logs have retention ≥ 90 days",
            description="VNet flow logs have retention ≥ 90 days.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "retention"],
        ),
        CheckDefinition(
            check_id="azure_vpn_gateway_aad_auth",
            title="VPN Gateway uses Azure AD authentication",
            description="VPN Gateway uses Azure AD authentication.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="azure_waf_body_inspection",
            title="WAF request body inspection is enabled",
            description="WAF request body inspection is enabled.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "waf"],
        ),
        CheckDefinition(
            check_id="azure_waf_bot_protection",
            title="WAF has bot protection rule set enabled",
            description="WAF has bot protection rule set enabled.",
            severity="medium",
            provider="azure",
            service="network",
            category="Networking",
            tags=["network", "waf"],
        ),
        # --- Supplementary: MITRE/RR orphan resolution ---
        CheckDefinition(
            check_id="azure_nsg_open_port_22",
            title="NSG allows unrestricted SSH access (port 22)",
            description="NSG allows unrestricted SSH access (port 22).",
            severity="high",
            provider="azure",
            service="Network",
            category="Networking",
            scanner_check_ids=["azure_nsg_open_port_22"],
            source="scanner",
            tags=["nsg", "networking", "ssh"],
        ),
        CheckDefinition(
            check_id="azure_nsg_open_port_3389",
            title="NSG allows unrestricted RDP access (port 3389)",
            description="NSG allows unrestricted RDP access (port 3389).",
            severity="high",
            provider="azure",
            service="Network",
            category="Networking",
            scanner_check_ids=["azure_nsg_open_port_3389"],
            source="scanner",
            tags=["nsg", "networking", "rdp"],
        ),
        CheckDefinition(
            check_id="sentinel_enabled",
            title="Azure Sentinel SIEM is enabled",
            description="Azure Sentinel SIEM is enabled.",
            severity="high",
            provider="azure",
            service="Sentinel",
            category="Threat Detection",
            scanner_check_ids=["sentinel_enabled"],
            rr_relevant=True,
            rr_domains=["D6"],
            source="scanner",
            tags=["sentinel", "siem", "logging"],
        ),
    ]
