"""Check definitions for Cloudflare.

Auto-generated from cloudflare scanner. 25 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Cloudflare check definitions."""
    return [
        CheckDefinition(
            check_id="cloudflare_ac_2fa_enabled",
            title="Two-factor authentication is enabled on Cloudflare account",
            description="Two-factor authentication is enabled on Cloudflare account.",
            severity="critical",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_access_policies",
            title="Cloudflare Access policies are configured",
            description="Cloudflare Access policies are configured.",
            severity="medium",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_admin_members",
            title="Account administrator count is reviewed",
            description="Account administrator count is reviewed.",
            severity="high",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_api_token_valid",
            title="API token is valid and active",
            description="API token is valid and active.",
            severity="high",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_zero_trust_gateway",
            title="Zero Trust Gateway policies are configured",
            description="Zero Trust Gateway policies are configured.",
            severity="medium",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_caa_configured",
            title="CAA records are configured to restrict certificate issuance",
            description="CAA records are configured to restrict certificate issuance.",
            severity="medium",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_dangling_review",
            title="DNS records are reviewed for dangling entries",
            description="DNS records are reviewed for dangling entries.",
            severity="high",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_dnssec_enabled",
            title="DNSSEC is enabled for the zone",
            description="DNSSEC is enabled for the zone.",
            severity="high",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_zone_transfer_restricted",
            title="DNS zone is using Cloudflare nameservers (full setup)",
            description="DNS zone is using Cloudflare nameservers (full setup).",
            severity="medium",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_early_hints",
            title="Early Hints (103) is enabled",
            description="Early Hints (103) is enabled.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_http2_enabled",
            title="HTTP/2 is enabled",
            description="HTTP/2 is enabled.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_http3_enabled",
            title="HTTP/3 (QUIC) is enabled",
            description="HTTP/3 (QUIC) is enabled.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_origin_protection",
            title="Authenticated Origin Pulls is enabled",
            description="Authenticated Origin Pulls is enabled.",
            severity="high",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_page_rules_secure",
            title="Page rules do not disable security features",
            description="Page rules do not disable security features.",
            severity="high",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_always_https",
            title="Always Use HTTPS is enabled",
            description="Always Use HTTPS is enabled.",
            severity="high",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_auto_https_rewrites",
            title="Automatic HTTPS Rewrites are enabled",
            description="Automatic HTTPS Rewrites are enabled.",
            severity="medium",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_full_strict",
            title="SSL mode is set to Full (Strict)",
            description="SSL mode is set to Full (Strict).",
            severity="critical",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_hsts_enabled",
            title="HTTP Strict Transport Security (HSTS) is enabled",
            description="HTTP Strict Transport Security (HSTS) is enabled.",
            severity="high",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_min_version",
            title="Minimum TLS version is 1.2 or higher",
            description="Minimum TLS version is 1.2 or higher.",
            severity="high",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_bot_management",
            title="Security level is set to medium or higher",
            description="Security level is set to medium or higher.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_browser_check",
            title="Browser Integrity Check is enabled",
            description="Browser Integrity Check is enabled.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_ddos_challenge_ttl",
            title="Challenge TTL is appropriately configured",
            description="Challenge TTL is appropriately configured.",
            severity="low",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_firewall_rules",
            title="Custom firewall rules are configured",
            description="Custom firewall rules are configured.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_managed_rules",
            title="WAF managed rules are enabled",
            description="WAF managed rules are enabled.",
            severity="high",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_rate_limiting",
            title="Rate limiting rules are configured",
            description="Rate limiting rules are configured.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
    ]
