"""Check definitions for Cloudflare.

Auto-generated from cloudflare scanner. 55 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Cloudflare check definitions."""
    return [
        CheckDefinition(
            check_id="cloudflare_ac_2fa_enabled",
            title="Two-factor authentication is enabled on Cloudflare account",
            description="Two-factor authentication is enabled on Cloudflare account.",
            severity="critical",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_access_policies",
            title="Cloudflare Access policies are configured",
            description="Cloudflare Access policies are configured.",
            severity="medium",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_admin_members",
            title="Account administrator count is reviewed",
            description="Account administrator count is reviewed.",
            severity="high",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_api_token_valid",
            title="API token is valid and active",
            description="API token is valid and active.",
            severity="high",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_zero_trust_gateway",
            title="Zero Trust Gateway policies are configured",
            description="Zero Trust Gateway policies are configured.",
            severity="medium",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_caa_configured",
            title="CAA records are configured to restrict certificate issuance",
            description="CAA records are configured to restrict certificate issuance.",
            severity="medium",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_dangling_review",
            title="DNS records are reviewed for dangling entries",
            description="DNS records are reviewed for dangling entries.",
            severity="high",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_dnssec_enabled",
            title="DNSSEC is enabled for the zone",
            description="DNSSEC is enabled for the zone.",
            severity="high",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_zone_transfer_restricted",
            title="DNS zone is using Cloudflare nameservers (full setup)",
            description="DNS zone is using Cloudflare nameservers (full setup).",
            severity="medium",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_early_hints",
            title="Early Hints (103) is enabled",
            description="Early Hints (103) is enabled.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_http2_enabled",
            title="HTTP/2 is enabled",
            description="HTTP/2 is enabled.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_http3_enabled",
            title="HTTP/3 (QUIC) is enabled",
            description="HTTP/3 (QUIC) is enabled.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_origin_protection",
            title="Authenticated Origin Pulls is enabled",
            description="Authenticated Origin Pulls is enabled.",
            severity="high",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_page_rules_secure",
            title="Page rules do not disable security features",
            description="Page rules do not disable security features.",
            severity="high",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_always_https",
            title="Always Use HTTPS is enabled",
            description="Always Use HTTPS is enabled.",
            severity="high",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_auto_https_rewrites",
            title="Automatic HTTPS Rewrites are enabled",
            description="Automatic HTTPS Rewrites are enabled.",
            severity="medium",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_full_strict",
            title="SSL mode is set to Full (Strict)",
            description="SSL mode is set to Full (Strict).",
            severity="critical",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_hsts_enabled",
            title="HTTP Strict Transport Security (HSTS) is enabled",
            description="HTTP Strict Transport Security (HSTS) is enabled.",
            severity="high",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_min_version",
            title="Minimum TLS version is 1.2 or higher",
            description="Minimum TLS version is 1.2 or higher.",
            severity="high",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_bot_management",
            title="Security level is set to medium or higher",
            description="Security level is set to medium or higher.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_browser_check",
            title="Browser Integrity Check is enabled",
            description="Browser Integrity Check is enabled.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_ddos_challenge_ttl",
            title="Challenge TTL is appropriately configured",
            description="Challenge TTL is appropriately configured.",
            severity="low",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_firewall_rules",
            title="Custom firewall rules are configured",
            description="Custom firewall rules are configured.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_managed_rules",
            title="WAF managed rules are enabled",
            description="WAF managed rules are enabled.",
            severity="high",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_rate_limiting",
            title="Rate limiting rules are configured",
            description="Rate limiting rules are configured.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        # --- New checks below ---
        CheckDefinition(
            check_id="cloudflare_ac_api_token_scoped",
            title="API tokens are scoped to minimum required permissions",
            description="API tokens are scoped to minimum required permissions.",
            severity="high",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control", "api"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_api_token_rotation",
            title="API tokens are rotated within 90 days",
            description="API tokens are rotated within 90 days.",
            severity="medium",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control", "api", "rotation"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_sso_configured",
            title="SSO is configured for Cloudflare dashboard access",
            description="SSO is configured for Cloudflare dashboard access.",
            severity="high",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control", "sso"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_account_audit_log",
            title="Account audit log is enabled and reviewed",
            description="Account audit log is enabled and reviewed.",
            severity="high",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control", "audit"],
        ),
        CheckDefinition(
            check_id="cloudflare_ac_member_roles_reviewed",
            title="Account member roles follow least privilege principle",
            description="Account member roles follow least privilege principle.",
            severity="medium",
            provider="cloudflare",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_cname_flattening",
            title="CNAME flattening is configured for root domain",
            description="CNAME flattening is configured for root domain.",
            severity="low",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_mx_records_valid",
            title="MX records are valid and point to authorized mail servers",
            description="MX records are valid and point to authorized mail servers.",
            severity="medium",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security", "email"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_proxy_enabled",
            title="DNS records are proxied through Cloudflare where appropriate",
            description="DNS records are proxied through Cloudflare where appropriate.",
            severity="medium",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_dns_wildcard_reviewed",
            title="Wildcard DNS records are reviewed and justified",
            description="Wildcard DNS records are reviewed and justified.",
            severity="medium",
            provider="cloudflare",
            service="dns_security",
            category="Networking",
            tags=["dns_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_certificate_pinning",
            title="Certificate pinning is configured for high-security origins",
            description="Certificate pinning is configured for high-security origins.",
            severity="medium",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_opportunistic_encryption",
            title="Opportunistic Encryption is enabled",
            description="Opportunistic Encryption is enabled.",
            severity="low",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_tls_1_3_enabled",
            title="TLS 1.3 is enabled for improved security",
            description="TLS 1.3 is enabled for improved security.",
            severity="medium",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_certificate_transparency",
            title="Certificate Transparency Monitoring is enabled",
            description="Certificate Transparency Monitoring is enabled.",
            severity="medium",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_tls_origin_certificate",
            title="Cloudflare Origin Certificate is used for origin connections",
            description="Cloudflare Origin Certificate is used for origin connections.",
            severity="high",
            provider="cloudflare",
            service="ssl_tls",
            category="Compliance",
            tags=["ssl_tls", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_owasp_rules",
            title="OWASP Core Ruleset is enabled in WAF",
            description="OWASP Core Ruleset is enabled in WAF.",
            severity="high",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf", "owasp"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_ip_access_rules",
            title="IP access rules are configured for known threat sources",
            description="IP access rules are configured for known threat sources.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_user_agent_blocking",
            title="Malicious user agent blocking rules are configured",
            description="Malicious user agent blocking rules are configured.",
            severity="medium",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_zone_lockdown",
            title="Zone Lockdown is configured for sensitive endpoints",
            description="Zone Lockdown is configured for sensitive endpoints.",
            severity="high",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_waf_hotlink_protection",
            title="Hotlink Protection is enabled to prevent resource theft",
            description="Hotlink Protection is enabled to prevent resource theft.",
            severity="low",
            provider="cloudflare",
            service="waf_security",
            category="Networking",
            tags=["waf_security", "waf"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_minification",
            title="Auto Minification is configured for CSS/JS/HTML",
            description="Auto Minification is configured for CSS/JS/HTML.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_brotli_compression",
            title="Brotli compression is enabled",
            description="Brotli compression is enabled.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_rocket_loader",
            title="Rocket Loader is reviewed for compatibility",
            description="Rocket Loader is reviewed for compatibility.",
            severity="low",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_perf_cache_level",
            title="Cache level is configured appropriately for security",
            description="Cache level is configured appropriately for security.",
            severity="medium",
            provider="cloudflare",
            service="performance_security",
            category="Compliance",
            tags=["performance_security"],
        ),
        CheckDefinition(
            check_id="cloudflare_zt_access_app_configured",
            title="Zero Trust Access applications are configured for internal services",
            description="Zero Trust Access applications are configured for internal services.",
            severity="high",
            provider="cloudflare",
            service="zero_trust",
            category="Compliance",
            tags=["zero_trust"],
        ),
        CheckDefinition(
            check_id="cloudflare_zt_tunnel_configured",
            title="Cloudflare Tunnel is configured for secure origin connectivity",
            description="Cloudflare Tunnel is configured for secure origin connectivity.",
            severity="high",
            provider="cloudflare",
            service="zero_trust",
            category="Compliance",
            tags=["zero_trust"],
        ),
        CheckDefinition(
            check_id="cloudflare_zt_device_posture",
            title="Device posture checks are configured for Zero Trust access",
            description="Device posture checks are configured for Zero Trust access.",
            severity="high",
            provider="cloudflare",
            service="zero_trust",
            category="Compliance",
            tags=["zero_trust", "device-posture"],
        ),
        CheckDefinition(
            check_id="cloudflare_zt_browser_isolation",
            title="Browser Isolation is enabled for high-risk destinations",
            description="Browser Isolation is enabled for high-risk destinations.",
            severity="medium",
            provider="cloudflare",
            service="zero_trust",
            category="Compliance",
            tags=["zero_trust"],
        ),
        CheckDefinition(
            check_id="cloudflare_zt_dlp_configured",
            title="Data Loss Prevention policies are configured",
            description="Data Loss Prevention policies are configured.",
            severity="high",
            provider="cloudflare",
            service="zero_trust",
            category="Compliance",
            tags=["zero_trust", "dlp"],
        ),
        CheckDefinition(
            check_id="cloudflare_zt_casb_configured",
            title="Cloud Access Security Broker (CASB) integration is configured",
            description="Cloud Access Security Broker (CASB) integration is configured.",
            severity="medium",
            provider="cloudflare",
            service="zero_trust",
            category="Compliance",
            tags=["zero_trust", "casb"],
        ),
        CheckDefinition(
            check_id="cloudflare_zt_email_security",
            title="Email Security (Area 1) is configured for phishing protection",
            description="Email Security (Area 1) is configured for phishing protection.",
            severity="medium",
            provider="cloudflare",
            service="zero_trust",
            category="Compliance",
            tags=["zero_trust", "email"],
        ),
    ]
