"""Check definitions for GCP.

Auto-generated from gcp scanner. 150 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all GCP check definitions."""
    return [
        CheckDefinition(
            check_id="gcp_bigquery_audit_logging",
            title="BigQuery audit logging is enabled",
            description="BigQuery audit logging is enabled.",
            severity="medium",
            provider="gcp",
            service="bigquery",
            category="Compliance",
            tags=["bigquery", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="gcp_bigquery_classification",
            title="BigQuery dataset has data classification labels",
            description="BigQuery dataset has data classification labels.",
            severity="low",
            provider="gcp",
            service="bigquery",
            category="Compliance",
            tags=["bigquery"],
        ),
        CheckDefinition(
            check_id="gcp_bigquery_cmek_encryption",
            title="BigQuery dataset uses CMEK encryption",
            description="BigQuery dataset uses CMEK encryption.",
            severity="medium",
            provider="gcp",
            service="bigquery",
            category="Compliance",
            tags=["bigquery", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_bigquery_dataset_no_public",
            title="BigQuery dataset is not publicly accessible",
            description="BigQuery dataset is not publicly accessible.",
            severity="critical",
            provider="gcp",
            service="bigquery",
            category="Compliance",
            tags=["bigquery", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_bigquery_table_encrypted",
            title="BigQuery table is encrypted with CMEK",
            description="BigQuery table is encrypted with CMEK.",
            severity="medium",
            provider="gcp",
            service="bigquery",
            category="Compliance",
            tags=["bigquery", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_binary_auth",
            title="Cloud Run service has Binary Authorization enabled",
            description="Cloud Run service has Binary Authorization enabled.",
            severity="medium",
            provider="gcp",
            service="cloudrun",
            category="Compliance",
            tags=["cloudrun"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_cmek",
            title="Cloud Run service uses customer-managed encryption key",
            description="Cloud Run service uses customer-managed encryption key.",
            severity="medium",
            provider="gcp",
            service="cloudrun",
            category="Compliance",
            tags=["cloudrun"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_custom_sa",
            title="Cloud Run service uses a custom service account",
            description="Cloud Run service uses a custom service account.",
            severity="high",
            provider="gcp",
            service="cloudrun",
            category="Compliance",
            tags=["cloudrun"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_ingress_restricted",
            title="Cloud Run service restricts ingress traffic",
            description="Cloud Run service restricts ingress traffic.",
            severity="high",
            provider="gcp",
            service="cloudrun",
            category="Compliance",
            tags=["cloudrun"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_no_public_access",
            title="Cloud Run service does not allow unauthenticated access",
            description="Cloud Run service does not allow unauthenticated access.",
            severity="high",
            provider="gcp",
            service="cloudrun",
            category="Compliance",
            tags=["cloudrun", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_no_secret_envvars",
            title="Cloud Run container does not store secrets in plaintext env vars",
            description="Cloud Run container does not store secrets in plaintext env vars.",
            severity="critical",
            provider="gcp",
            service="cloudrun",
            category="Compliance",
            tags=["cloudrun"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_vpc_egress",
            title="Cloud Run service routes egress through VPC",
            description="Cloud Run service routes egress through VPC.",
            severity="medium",
            provider="gcp",
            service="cloudrun",
            category="Compliance",
            tags=["cloudrun", "networking"],
        ),
        CheckDefinition(
            check_id="gcp_compute_block_project_ssh",
            title="VM instance blocks project-wide SSH keys",
            description="VM instance blocks project-wide SSH keys.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute", "ssh"],
        ),
        CheckDefinition(
            check_id="gcp_compute_confidential_computing",
            title="VM instance has Confidential Computing enabled",
            description="VM instance has Confidential Computing enabled.",
            severity="low",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_compute_disk_encryption_cmek",
            title="VM disks are encrypted with customer-managed keys (CMEK)",
            description="VM disks are encrypted with customer-managed keys (CMEK).",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_compute_ip_forwarding_disabled",
            title="VM instance has IP forwarding disabled",
            description="VM instance has IP forwarding disabled.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_compute_no_default_sa",
            title="VM instance does not use default Compute Engine service account",
            description="VM instance does not use default Compute Engine service account.",
            severity="high",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_compute_no_external_ip",
            title="VM instance has no external IP",
            description="VM instance has no external IP.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_compute_no_full_api_access",
            title="VM instance does not use full API access scope",
            description="VM instance does not use full API access scope.",
            severity="high",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_compute_os_login",
            title="VM instance has OS Login enabled",
            description="VM instance has OS Login enabled.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_compute_serial_port_disabled",
            title="VM instance has serial port access disabled",
            description="VM instance has serial port access disabled.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_compute_shielded_vm",
            title="VM instance uses Shielded VM features",
            description="VM instance uses Shielded VM features.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="gcp_dataproc_encrypted",
            title="Dataproc cluster is encrypted with CMEK",
            description="Dataproc cluster is encrypted with CMEK.",
            severity="medium",
            provider="gcp",
            service="dataproc",
            category="Compliance",
            tags=["dataproc", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_dataproc_private",
            title="Dataproc cluster uses internal IP only",
            description="Dataproc cluster uses internal IP only.",
            severity="high",
            provider="gcp",
            service="dataproc",
            category="Compliance",
            tags=["dataproc"],
        ),
        CheckDefinition(
            check_id="gcp_dns_dnssec_enabled",
            title="Cloud DNS managed zone has DNSSEC enabled",
            description="Cloud DNS managed zone has DNSSEC enabled.",
            severity="medium",
            provider="gcp",
            service="dns",
            category="Networking",
            tags=["dns"],
        ),
        CheckDefinition(
            check_id="gcp_dns_rsasha1_disabled",
            title="Cloud DNS DNSSEC does not use RSASHA1",
            description="Cloud DNS DNSSEC does not use RSASHA1.",
            severity="high",
            provider="gcp",
            service="dns",
            category="Networking",
            tags=["dns"],
        ),
        CheckDefinition(
            check_id="gcp_firewall_no_default_allow",
            title="Default allow firewall rules are removed",
            description="Default allow firewall rules are removed.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="gcp_function_custom_sa",
            title="Cloud Function uses a custom service account",
            description="Cloud Function uses a custom service account.",
            severity="high",
            provider="gcp",
            service="cloudfunctions",
            category="Serverless",
            tags=["cloudfunctions"],
        ),
        CheckDefinition(
            check_id="gcp_function_ingress_restricted",
            title="Cloud Function restricts ingress traffic",
            description="Cloud Function restricts ingress traffic.",
            severity="high",
            provider="gcp",
            service="cloudfunctions",
            category="Serverless",
            tags=["cloudfunctions"],
        ),
        CheckDefinition(
            check_id="gcp_function_max_instances",
            title="Cloud Function has max instances limit configured",
            description="Cloud Function has max instances limit configured.",
            severity="low",
            provider="gcp",
            service="cloudfunctions",
            category="Serverless",
            tags=["cloudfunctions"],
        ),
        CheckDefinition(
            check_id="gcp_function_no_secret_envvars",
            title="Cloud Function does not store secrets in plaintext env vars",
            description="Cloud Function does not store secrets in plaintext env vars.",
            severity="critical",
            provider="gcp",
            service="cloudfunctions",
            category="Serverless",
            tags=["cloudfunctions"],
        ),
        CheckDefinition(
            check_id="gcp_function_runtime_supported",
            title="Cloud Function uses a supported runtime version",
            description="Cloud Function uses a supported runtime version.",
            severity="medium",
            provider="gcp",
            service="cloudfunctions",
            category="Serverless",
            tags=["cloudfunctions"],
        ),
        CheckDefinition(
            check_id="gcp_function_vpc_connector",
            title="Cloud Function uses a VPC connector",
            description="Cloud Function uses a VPC connector.",
            severity="medium",
            provider="gcp",
            service="cloudfunctions",
            category="Serverless",
            tags=["cloudfunctions", "networking"],
        ),
        CheckDefinition(
            check_id="gcp_gke_binary_auth",
            title="GKE cluster has Binary Authorization enabled",
            description="GKE cluster has Binary Authorization enabled.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke"],
        ),
        CheckDefinition(
            check_id="gcp_gke_cluster_logging",
            title="GKE cluster has logging enabled",
            description="GKE cluster has logging enabled.",
            severity="high",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "logging"],
        ),
        CheckDefinition(
            check_id="gcp_gke_master_auth_networks",
            title="GKE cluster has master authorized networks enabled",
            description="GKE cluster has master authorized networks enabled.",
            severity="high",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke"],
        ),
        CheckDefinition(
            check_id="gcp_gke_network_policy",
            title="GKE cluster has network policy enabled",
            description="GKE cluster has network policy enabled.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke"],
        ),
        CheckDefinition(
            check_id="gcp_gke_pod_security_policy",
            title="GKE cluster has Pod Security Policy / Standards enabled",
            description="GKE cluster has Pod Security Policy / Standards enabled.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke"],
        ),
        CheckDefinition(
            check_id="gcp_gke_private_cluster",
            title="GKE cluster uses private nodes",
            description="GKE cluster uses private nodes.",
            severity="high",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke"],
        ),
        CheckDefinition(
            check_id="gcp_gke_shielded_nodes",
            title="GKE cluster has Shielded GKE Nodes enabled",
            description="GKE cluster has Shielded GKE Nodes enabled.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke"],
        ),
        CheckDefinition(
            check_id="gcp_gke_workload_identity",
            title="GKE cluster has Workload Identity enabled",
            description="GKE cluster has Workload Identity enabled.",
            severity="high",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke"],
        ),
        CheckDefinition(
            check_id="gcp_iam_api_keys_exist",
            title="API keys are not used (prefer OAuth or service accounts)",
            description="API keys are not used (prefer OAuth or service accounts).",
            severity="low",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_api_keys_restricted",
            title="API keys have application restrictions",
            description="API keys have application restrictions.",
            severity="medium",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_api_keys_rotated",
            title="API keys are rotated within 90 days",
            description="API keys are rotated within 90 days.",
            severity="medium",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_corp_login_required",
            title="Corporate login identities are used",
            description="Corporate login identities are used.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_essential_contacts",
            title="Essential Contacts are configured for the project",
            description="Essential Contacts are configured for the project.",
            severity="medium",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_kms_separation_of_duties",
            title="KMS admin and CryptoKey Encrypter/Decrypter roles are separated",
            description="KMS admin and CryptoKey Encrypter/Decrypter roles are separated.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "kms"],
        ),
        CheckDefinition(
            check_id="gcp_iam_no_primitive_roles",
            title="IAM policy does not use primitive roles for users",
            description="IAM policy does not use primitive roles for users.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_no_public_access",
            title="IAM policy does not grant public access",
            description="IAM policy does not grant public access.",
            severity="critical",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_iam_no_sa_admin_key",
            title="Service accounts with admin privileges do not have user-managed keys",
            description="Service accounts with admin privileges do not have user-managed keys.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_no_user_managed_sa_keys",
            title="Service accounts do not have user-managed keys",
            description="Service accounts do not have user-managed keys.",
            severity="medium",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_sa_key_rotation",
            title="Service account keys are rotated within 90 days",
            description="Service account keys are rotated within 90 days.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="gcp_iam_sa_token_creator_role",
            title="Service Account Token Creator role is not assigned at project level",
            description="Service Account Token Creator role is not assigned at project level.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_sa_user_role",
            title="Service Account User role is not assigned at project level",
            description="Service Account User role is not assigned at project level.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_secrets_in_functions",
            title="Cloud Functions do not contain secrets in environment variables",
            description="Cloud Functions do not contain secrets in environment variables.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_iam_separation_of_duties",
            title="Separation of duties enforced for service account admin",
            description="Separation of duties enforced for service account admin.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="gcp_kms_hsm_protection",
            title="KMS key uses HSM protection level",
            description="KMS key uses HSM protection level.",
            severity="low",
            provider="gcp",
            service="kms",
            category="Encryption",
            tags=["kms"],
        ),
        CheckDefinition(
            check_id="gcp_kms_key_rotation",
            title="KMS key has rotation period of 90 days or less",
            description="KMS key has rotation period of 90 days or less.",
            severity="medium",
            provider="gcp",
            service="kms",
            category="Encryption",
            tags=["kms", "rotation"],
        ),
        CheckDefinition(
            check_id="gcp_kms_no_public_access",
            title="KMS key is not publicly accessible",
            description="KMS key is not publicly accessible.",
            severity="critical",
            provider="gcp",
            service="kms",
            category="Encryption",
            tags=["kms", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_logging_audit_config_changes",
            title="Log metric filter exists for audit configuration changes",
            description="Log metric filter exists for audit configuration changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "audit"],
        ),
        CheckDefinition(
            check_id="gcp_logging_audit_logs_enabled",
            title="Data Access audit logs are enabled for all services",
            description="Data Access audit logs are enabled for all services.",
            severity="high",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "audit"],
        ),
        CheckDefinition(
            check_id="gcp_logging_bucket_retention",
            title="Log buckets have retention of 365 days or more",
            description="Log buckets have retention of 365 days or more.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "retention"],
        ),
        CheckDefinition(
            check_id="gcp_logging_cloud_asset_inventory",
            title="Cloud Asset Inventory is enabled",
            description="Cloud Asset Inventory is enabled.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_custom_role_changes",
            title="Log metric filter exists for custom role changes",
            description="Log metric filter exists for custom role changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_dns_logging",
            title="Cloud DNS logging is enabled",
            description="Cloud DNS logging is enabled.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_firewall_changes",
            title="Log metric filter exists for VPC firewall rule changes",
            description="Log metric filter exists for VPC firewall rule changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_lb_logging",
            title="Load balancer logging is enabled",
            description="Load balancer logging is enabled.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_metric_filters",
            title="Log metric filters exist for critical operations",
            description="Log metric filters exist for critical operations.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_ownership_changes",
            title="Log metric filter exists for project ownership changes",
            description="Log metric filter exists for project ownership changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_route_changes",
            title="Log metric filter exists for VPC network route changes",
            description="Log metric filter exists for VPC network route changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_sinks_configured",
            title="Log sinks are configured",
            description="Log sinks are configured.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_sql_config_changes",
            title="Log metric filter exists for SQL instance configuration changes",
            description="Log metric filter exists for SQL instance configuration changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="gcp_logging_storage_iam_changes",
            title="Log metric filter exists for Cloud Storage IAM permission changes",
            description="Log metric filter exists for Cloud Storage IAM permission changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "iam"],
        ),
        CheckDefinition(
            check_id="gcp_logging_vpc_changes",
            title="Log metric filter exists for VPC network changes",
            description="Log metric filter exists for VPC network changes.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "networking"],
        ),
        CheckDefinition(
            check_id="gcp_logging_vpc_flow_logs",
            title="VPC subnet has flow logs enabled",
            description="VPC subnet has flow logs enabled.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "networking"],
        ),
        CheckDefinition(
            check_id="gcp_network_dns_sec",
            title="Cloud DNS zone has DNSSEC enabled",
            description="Cloud DNS zone has DNSSEC enabled.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="gcp_network_flow_logs_enabled",
            title="Subnet has VPC Flow Logs enabled",
            description="Subnet has VPC Flow Logs enabled.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="gcp_network_no_default_network",
            title="Default network does not exist in the project",
            description="Default network does not exist in the project.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="gcp_network_no_legacy_network",
            title="No legacy networks exist in the project",
            description="No legacy networks exist in the project.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="gcp_network_private_google_access",
            title="Subnet has Private Google Access enabled",
            description="Subnet has Private Google Access enabled.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="gcp_network_ssl_policy",
            title="SSL policy uses TLS 1.2 or higher",
            description="SSL policy uses TLS 1.2 or higher.",
            severity="high",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="gcp_pubsub_encrypted",
            title="Pub/Sub topic is encrypted with CMEK",
            description="Pub/Sub topic is encrypted with CMEK.",
            severity="medium",
            provider="gcp",
            service="pubsub",
            category="Compliance",
            tags=["pubsub", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_pubsub_no_public_access",
            title="Pub/Sub topic is not publicly accessible",
            description="Pub/Sub topic is not publicly accessible.",
            severity="high",
            provider="gcp",
            service="pubsub",
            category="Compliance",
            tags=["pubsub", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_secret_cmek",
            title="Secret is encrypted with customer-managed key",
            description="Secret is encrypted with customer-managed key.",
            severity="medium",
            provider="gcp",
            service="secretmanager",
            category="Container",
            tags=["secretmanager"],
        ),
        CheckDefinition(
            check_id="gcp_secret_labeled",
            title="Secret has ownership labels",
            description="Secret has ownership labels.",
            severity="low",
            provider="gcp",
            service="secretmanager",
            category="Container",
            tags=["secretmanager"],
        ),
        CheckDefinition(
            check_id="gcp_secret_no_public_access",
            title="Secret is not accessible to allUsers or allAuthenticatedUsers",
            description="Secret is not accessible to allUsers or allAuthenticatedUsers.",
            severity="critical",
            provider="gcp",
            service="secretmanager",
            category="Container",
            tags=["secretmanager", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_secret_rotation",
            title="Secret has automatic rotation configured",
            description="Secret has automatic rotation configured.",
            severity="high",
            provider="gcp",
            service="secretmanager",
            category="Container",
            tags=["secretmanager", "rotation"],
        ),
        CheckDefinition(
            check_id="gcp_secret_version_cleanup",
            title="Secret does not have excessive enabled versions",
            description="Secret does not have excessive enabled versions.",
            severity="low",
            provider="gcp",
            service="secretmanager",
            category="Container",
            tags=["secretmanager"],
        ),
        CheckDefinition(
            check_id="gcp_sql_audit_logging",
            title="Cloud SQL instance has database audit logging enabled",
            description="Cloud SQL instance has database audit logging enabled.",
            severity="medium",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="gcp_sql_auto_storage_increase",
            title="Cloud SQL instance has automatic storage increase enabled",
            description="Cloud SQL instance has automatic storage increase enabled.",
            severity="low",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql"],
        ),
        CheckDefinition(
            check_id="gcp_sql_backup_enabled",
            title="Cloud SQL instance has backups enabled",
            description="Cloud SQL instance has backups enabled.",
            severity="medium",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "backup"],
        ),
        CheckDefinition(
            check_id="gcp_sql_cmek_encryption",
            title="Cloud SQL instance is encrypted with CMEK",
            description="Cloud SQL instance is encrypted with CMEK.",
            severity="medium",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_sql_no_public_ip",
            title="Cloud SQL instance has no public IP",
            description="Cloud SQL instance has no public IP.",
            severity="high",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_sql_no_public_networks",
            title="Cloud SQL instance has no public authorized networks",
            description="Cloud SQL instance has no public authorized networks.",
            severity="critical",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_sql_pitr_enabled",
            title="Cloud SQL instance has point-in-time recovery enabled",
            description="Cloud SQL instance has point-in-time recovery enabled.",
            severity="medium",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql"],
        ),
        CheckDefinition(
            check_id="gcp_sql_ssl_required",
            title="Cloud SQL instance requires SSL",
            description="Cloud SQL instance requires SSL.",
            severity="high",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="gcp_storage_cmek_encryption",
            title="Bucket is encrypted with customer-managed keys (CMEK)",
            description="Bucket is encrypted with customer-managed keys (CMEK).",
            severity="medium",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_storage_logging_enabled",
            title="Bucket has access logging enabled",
            description="Bucket has access logging enabled.",
            severity="medium",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage", "logging"],
        ),
        CheckDefinition(
            check_id="gcp_storage_no_public_access",
            title="Bucket is not publicly accessible",
            description="Bucket is not publicly accessible.",
            severity="critical",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage", "public-access"],
        ),
        CheckDefinition(
            check_id="gcp_storage_retention_policy",
            title="Bucket has a retention policy configured",
            description="Bucket has a retention policy configured.",
            severity="medium",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage", "retention"],
        ),
        CheckDefinition(
            check_id="gcp_storage_uniform_access",
            title="Bucket has uniform bucket-level access",
            description="Bucket has uniform bucket-level access.",
            severity="medium",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        CheckDefinition(
            check_id="gcp_storage_versioning",
            title="Bucket has versioning enabled",
            description="Bucket has versioning enabled.",
            severity="low",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        # ---- IAM Advanced ----
        CheckDefinition(
            check_id="gcp_iam_workload_identity_federation",
            title="Workload Identity Federation used for external workloads",
            description="Workload Identity Federation used for external workloads instead of exported service account keys.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "workload-identity"],
        ),
        CheckDefinition(
            check_id="gcp_iam_org_policy_domain_restricted",
            title="Organization policy restricts domain sharing",
            description="Organization policy restricts sharing resources to specific trusted domains.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "org-policy"],
        ),
        CheckDefinition(
            check_id="gcp_iam_org_policy_vm_external_ip",
            title="Organization policy restricts VM external IPs",
            description="Organization policy restricts the creation of VM instances with external IP addresses.",
            severity="high",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "org-policy", "compute"],
        ),
        CheckDefinition(
            check_id="gcp_iam_org_policy_service_account_key",
            title="Organization policy disables SA key creation",
            description="Organization policy disables the creation of service account keys to reduce credential exposure.",
            severity="medium",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "org-policy"],
        ),
        CheckDefinition(
            check_id="gcp_iam_org_policy_uniform_bucket",
            title="Organization policy enforces uniform bucket access",
            description="Organization policy enforces uniform bucket-level access across all Cloud Storage buckets.",
            severity="medium",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "org-policy", "storage"],
        ),
        CheckDefinition(
            check_id="gcp_iam_conditional_bindings",
            title="IAM bindings use conditions where appropriate",
            description="IAM bindings leverage conditions to restrict access by time, resource, or request attributes.",
            severity="medium",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "conditional-access"],
        ),
        CheckDefinition(
            check_id="gcp_iam_recommender_reviewed",
            title="IAM Recommender suggestions reviewed",
            description="IAM Recommender suggestions have been reviewed and actioned to enforce least-privilege access.",
            severity="low",
            provider="gcp",
            service="iam",
            category="Identity",
            tags=["iam", "recommender"],
        ),
        # ---- Compute Advanced ----
        CheckDefinition(
            check_id="gcp_compute_sole_tenant_nodes",
            title="Sensitive workloads use sole-tenant nodes",
            description="Sensitive workloads run on sole-tenant nodes for physical isolation from other projects.",
            severity="low",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute", "isolation"],
        ),
        CheckDefinition(
            check_id="gcp_compute_instance_group_autohealing",
            title="Instance group has autohealing configured",
            description="Managed instance group has autohealing health check configured for automatic recovery.",
            severity="low",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute", "availability"],
        ),
        CheckDefinition(
            check_id="gcp_compute_disk_csek",
            title="Disk uses Customer-Supplied Encryption Key",
            description="Persistent disk uses a Customer-Supplied Encryption Key (CSEK) for maximum key control.",
            severity="low",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_compute_preemptible_non_critical",
            title="Preemptible VMs not used for critical workloads",
            description="Preemptible or spot VMs are not used for production-critical workloads that require high availability.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute", "availability"],
        ),
        CheckDefinition(
            check_id="gcp_compute_metadata_server_v2",
            title="Instance uses metadata server v2",
            description="VM instance uses the v2 metadata server endpoint to prevent SSRF-based metadata exfiltration.",
            severity="medium",
            provider="gcp",
            service="compute",
            category="Compute",
            tags=["compute", "metadata"],
        ),
        # ---- GKE Advanced ----
        CheckDefinition(
            check_id="gcp_gke_release_channel",
            title="GKE cluster enrolled in a release channel",
            description="GKE cluster is enrolled in a release channel for automatic version management.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "versioning"],
        ),
        CheckDefinition(
            check_id="gcp_gke_cluster_monitoring",
            title="GKE cluster has monitoring enabled",
            description="GKE cluster has Cloud Monitoring enabled for visibility into cluster health and performance.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "monitoring"],
        ),
        CheckDefinition(
            check_id="gcp_gke_intranode_visibility",
            title="GKE cluster has intranode visibility enabled",
            description="GKE cluster has intranode visibility enabled for full network flow logging between pods on the same node.",
            severity="low",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "networking"],
        ),
        CheckDefinition(
            check_id="gcp_gke_maintenance_window",
            title="GKE cluster has maintenance window configured",
            description="GKE cluster has a maintenance window configured to control when automatic upgrades occur.",
            severity="low",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "maintenance"],
        ),
        CheckDefinition(
            check_id="gcp_gke_node_auto_upgrade",
            title="GKE node pools have auto-upgrade enabled",
            description="GKE node pools have auto-upgrade enabled to receive security patches automatically.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "patching"],
        ),
        CheckDefinition(
            check_id="gcp_gke_node_auto_repair",
            title="GKE node pools have auto-repair enabled",
            description="GKE node pools have auto-repair enabled to automatically fix unhealthy nodes.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "availability"],
        ),
        CheckDefinition(
            check_id="gcp_gke_cos_node_image",
            title="GKE nodes use Container-Optimized OS",
            description="GKE nodes use Container-Optimized OS image for a minimal and hardened operating system.",
            severity="medium",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "hardening"],
        ),
        CheckDefinition(
            check_id="gcp_gke_metadata_server",
            title="GKE workload metadata server is enabled",
            description="GKE workload metadata server (GKE_METADATA) is enabled to prevent pods from accessing node metadata.",
            severity="high",
            provider="gcp",
            service="gke",
            category="Container",
            tags=["gke", "metadata"],
        ),
        # ---- Network Advanced ----
        CheckDefinition(
            check_id="gcp_network_firewall_no_ssh_world",
            title="Firewall does not allow SSH from 0.0.0.0/0",
            description="Firewall rule does not allow SSH (port 22) ingress from 0.0.0.0/0 or ::/0.",
            severity="critical",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "firewall", "ssh"],
        ),
        CheckDefinition(
            check_id="gcp_network_firewall_no_rdp_world",
            title="Firewall does not allow RDP from 0.0.0.0/0",
            description="Firewall rule does not allow RDP (port 3389) ingress from 0.0.0.0/0 or ::/0.",
            severity="critical",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "firewall", "rdp"],
        ),
        CheckDefinition(
            check_id="gcp_network_vpc_service_controls",
            title="VPC Service Controls perimeter configured",
            description="VPC Service Controls perimeter is configured to restrict data exfiltration from GCP services.",
            severity="high",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "vpc-sc"],
        ),
        CheckDefinition(
            check_id="gcp_network_cloud_armor",
            title="Cloud Armor security policy configured",
            description="Cloud Armor security policy is configured to protect internet-facing applications from DDoS and web attacks.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "cloud-armor"],
        ),
        CheckDefinition(
            check_id="gcp_network_cloud_nat_configured",
            title="Cloud NAT configured for private instances",
            description="Cloud NAT is configured to provide outbound internet access for private instances without external IPs.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "nat"],
        ),
        CheckDefinition(
            check_id="gcp_network_iap_configured",
            title="Identity-Aware Proxy configured for web apps",
            description="Identity-Aware Proxy is configured to enforce identity-based access control for web applications.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "iap"],
        ),
        CheckDefinition(
            check_id="gcp_network_firewall_logging",
            title="Firewall rules have logging enabled",
            description="Firewall rules have logging enabled to provide visibility into allowed and denied traffic.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "firewall", "logging"],
        ),
        # ---- Database Advanced ----
        CheckDefinition(
            check_id="gcp_sql_ha_configured",
            title="Cloud SQL instance has high availability",
            description="Cloud SQL instance has high availability configured with regional failover for production workloads.",
            severity="medium",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "availability"],
        ),
        CheckDefinition(
            check_id="gcp_sql_maintenance_window",
            title="Cloud SQL has maintenance window configured",
            description="Cloud SQL instance has a maintenance window configured to control when updates are applied.",
            severity="low",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "maintenance"],
        ),
        CheckDefinition(
            check_id="gcp_sql_password_policy",
            title="Cloud SQL password policy configured",
            description="Cloud SQL instance has a password policy configured to enforce complexity and rotation requirements.",
            severity="medium",
            provider="gcp",
            service="sql",
            category="Database",
            tags=["sql", "password"],
        ),
        CheckDefinition(
            check_id="gcp_spanner_iam_restricted",
            title="Spanner IAM policies are restrictive",
            description="Spanner database IAM policies follow least-privilege and do not grant overly broad access.",
            severity="medium",
            provider="gcp",
            service="spanner",
            category="Database",
            tags=["spanner", "iam"],
        ),
        CheckDefinition(
            check_id="gcp_spanner_backup",
            title="Spanner database has backups",
            description="Spanner database has regular backups configured to enable point-in-time recovery.",
            severity="medium",
            provider="gcp",
            service="spanner",
            category="Database",
            tags=["spanner", "backup"],
        ),
        CheckDefinition(
            check_id="gcp_bigtable_encryption",
            title="Bigtable instance uses CMEK",
            description="Bigtable instance is encrypted with customer-managed encryption keys for additional key control.",
            severity="medium",
            provider="gcp",
            service="bigtable",
            category="Database",
            tags=["bigtable", "encryption"],
        ),
        CheckDefinition(
            check_id="gcp_memorystore_auth",
            title="Memorystore instance has AUTH enabled",
            description="Memorystore Redis instance has AUTH enabled to require authentication for client connections.",
            severity="high",
            provider="gcp",
            service="memorystore",
            category="Database",
            tags=["memorystore", "authentication"],
        ),
        CheckDefinition(
            check_id="gcp_memorystore_transit_encryption",
            title="Memorystore has in-transit encryption",
            description="Memorystore Redis instance has in-transit encryption enabled to protect data between client and server.",
            severity="high",
            provider="gcp",
            service="memorystore",
            category="Database",
            tags=["memorystore", "encryption"],
        ),
        # ---- Security Services ----
        CheckDefinition(
            check_id="gcp_scc_enabled",
            title="Security Command Center is enabled",
            description="Security Command Center is enabled to provide centralized visibility into security posture and threats.",
            severity="high",
            provider="gcp",
            service="scc",
            category="Compliance",
            tags=["scc", "threat-detection"],
        ),
        CheckDefinition(
            check_id="gcp_scc_notifications",
            title="Security Command Center notifications configured",
            description="Security Command Center has notifications configured for critical and high-severity findings.",
            severity="medium",
            provider="gcp",
            service="scc",
            category="Compliance",
            tags=["scc", "notifications"],
        ),
        CheckDefinition(
            check_id="gcp_web_security_scanner",
            title="Web Security Scanner configured for apps",
            description="Web Security Scanner is configured to scan web applications for common vulnerabilities.",
            severity="medium",
            provider="gcp",
            service="websecurityscanner",
            category="Compliance",
            tags=["websecurityscanner", "vulnerability"],
        ),
        CheckDefinition(
            check_id="gcp_cas_configured",
            title="Certificate Authority Service configured",
            description="Certificate Authority Service is configured for private certificate management and issuance.",
            severity="medium",
            provider="gcp",
            service="cas",
            category="Encryption",
            tags=["cas", "certificates"],
        ),
        CheckDefinition(
            check_id="gcp_armor_ddos_protection",
            title="Cloud Armor DDoS protection configured",
            description="Cloud Armor advanced DDoS protection is configured to mitigate volumetric and protocol attacks.",
            severity="medium",
            provider="gcp",
            service="networking",
            category="Networking",
            tags=["networking", "cloud-armor", "ddos"],
        ),
        # ---- Logging Advanced ----
        CheckDefinition(
            check_id="gcp_logging_org_sinks",
            title="Organization-level log sinks configured",
            description="Organization-level log sinks are configured to aggregate logs from all projects centrally.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "org-level"],
        ),
        CheckDefinition(
            check_id="gcp_logging_vpc_flow_sampling",
            title="VPC flow logs have adequate sampling rate",
            description="VPC flow logs are configured with an adequate sampling rate for sufficient network visibility.",
            severity="low",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "networking", "flow-logs"],
        ),
        CheckDefinition(
            check_id="gcp_logging_access_transparency",
            title="Access Transparency logs enabled",
            description="Access Transparency logs are enabled to record when Google staff access your data.",
            severity="medium",
            provider="gcp",
            service="logging",
            category="Logging",
            tags=["logging", "access-transparency"],
        ),
        # ---- Serverless Advanced ----
        CheckDefinition(
            check_id="gcp_appengine_firewall",
            title="App Engine has firewall rules configured",
            description="App Engine application has firewall rules configured to restrict access by IP range.",
            severity="medium",
            provider="gcp",
            service="appengine",
            category="Serverless",
            tags=["appengine", "firewall"],
        ),
        CheckDefinition(
            check_id="gcp_cloudrun_min_instances",
            title="Cloud Run has minimum instances for availability",
            description="Cloud Run service has minimum instances configured to avoid cold starts and ensure availability.",
            severity="low",
            provider="gcp",
            service="cloudrun",
            category="Serverless",
            tags=["cloudrun", "availability"],
        ),
        CheckDefinition(
            check_id="gcp_function_cmek",
            title="Cloud Function uses CMEK encryption",
            description="Cloud Function is encrypted with a customer-managed encryption key for additional key control.",
            severity="medium",
            provider="gcp",
            service="cloudfunctions",
            category="Serverless",
            tags=["cloudfunctions", "encryption"],
        ),
        # ---- Storage Advanced ----
        CheckDefinition(
            check_id="gcp_storage_object_lifecycle",
            title="Bucket has object lifecycle management",
            description="Cloud Storage bucket has object lifecycle management rules configured for cost optimization and compliance.",
            severity="low",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage", "lifecycle"],
        ),
        CheckDefinition(
            check_id="gcp_storage_signed_urls_restricted",
            title="Signed URLs have limited duration",
            description="Cloud Storage signed URLs are generated with limited expiration durations to minimize exposure.",
            severity="medium",
            provider="gcp",
            service="storage",
            category="Storage",
            tags=["storage", "signed-urls"],
        ),
    ]
