"""Check definitions for GitHub.

Auto-generated from github scanner. 64 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all GitHub check definitions."""
    return [
        CheckDefinition(
            check_id="github_ac_admin_count",
            title="Organization admin count is between 2 and 10",
            description="Organization admin count is between 2 and 10.",
            severity="high",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_ac_deploy_keys_audit",
            title="Deploy keys with write access are minimized",
            description="Deploy keys with write access are minimized.",
            severity="high",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control", "audit"],
        ),
        CheckDefinition(
            check_id="github_ac_outside_collaborator_review",
            title="Outside collaborator access is justified",
            description="Outside collaborator access is justified.",
            severity="medium",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_ac_outside_collaborators",
            title="Outside collaborators are reviewed and minimal",
            description="Outside collaborators are reviewed and minimal.",
            severity="medium",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_ac_pat_excessive_scope",
            title="Configured token does not have excessive admin scopes",
            description="Configured token does not have excessive admin scopes.",
            severity="high",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_ac_stale_invitations",
            title="No stale organization invitations (older than 7 days)",
            description="No stale organization invitations (older than 7 days).",
            severity="low",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_actions_no_pr_approval",
            title="Actions cannot approve pull request reviews",
            description="Actions cannot approve pull request reviews.",
            severity="medium",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_oidc_configured",
            title="OIDC is configured for cloud deployment authentication",
            description="OIDC is configured for cloud deployment authentication.",
            severity="medium",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_restricted",
            title="GitHub Actions are restricted to verified or selected actions",
            description="GitHub Actions are restricted to verified or selected actions.",
            severity="high",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_runner_offline",
            title="Self-hosted runner is online and healthy",
            description="Self-hosted runner is online and healthy.",
            severity="medium",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_secrets_managed",
            title="Organization Actions secrets are managed centrally",
            description="Organization Actions secrets are managed centrally.",
            severity="medium",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_self_hosted_runners",
            title="Self-hosted runners inventory is reviewed",
            description="Self-hosted runners inventory is reviewed.",
            severity="medium",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_workflow_permissions",
            title="Default workflow permissions are read-only",
            description="Default workflow permissions are read-only.",
            severity="high",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_org_2fa_required",
            title="Organization requires two-factor authentication",
            description="Organization requires two-factor authentication.",
            severity="critical",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_default_repo_permission",
            title="Default repository permission is restrictive (read or none)",
            description="Default repository permission is restrictive (read or none).",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_dependency_alerts_enabled",
            title="Dependabot alerts are enabled for new repositories",
            description="Dependabot alerts are enabled for new repositories.",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_members_create_repos",
            title="Members cannot create repositories by default",
            description="Members cannot create repositories by default.",
            severity="medium",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_secret_scanning_enabled",
            title="Secret scanning is enabled for new repositories",
            description="Secret scanning is enabled for new repositories.",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_sso_configured",
            title="SAML SSO is configured for the organization",
            description="SAML SSO is configured for the organization.",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_repo_branch_protection",
            title="Default branch has branch protection rules",
            description="Default branch has branch protection rules.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_code_scanning",
            title="Code scanning is enabled on repository",
            description="Code scanning is enabled on repository.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_codeowners",
            title="CODEOWNERS file exists in repository",
            description="CODEOWNERS file exists in repository.",
            severity="low",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_no_force_push",
            title="Force pushes are restricted on default branch",
            description="Force pushes are restricted on default branch.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_require_reviews",
            title="Pull request reviews are required before merging",
            description="Pull request reviews are required before merging.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_require_status_checks",
            title="Status checks are required before merging",
            description="Status checks are required before merging.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_require_up_to_date",
            title="Branches must be up to date before merging",
            description="Branches must be up to date before merging.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_secret_scanning",
            title="Secret scanning is enabled on repository",
            description="Secret scanning is enabled on repository.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_signed_commits",
            title="Signed commits are required on default branch",
            description="Signed commits are required on default branch.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_vulnerability_alerts",
            title="Vulnerability alerts (Dependabot) are enabled",
            description="Vulnerability alerts (Dependabot) are enabled.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        # --- New checks below ---
        CheckDefinition(
            check_id="github_org_audit_log_streaming",
            title="Audit log streaming is configured to external SIEM",
            description="Audit log streaming is configured to external SIEM.",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security", "audit"],
        ),
        CheckDefinition(
            check_id="github_org_verified_domains",
            title="Organization has verified domain ownership",
            description="Organization has verified domain ownership.",
            severity="medium",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_ip_allow_list",
            title="IP allow list is configured for the organization",
            description="IP allow list is configured for the organization.",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security", "network"],
        ),
        CheckDefinition(
            check_id="github_org_saml_enforced",
            title="SAML SSO is enforced (not just enabled) for the organization",
            description="SAML SSO is enforced (not just enabled) for the organization.",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security", "sso"],
        ),
        CheckDefinition(
            check_id="github_org_security_manager_team",
            title="Security manager team is designated for the organization",
            description="Security manager team is designated for the organization.",
            severity="medium",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_base_permissions_none",
            title="Organization base permissions are set to none",
            description="Organization base permissions are set to none.",
            severity="high",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security", "access-control"],
        ),
        CheckDefinition(
            check_id="github_org_fork_policy",
            title="Forking policy is restricted for private repositories",
            description="Forking policy is restricted for private repositories.",
            severity="medium",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_package_visibility",
            title="Default package visibility is set to private",
            description="Default package visibility is set to private.",
            severity="medium",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_org_runner_groups",
            title="Self-hosted runner groups are scoped to specific repositories",
            description="Self-hosted runner groups are scoped to specific repositories.",
            severity="medium",
            provider="github",
            service="org_security",
            category="DevOps",
            tags=["org_security", "actions_security"],
        ),
        CheckDefinition(
            check_id="github_org_billing_manager_limited",
            title="Billing manager role assignments are limited",
            description="Billing manager role assignments are limited.",
            severity="low",
            provider="github",
            service="org_security",
            category="Compliance",
            tags=["org_security"],
        ),
        CheckDefinition(
            check_id="github_repo_dependabot_security_updates",
            title="Dependabot security updates are enabled",
            description="Dependabot security updates are enabled.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security", "dependabot"],
        ),
        CheckDefinition(
            check_id="github_repo_dependabot_version_updates",
            title="Dependabot version updates are configured",
            description="Dependabot version updates are configured.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security", "dependabot"],
        ),
        CheckDefinition(
            check_id="github_repo_private_vulnerability_reporting",
            title="Private vulnerability reporting is enabled",
            description="Private vulnerability reporting is enabled.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_security_policy",
            title="SECURITY.md policy file exists in repository",
            description="SECURITY.md policy file exists in repository.",
            severity="low",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_license_configured",
            title="Repository has a license file configured",
            description="Repository has a license file configured.",
            severity="low",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_dismiss_stale_reviews",
            title="Stale pull request reviews are dismissed on new commits",
            description="Stale pull request reviews are dismissed on new commits.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_require_review_count_2",
            title="At least 2 pull request reviews are required before merging",
            description="At least 2 pull request reviews are required before merging.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_restrict_deletions",
            title="Branch deletion is restricted on default branch",
            description="Branch deletion is restricted on default branch.",
            severity="medium",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_require_conversation_resolution",
            title="Conversation resolution is required before merging",
            description="Conversation resolution is required before merging.",
            severity="low",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_require_linear_history",
            title="Linear history is required on default branch",
            description="Linear history is required on default branch.",
            severity="low",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_repo_deploy_environments_protected",
            title="Deployment environments have protection rules configured",
            description="Deployment environments have protection rules configured.",
            severity="high",
            provider="github",
            service="repo_security",
            category="DevOps",
            tags=["repo_security", "environments"],
        ),
        CheckDefinition(
            check_id="github_repo_environment_protection_rules",
            title="Environment protection rules include required reviewers",
            description="Environment protection rules include required reviewers.",
            severity="high",
            provider="github",
            service="repo_security",
            category="DevOps",
            tags=["repo_security", "environments"],
        ),
        CheckDefinition(
            check_id="github_repo_no_admin_bypass",
            title="Administrators cannot bypass branch protection rules",
            description="Administrators cannot bypass branch protection rules.",
            severity="high",
            provider="github",
            service="repo_security",
            category="Compliance",
            tags=["repo_security"],
        ),
        CheckDefinition(
            check_id="github_actions_pinned_versions",
            title="GitHub Actions use pinned versions (SHA references)",
            description="GitHub Actions use pinned versions (SHA references).",
            severity="high",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security", "supply-chain"],
        ),
        CheckDefinition(
            check_id="github_actions_no_self_hosted_public",
            title="Self-hosted runners are not used on public repositories",
            description="Self-hosted runners are not used on public repositories.",
            severity="critical",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_step_debug_disabled",
            title="Actions step debug logging is disabled in production",
            description="Actions step debug logging is disabled in production.",
            severity="medium",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_fork_pr_approval",
            title="Fork pull request workflows require approval before running",
            description="Fork pull request workflows require approval before running.",
            severity="high",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_artifact_retention",
            title="Artifact retention period is configured appropriately",
            description="Artifact retention period is configured appropriately.",
            severity="low",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_actions_cache_security",
            title="Actions cache is scoped and not used for sensitive data",
            description="Actions cache is scoped and not used for sensitive data.",
            severity="medium",
            provider="github",
            service="actions_security",
            category="DevOps",
            tags=["actions_security"],
        ),
        CheckDefinition(
            check_id="github_ac_ssh_key_audit",
            title="SSH keys are audited and rotated regularly",
            description="SSH keys are audited and rotated regularly.",
            severity="medium",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control", "audit"],
        ),
        CheckDefinition(
            check_id="github_ac_fine_grained_pat",
            title="Fine-grained personal access tokens are preferred over classic tokens",
            description="Fine-grained personal access tokens are preferred over classic tokens.",
            severity="medium",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_ac_team_permissions_reviewed",
            title="Team repository permissions follow least privilege",
            description="Team repository permissions follow least privilege.",
            severity="medium",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_ac_inactive_members_removed",
            title="Inactive organization members are removed within 90 days",
            description="Inactive organization members are removed within 90 days.",
            severity="medium",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control"],
        ),
        CheckDefinition(
            check_id="github_ac_webhook_ssl_verified",
            title="Webhooks use SSL verification",
            description="Webhooks use SSL verification.",
            severity="high",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control", "webhooks"],
        ),
        CheckDefinition(
            check_id="github_ac_webhook_secrets_configured",
            title="Webhooks have secrets configured for payload validation",
            description="Webhooks have secrets configured for payload validation.",
            severity="high",
            provider="github",
            service="access_control",
            category="Compliance",
            tags=["access_control", "webhooks"],
        ),
    ]
