"""Check definitions for Google Workspace.

Auto-generated from google_workspace scanner. 95 checks.
Covers CIS Google Workspace Benchmark v1.3.0 sections 1-10.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Google Workspace check definitions."""
    return [
        # =====================================================================
        # Section 1 - Admin Console / Directory (~15 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_admin_count_appropriate",
            title="Admin count is between 2 and 10",
            description="Admin count is between 2 and 10.",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_admin_mfa_enforced",
            title="Admin user has 2-step verification enforced",
            description="Admin user has 2-step verification enforced.",
            severity="critical",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="gws_cis_multiple_super_admins",
            title="Multiple super admin accounts exist (2-4) (CIS 1.1.1)",
            description="Multiple super admin accounts exist (2-4) (CIS 1.1.1).",
            severity="critical",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory"],
        ),
        CheckDefinition(
            check_id="gws_cis_directory_external_restricted",
            title="Directory data sharing is restricted externally (CIS 1.2.1.1)",
            description="Directory data sharing is restricted externally (CIS 1.2.1.1).",
            severity="high",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory"],
        ),
        CheckDefinition(
            check_id="gws_super_admin_minimal",
            title="Super admin accounts are minimized (2-3 recommended)",
            description="Super admin accounts are minimized (2-3 recommended).",
            severity="critical",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_password_policy_strength",
            title="Password policy requires minimum 12 characters",
            description="Password policy requires minimum 12 characters.",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_suspended_accounts_reviewed",
            title="Suspended accounts are reviewed and cleaned up",
            description="Suspended accounts are reviewed and cleaned up.",
            severity="low",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_user_2fa_enrolled",
            title="User is enrolled in 2-step verification",
            description="User is enrolled in 2-step verification.",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_cis_admin_recovery_options",
            title="Admin account recovery options are configured (CIS 1.1.3)",
            description="Admin account recovery options are configured (CIS 1.1.3).",
            severity="high",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory", "admin"],
        ),
        CheckDefinition(
            check_id="gws_cis_custom_admin_roles_reviewed",
            title="Custom admin roles are reviewed regularly (CIS 1.1.4)",
            description="Custom admin roles are reviewed regularly (CIS 1.1.4).",
            severity="medium",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory", "admin"],
        ),
        CheckDefinition(
            check_id="gws_cis_password_complexity_enforced",
            title="Password complexity requirements are enforced (CIS 1.3.1)",
            description="Password complexity requirements are enforced (CIS 1.3.1).",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users", "password"],
        ),
        CheckDefinition(
            check_id="gws_cis_password_reuse_prevented",
            title="Password reuse is prevented (CIS 1.3.2)",
            description="Password reuse is prevented (CIS 1.3.2).",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users", "password"],
        ),
        CheckDefinition(
            check_id="gws_cis_account_recovery_restricted",
            title="Account recovery options are restricted for users (CIS 1.3.3)",
            description="Account recovery options are restricted for users (CIS 1.3.3).",
            severity="medium",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users", "password"],
        ),
        CheckDefinition(
            check_id="gws_cis_ou_structure_configured",
            title="Organization unit structure is properly configured (CIS 1.4.1)",
            description="Organization unit structure is properly configured (CIS 1.4.1).",
            severity="medium",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory"],
        ),
        CheckDefinition(
            check_id="gws_cis_delegated_admin_limited",
            title="Delegated admin privileges are limited (CIS 1.1.5)",
            description="Delegated admin privileges are limited (CIS 1.1.5).",
            severity="high",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory", "admin"],
        ),
        CheckDefinition(
            check_id="gws_cis_domain_verified",
            title="Domain registration is verified (CIS 1.5.1)",
            description="Domain registration is verified (CIS 1.5.1).",
            severity="high",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory"],
        ),
        CheckDefinition(
            check_id="gws_cis_admin_audit_log_enabled",
            title="Admin audit log is enabled (CIS 1.6.1)",
            description="Admin audit log is enabled (CIS 1.6.1).",
            severity="high",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory", "audit"],
        ),
        # =====================================================================
        # Section 2 - Gmail / Email Security (~20 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_email_spf_configured",
            title="SPF record is configured for the domain",
            description="SPF record is configured for the domain.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_spf_strict",
            title="SPF record uses strict fail (-all) policy",
            description="SPF record uses strict fail (-all) policy.",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_dkim_configured",
            title="DKIM is configured for the domain",
            description="DKIM is configured for the domain.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_dmarc_configured",
            title="DMARC record is configured for the domain",
            description="DMARC record is configured for the domain.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_dmarc_policy_strict",
            title="DMARC policy is set to reject or quarantine",
            description="DMARC policy is set to reject or quarantine.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_phishing_protection",
            title="Advanced phishing and malware protections are configured",
            description="Advanced phishing and malware protections are configured.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_allowlist_reviewed",
            title="Email allowlist entries are reviewed and minimal",
            description="Email allowlist entries are reviewed and minimal.",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_content_compliance",
            title="Email content compliance rules are configured",
            description="Email content compliance rules are configured.",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_email_attachment_safety",
            title="Attachment safety settings are enabled (CIS 2.5.1)",
            description="Attachment safety settings are enabled (CIS 2.5.1).",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_email_link_protection",
            title="Links and external images protection is enabled (CIS 2.5.2)",
            description="Links and external images protection is enabled (CIS 2.5.2).",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_email_spoofing_quarantined",
            title="Spoofed emails are quarantined (CIS 2.6.1)",
            description="Spoofed emails are quarantined (CIS 2.6.1).",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_email_internal_encryption",
            title="Internal email encryption (TLS) is enforced (CIS 2.7.1)",
            description="Internal email encryption (TLS) is enforced (CIS 2.7.1).",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_mail_routing_reviewed",
            title="Mail routing rules are reviewed (CIS 2.8.1)",
            description="Mail routing rules are reviewed (CIS 2.8.1).",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_smtp_relay_restricted",
            title="SMTP relay service is restricted (CIS 2.8.2)",
            description="SMTP relay service is restricted (CIS 2.8.2).",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_pop_imap_restricted",
            title="POP and IMAP access is disabled or restricted (CIS 2.9.1)",
            description="POP and IMAP access is disabled or restricted (CIS 2.9.1).",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_external_reply_warning",
            title="External reply warning is enabled (CIS 2.10.1)",
            description="External reply warning is enabled (CIS 2.10.1).",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_safe_browsing_gmail",
            title="Safe browsing for Gmail is enabled (CIS 2.11.1)",
            description="Safe browsing for Gmail is enabled (CIS 2.11.1).",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_inbound_gateway_configured",
            title="Inbound email gateway is properly configured (CIS 2.12.1)",
            description="Inbound email gateway is properly configured (CIS 2.12.1).",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_email_delegation_restricted",
            title="Email delegation is restricted (CIS 2.13.1)",
            description="Email delegation is restricted (CIS 2.13.1).",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_cis_auto_forwarding_disabled",
            title="Automatic email forwarding is disabled (CIS 2.14.1)",
            description="Automatic email forwarding is disabled (CIS 2.14.1).",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        # =====================================================================
        # Section 3 - Drive / Data (~15 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_drive_external_sharing_restricted",
            title="External file sharing is restricted",
            description="External file sharing is restricted.",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_drive_link_sharing_defaults",
            title="Default link sharing is set to restricted",
            description="Default link sharing is set to restricted.",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_drive_dlp_configured",
            title="Data Loss Prevention (DLP) rules are configured",
            description="Data Loss Prevention (DLP) rules are configured.",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_desktop_restricted",
            title="Drive for desktop is restricted (CIS 3.4.1)",
            description="Drive for desktop is restricted (CIS 3.4.1).",
            severity="medium",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_shared_drive_creation_restricted",
            title="Shared drive creation is restricted (CIS 3.5.1)",
            description="Shared drive creation is restricted (CIS 3.5.1).",
            severity="medium",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_file_transfer_limits",
            title="File transfer and size limits are configured (CIS 3.6.1)",
            description="File transfer and size limits are configured (CIS 3.6.1).",
            severity="low",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_addons_restricted",
            title="Drive add-ons are restricted (CIS 3.7.1)",
            description="Drive add-ons are restricted (CIS 3.7.1).",
            severity="medium",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_offline_restricted",
            title="Offline access to Drive is restricted (CIS 3.8.1)",
            description="Offline access to Drive is restricted (CIS 3.8.1).",
            severity="medium",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_labels_configured",
            title="Drive labels and classification are configured (CIS 3.9.1)",
            description="Drive labels and classification are configured (CIS 3.9.1).",
            severity="medium",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_shared_drive_external_members",
            title="Shared drive external member access is restricted (CIS 3.5.2)",
            description="Shared drive external member access is restricted (CIS 3.5.2).",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_audit_logging",
            title="Drive audit logging is enabled (CIS 3.10.1)",
            description="Drive audit logging is enabled (CIS 3.10.1).",
            severity="medium",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data", "audit"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_sharing_allowlist",
            title="Drive sharing is restricted to allowlisted domains (CIS 3.1.2)",
            description="Drive sharing is restricted to allowlisted domains (CIS 3.1.2).",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_published_web_restricted",
            title="Publishing files to the web is restricted (CIS 3.2.1)",
            description="Publishing files to the web is restricted (CIS 3.2.1).",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_access_checker",
            title="Access checker suggestions are restricted (CIS 3.3.1)",
            description="Access checker suggestions are restricted (CIS 3.3.1).",
            severity="medium",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        # =====================================================================
        # Section 4 - Apps & APIs (~12 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_app_access_controlled",
            title="Third-party app access is controlled",
            description="Third-party app access is controlled.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_api_access_restricted",
            title="API access is restricted for third-party applications (CIS 4.2.1.1)",
            description="API access is restricted for third-party applications (CIS 4.2.1.1).",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_less_secure_apps_disabled",
            title="Less secure app access is disabled",
            description="Less secure app access is disabled.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_login_challenges_enabled",
            title="Login challenges are enabled for suspicious sign-ins",
            description="Login challenges are enabled for suspicious sign-ins.",
            severity="medium",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_security_keys_admins",
            title="Security keys are required for admin accounts",
            description="Security keys are required for admin accounts.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_sso_configured",
            title="Single Sign-On (SSO) is configured",
            description="Single Sign-On (SSO) is configured.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_oauth_consent_configured",
            title="OAuth consent screen is properly configured (CIS 4.3.1)",
            description="OAuth consent screen is properly configured (CIS 4.3.1).",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security", "oauth"],
        ),
        CheckDefinition(
            check_id="gws_cis_marketplace_apps_restricted",
            title="Google Workspace Marketplace apps are restricted (CIS 4.4.1)",
            description="Google Workspace Marketplace apps are restricted (CIS 4.4.1).",
            severity="medium",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_connected_apps_reviewed",
            title="Connected third-party apps are reviewed (CIS 4.5.1)",
            description="Connected third-party apps are reviewed (CIS 4.5.1).",
            severity="medium",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_app_passwords_disabled",
            title="Application-specific passwords are disabled (CIS 4.6.1)",
            description="Application-specific passwords are disabled (CIS 4.6.1).",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_saml_apps_reviewed",
            title="SAML application configurations are reviewed (CIS 4.7.1)",
            description="SAML application configurations are reviewed (CIS 4.7.1).",
            severity="medium",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_chrome_management_enabled",
            title="Chrome browser management is enabled (CIS 4.8.1)",
            description="Chrome browser management is enabled (CIS 4.8.1).",
            severity="medium",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_app_deployment_restricted",
            title="App deployment and installation is restricted (CIS 4.9.1)",
            description="App deployment and installation is restricted (CIS 4.9.1).",
            severity="medium",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        # =====================================================================
        # Section 5 - Reporting / Monitoring (~10 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_cis_app_usage_report_reviewed",
            title="Application usage activity report is reviewed (CIS 5.1.1.1)",
            description="Application usage activity report is reviewed (CIS 5.1.1.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting"],
        ),
        CheckDefinition(
            check_id="gws_cis_login_activity_monitored",
            title="Login activity is monitored (CIS 5.2.1)",
            description="Login activity is monitored (CIS 5.2.1).",
            severity="high",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting"],
        ),
        CheckDefinition(
            check_id="gws_cis_admin_activity_audit",
            title="Admin activity audit log is reviewed (CIS 5.3.1)",
            description="Admin activity audit log is reviewed (CIS 5.3.1).",
            severity="high",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting", "audit"],
        ),
        CheckDefinition(
            check_id="gws_cis_user_activity_reports",
            title="User activity reports are enabled and reviewed (CIS 5.4.1)",
            description="User activity reports are enabled and reviewed (CIS 5.4.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting"],
        ),
        CheckDefinition(
            check_id="gws_cis_security_investigation_tool",
            title="Security investigation tool is enabled (CIS 5.5.1)",
            description="Security investigation tool is enabled (CIS 5.5.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting", "security"],
        ),
        CheckDefinition(
            check_id="gws_cis_bigquery_export_configured",
            title="BigQuery export for logs is configured (CIS 5.6.1)",
            description="BigQuery export for logs is configured (CIS 5.6.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_center_active",
            title="Alert center is active and configured (CIS 5.7.1)",
            description="Alert center is active and configured (CIS 5.7.1).",
            severity="high",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting", "alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_mobile_device_audit",
            title="Mobile device audit is enabled (CIS 5.8.1)",
            description="Mobile device audit is enabled (CIS 5.8.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting", "mobile"],
        ),
        CheckDefinition(
            check_id="gws_cis_drive_file_audit",
            title="Drive file audit activity is monitored (CIS 5.9.1)",
            description="Drive file audit activity is monitored (CIS 5.9.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting", "drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_cis_email_log_search_enabled",
            title="Email log search is enabled and reviewed (CIS 5.10.1)",
            description="Email log search is enabled and reviewed (CIS 5.10.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting", "email_security"],
        ),
        # =====================================================================
        # Section 6 - Calendar (~5 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_cis_calendar_external_sharing_restricted",
            title="External calendar sharing is restricted (CIS 6.1.1)",
            description="External calendar sharing is restricted (CIS 6.1.1).",
            severity="medium",
            provider="google_workspace",
            service="calendar",
            category="Compliance",
            tags=["calendar"],
        ),
        CheckDefinition(
            check_id="gws_cis_calendar_appointment_slots_restricted",
            title="Calendar appointment slots are restricted for external users (CIS 6.2.1)",
            description="Calendar appointment slots are restricted for external users (CIS 6.2.1).",
            severity="low",
            provider="google_workspace",
            service="calendar",
            category="Compliance",
            tags=["calendar"],
        ),
        CheckDefinition(
            check_id="gws_cis_calendar_video_conferencing_defaults",
            title="Video conferencing default settings are configured (CIS 6.3.1)",
            description="Video conferencing default settings are configured (CIS 6.3.1).",
            severity="low",
            provider="google_workspace",
            service="calendar",
            category="Compliance",
            tags=["calendar"],
        ),
        CheckDefinition(
            check_id="gws_cis_calendar_interop_managed",
            title="Calendar interop with external systems is managed (CIS 6.4.1)",
            description="Calendar interop with external systems is managed (CIS 6.4.1).",
            severity="low",
            provider="google_workspace",
            service="calendar",
            category="Compliance",
            tags=["calendar"],
        ),
        CheckDefinition(
            check_id="gws_cis_calendar_resource_booking",
            title="Calendar resource booking is properly configured (CIS 6.5.1)",
            description="Calendar resource booking is properly configured (CIS 6.5.1).",
            severity="low",
            provider="google_workspace",
            service="calendar",
            category="Compliance",
            tags=["calendar"],
        ),
        # =====================================================================
        # Section 7 - Sites (~3 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_cis_sites_creation_restricted",
            title="Sites creation is restricted (CIS 7.1.1)",
            description="Sites creation is restricted (CIS 7.1.1).",
            severity="medium",
            provider="google_workspace",
            service="sites",
            category="Compliance",
            tags=["sites"],
        ),
        CheckDefinition(
            check_id="gws_cis_sites_external_sharing_restricted",
            title="External sharing of Sites is restricted (CIS 7.2.1)",
            description="External sharing of Sites is restricted (CIS 7.2.1).",
            severity="medium",
            provider="google_workspace",
            service="sites",
            category="Compliance",
            tags=["sites"],
        ),
        CheckDefinition(
            check_id="gws_cis_sites_file_upload_restricted",
            title="Sites file upload restrictions are configured (CIS 7.3.1)",
            description="Sites file upload restrictions are configured (CIS 7.3.1).",
            severity="low",
            provider="google_workspace",
            service="sites",
            category="Compliance",
            tags=["sites"],
        ),
        # =====================================================================
        # Section 8 - Groups (~8 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_cis_group_creation_restricted",
            title="Group creation is restricted to admins (CIS 8.1.1)",
            description="Group creation is restricted to admins (CIS 8.1.1).",
            severity="medium",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        CheckDefinition(
            check_id="gws_cis_group_external_access_restricted",
            title="External access to groups is restricted (CIS 8.2.1)",
            description="External access to groups is restricted (CIS 8.2.1).",
            severity="high",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        CheckDefinition(
            check_id="gws_cis_group_sharing_settings",
            title="Group sharing settings are properly configured (CIS 8.3.1)",
            description="Group sharing settings are properly configured (CIS 8.3.1).",
            severity="medium",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        CheckDefinition(
            check_id="gws_cis_group_owner_management",
            title="Group owner and manager roles are reviewed (CIS 8.4.1)",
            description="Group owner and manager roles are reviewed (CIS 8.4.1).",
            severity="medium",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        CheckDefinition(
            check_id="gws_cis_group_email_permissions",
            title="Group email sending permissions are restricted (CIS 8.5.1)",
            description="Group email sending permissions are restricted (CIS 8.5.1).",
            severity="medium",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        CheckDefinition(
            check_id="gws_cis_group_archive_retention",
            title="Group message archive and retention is configured (CIS 8.6.1)",
            description="Group message archive and retention is configured (CIS 8.6.1).",
            severity="low",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        CheckDefinition(
            check_id="gws_cis_groups_business_access",
            title="Groups for Business access controls are configured (CIS 8.7.1)",
            description="Groups for Business access controls are configured (CIS 8.7.1).",
            severity="medium",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        CheckDefinition(
            check_id="gws_cis_group_collaborative_inbox",
            title="Collaborative inbox settings are reviewed (CIS 8.8.1)",
            description="Collaborative inbox settings are reviewed (CIS 8.8.1).",
            severity="low",
            provider="google_workspace",
            service="groups",
            category="Compliance",
            tags=["groups"],
        ),
        # =====================================================================
        # Section 9 - Mobile Device Management (~8 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_cis_mobile_management_enabled",
            title="Mobile device management is enabled (CIS 9.1.1)",
            description="Mobile device management is enabled (CIS 9.1.1).",
            severity="high",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management"],
        ),
        CheckDefinition(
            check_id="gws_cis_device_approval_required",
            title="Device approval is required before access (CIS 9.2.1)",
            description="Device approval is required before access (CIS 9.2.1).",
            severity="high",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management"],
        ),
        CheckDefinition(
            check_id="gws_cis_screen_lock_enforced",
            title="Screen lock is enforced on mobile devices (CIS 9.3.1)",
            description="Screen lock is enforced on mobile devices (CIS 9.3.1).",
            severity="high",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management"],
        ),
        CheckDefinition(
            check_id="gws_cis_device_wipe_enabled",
            title="Remote data wipe is enabled for mobile devices (CIS 9.4.1)",
            description="Remote data wipe is enabled for mobile devices (CIS 9.4.1).",
            severity="high",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management"],
        ),
        CheckDefinition(
            check_id="gws_cis_mobile_app_management",
            title="Mobile application management is configured (CIS 9.5.1)",
            description="Mobile application management is configured (CIS 9.5.1).",
            severity="medium",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management"],
        ),
        CheckDefinition(
            check_id="gws_cis_company_owned_device_policies",
            title="Company-owned device policies are configured (CIS 9.6.1)",
            description="Company-owned device policies are configured (CIS 9.6.1).",
            severity="medium",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management"],
        ),
        CheckDefinition(
            check_id="gws_cis_device_encryption_required",
            title="Device encryption is required (CIS 9.7.1)",
            description="Device encryption is required (CIS 9.7.1).",
            severity="high",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management"],
        ),
        CheckDefinition(
            check_id="gws_cis_suspicious_mobile_activity_alerts",
            title="Suspicious mobile activity alerts are enabled (CIS 9.8.1)",
            description="Suspicious mobile activity alerts are enabled (CIS 9.8.1).",
            severity="medium",
            provider="google_workspace",
            service="mobile_management",
            category="Compliance",
            tags=["mobile_management", "alerts"],
        ),
        # =====================================================================
        # Section 10 - Alerts / Rules (~8 checks)
        # =====================================================================
        CheckDefinition(
            check_id="gws_cis_alert_super_admin_password",
            title="Alert for super admin password change is enabled (CIS 10.1.1)",
            description="Alert for super admin password change is enabled (CIS 10.1.1).",
            severity="critical",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_government_attack",
            title="Alert for government-backed attack is enabled (CIS 10.2.1)",
            description="Alert for government-backed attack is enabled (CIS 10.2.1).",
            severity="critical",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_suspicious_activity",
            title="Alert for suspicious login activity is enabled (CIS 10.3.1)",
            description="Alert for suspicious login activity is enabled (CIS 10.3.1).",
            severity="high",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_admin_privilege_changes",
            title="Alert for admin privilege changes is enabled (CIS 10.4.1)",
            description="Alert for admin privilege changes is enabled (CIS 10.4.1).",
            severity="critical",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_leaked_password",
            title="Alert for leaked password is enabled (CIS 10.5.1)",
            description="Alert for leaked password is enabled (CIS 10.5.1).",
            severity="high",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_employee_spoofing",
            title="Alert for employee spoofing attempt is enabled (CIS 10.6.1)",
            description="Alert for employee spoofing attempt is enabled (CIS 10.6.1).",
            severity="high",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_mobile_device_compromise",
            title="Alert for mobile device compromise is enabled (CIS 10.7.1)",
            description="Alert for mobile device compromise is enabled (CIS 10.7.1).",
            severity="high",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
        CheckDefinition(
            check_id="gws_cis_alert_external_sharing_changes",
            title="Alert for external sharing changes is enabled (CIS 10.8.1)",
            description="Alert for external sharing changes is enabled (CIS 10.8.1).",
            severity="high",
            provider="google_workspace",
            service="alerts",
            category="Compliance",
            tags=["alerts"],
        ),
    ]
