"""Check definitions for Google Workspace.

Auto-generated from google_workspace scanner. 26 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Google Workspace check definitions."""
    return [
        CheckDefinition(
            check_id="gws_admin_count_appropriate",
            title="Admin count is between 2 and 10",
            description="Admin count is between 2 and 10.",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_admin_mfa_enforced",
            title="Admin user has 2-step verification enforced",
            description="Admin user has 2-step verification enforced.",
            severity="critical",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="gws_app_access_controlled",
            title="Third-party app access is controlled",
            description="Third-party app access is controlled.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_api_access_restricted",
            title="API access is restricted for third-party applications (CIS 4.2.1.1)",
            description="API access is restricted for third-party applications (CIS 4.2.1.1).",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_cis_app_usage_report_reviewed",
            title="Application usage activity report is reviewed (CIS 5.1.1.1)",
            description="Application usage activity report is reviewed (CIS 5.1.1.1).",
            severity="medium",
            provider="google_workspace",
            service="reporting",
            category="Compliance",
            tags=["reporting"],
        ),
        CheckDefinition(
            check_id="gws_cis_directory_external_restricted",
            title="Directory data sharing is restricted externally (CIS 1.2.1.1)",
            description="Directory data sharing is restricted externally (CIS 1.2.1.1).",
            severity="high",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory"],
        ),
        CheckDefinition(
            check_id="gws_cis_multiple_super_admins",
            title="Multiple super admin accounts exist (2-4) (CIS 1.1.1)",
            description="Multiple super admin accounts exist (2-4) (CIS 1.1.1).",
            severity="critical",
            provider="google_workspace",
            service="directory",
            category="Compliance",
            tags=["directory"],
        ),
        CheckDefinition(
            check_id="gws_drive_dlp_configured",
            title="Data Loss Prevention (DLP) rules are configured",
            description="Data Loss Prevention (DLP) rules are configured.",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_drive_external_sharing_restricted",
            title="External file sharing is restricted",
            description="External file sharing is restricted.",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_drive_link_sharing_defaults",
            title="Default link sharing is set to restricted",
            description="Default link sharing is set to restricted.",
            severity="high",
            provider="google_workspace",
            service="drive_and_data",
            category="Compliance",
            tags=["drive_and_data"],
        ),
        CheckDefinition(
            check_id="gws_email_allowlist_reviewed",
            title="Email allowlist entries are reviewed and minimal",
            description="Email allowlist entries are reviewed and minimal.",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_content_compliance",
            title="Email content compliance rules are configured",
            description="Email content compliance rules are configured.",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_dkim_configured",
            title="DKIM is configured for the domain",
            description="DKIM is configured for the domain.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_dmarc_configured",
            title="DMARC record is configured for the domain",
            description="DMARC record is configured for the domain.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_dmarc_policy_strict",
            title="DMARC policy is set to reject or quarantine",
            description="DMARC policy is set to reject or quarantine.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_phishing_protection",
            title="Advanced phishing and malware protections are configured",
            description="Advanced phishing and malware protections are configured.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_spf_configured",
            title="SPF record is configured for the domain",
            description="SPF record is configured for the domain.",
            severity="high",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_email_spf_strict",
            title="SPF record uses strict fail (-all) policy",
            description="SPF record uses strict fail (-all) policy.",
            severity="medium",
            provider="google_workspace",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="gws_less_secure_apps_disabled",
            title="Less secure app access is disabled",
            description="Less secure app access is disabled.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_login_challenges_enabled",
            title="Login challenges are enabled for suspicious sign-ins",
            description="Login challenges are enabled for suspicious sign-ins.",
            severity="medium",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_password_policy_strength",
            title="Password policy requires minimum 12 characters",
            description="Password policy requires minimum 12 characters.",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_security_keys_admins",
            title="Security keys are required for admin accounts",
            description="Security keys are required for admin accounts.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_sso_configured",
            title="Single Sign-On (SSO) is configured",
            description="Single Sign-On (SSO) is configured.",
            severity="high",
            provider="google_workspace",
            service="security",
            category="Compliance",
            tags=["security"],
        ),
        CheckDefinition(
            check_id="gws_super_admin_minimal",
            title="Super admin accounts are minimized (2-3 recommended)",
            description="Super admin accounts are minimized (2-3 recommended).",
            severity="critical",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_suspended_accounts_reviewed",
            title="Suspended accounts are reviewed and cleaned up",
            description="Suspended accounts are reviewed and cleaned up.",
            severity="low",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="gws_user_2fa_enrolled",
            title="User is enrolled in 2-step verification",
            description="User is enrolled in 2-step verification.",
            severity="high",
            provider="google_workspace",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
    ]
