"""Check definitions for Kubernetes.

Auto-generated from kubernetes scanner. 17 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Kubernetes check definitions."""
    return [
        CheckDefinition(
            check_id="k8s_admission_pod_security",
            title="Namespace has Pod Security Standards (PSA) enforce label",
            description="Namespace has Pod Security Standards (PSA) enforce label.",
            severity="high",
            provider="kubernetes",
            service="admission",
            category="Compliance",
            tags=["admission"],
        ),
        CheckDefinition(
            check_id="k8s_api_audit_logging",
            title="API server has audit logging enabled",
            description="API server has audit logging enabled.",
            severity="high",
            provider="kubernetes",
            service="apiserver",
            category="Compliance",
            tags=["apiserver", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="k8s_api_tls_enabled",
            title="API server has TLS enabled",
            description="API server has TLS enabled.",
            severity="critical",
            provider="kubernetes",
            service="apiserver",
            category="Compliance",
            tags=["apiserver", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="k8s_namespace_limit_ranges",
            title="Namespace has LimitRange defined",
            description="Namespace has LimitRange defined.",
            severity="low",
            provider="kubernetes",
            service="namespaces",
            category="Compliance",
            tags=["namespaces"],
        ),
        CheckDefinition(
            check_id="k8s_namespace_network_policy",
            title="Namespace has network policies",
            description="Namespace has network policies.",
            severity="medium",
            provider="kubernetes",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="k8s_namespace_resource_quotas",
            title="Namespace has resource quotas defined",
            description="Namespace has resource quotas defined.",
            severity="medium",
            provider="kubernetes",
            service="namespaces",
            category="Compliance",
            tags=["namespaces"],
        ),
        CheckDefinition(
            check_id="k8s_network_deny_all_default",
            title="Namespace has a default deny-all network policy",
            description="Namespace has a default deny-all network policy.",
            severity="medium",
            provider="kubernetes",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="k8s_network_ingress_rules",
            title="Network policy ingress rule specifies source restrictions",
            description="Network policy ingress rule specifies source restrictions.",
            severity="medium",
            provider="kubernetes",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="k8s_no_pods_in_default",
            title="No workload pods in default namespace",
            description="No workload pods in default namespace.",
            severity="medium",
            provider="kubernetes",
            service="namespaces",
            category="Compliance",
            tags=["namespaces"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_limit_secrets_access",
            title="ClusterRole limits access to secrets",
            description="ClusterRole limits access to secrets.",
            severity="high",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_no_default_sa_token",
            title="Default service account token auto-mount is disabled",
            description="Default service account token auto-mount is disabled.",
            severity="medium",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_no_wildcard_cluster_admin",
            title="cluster-admin not bound to broad groups",
            description="cluster-admin not bound to broad groups.",
            severity="critical",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_no_wildcard_verbs",
            title="ClusterRole does not use wildcard verbs on all resources",
            description="ClusterRole does not use wildcard verbs on all resources.",
            severity="high",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_secrets_encrypted_etcd",
            title="Secrets encryption at rest is configured for etcd",
            description="Secrets encryption at rest is configured for etcd.",
            severity="high",
            provider="kubernetes",
            service="secrets",
            category="Container",
            tags=["secrets", "encryption"],
        ),
        CheckDefinition(
            check_id="k8s_secrets_no_env_vars",
            title="Secrets are not exposed as environment variables",
            description="Secrets are not exposed as environment variables.",
            severity="medium",
            provider="kubernetes",
            service="secrets",
            category="Container",
            tags=["secrets"],
        ),
        CheckDefinition(
            check_id="k8s_service_no_loadbalancer_public",
            title="LoadBalancer service is not publicly exposed",
            description="LoadBalancer service is not publicly exposed.",
            severity="high",
            provider="kubernetes",
            service="services",
            category="Compliance",
            tags=["services", "public-access"],
        ),
        CheckDefinition(
            check_id="k8s_service_no_nodeport",
            title="Service does not use NodePort type",
            description="Service does not use NodePort type.",
            severity="medium",
            provider="kubernetes",
            service="services",
            category="Compliance",
            tags=["services"],
        ),
        # --- Supplementary: MITRE/RR orphan resolution ---
        CheckDefinition(
            check_id="k8s_image_pull_policy_always",
            title="Container image pull policy is set to Always",
            description="Container image pull policy is set to Always.",
            severity="medium",
            provider="kubernetes",
            service="workloads",
            category="Container",
            scanner_check_ids=["k8s_image_pull_policy_always"],
            source="scanner",
            tags=["container", "images", "supply-chain"],
        ),
        CheckDefinition(
            check_id="k8s_no_automount_sa_token",
            title="Service account token is not auto-mounted",
            description="Service account token is not auto-mounted.",
            severity="high",
            provider="kubernetes",
            service="workloads",
            category="Identity",
            scanner_check_ids=["k8s_no_automount_sa_token"],
            source="scanner",
            tags=["identity", "service-accounts"],
        ),
        CheckDefinition(
            check_id="k8s_no_host_network",
            title="Pod does not use host network namespace",
            description="Pod does not use host network namespace.",
            severity="high",
            provider="kubernetes",
            service="workloads",
            category="Container",
            scanner_check_ids=["k8s_no_host_network"],
            source="scanner",
            tags=["container", "host-isolation"],
        ),
        CheckDefinition(
            check_id="k8s_no_host_pid",
            title="Pod does not use host PID namespace",
            description="Pod does not use host PID namespace.",
            severity="high",
            provider="kubernetes",
            service="workloads",
            category="Container",
            scanner_check_ids=["k8s_no_host_pid"],
            source="scanner",
            tags=["container", "host-isolation"],
        ),
        CheckDefinition(
            check_id="k8s_no_privileged_containers",
            title="Container does not run in privileged mode",
            description="Container does not run in privileged mode.",
            severity="critical",
            provider="kubernetes",
            service="workloads",
            category="Container",
            scanner_check_ids=["k8s_no_privileged_containers"],
            source="scanner",
            tags=["container", "privilege-escalation"],
        ),
        CheckDefinition(
            check_id="k8s_resource_limits_set",
            title="Pod has CPU and memory resource limits set",
            description="Pod has CPU and memory resource limits set.",
            severity="medium",
            provider="kubernetes",
            service="workloads",
            category="Container",
            scanner_check_ids=["k8s_resource_limits_set"],
            source="scanner",
            tags=["container", "resource-management"],
        ),
    ]
