"""Check definitions for Kubernetes.

Auto-generated from kubernetes scanner. 17 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Kubernetes check definitions."""
    return [
        CheckDefinition(
            check_id="k8s_admission_pod_security",
            title="Namespace has Pod Security Standards (PSA) enforce label",
            description="Namespace has Pod Security Standards (PSA) enforce label.",
            severity="high",
            provider="kubernetes",
            service="admission",
            category="Compliance",
            tags=["admission"],
        ),
        CheckDefinition(
            check_id="k8s_api_audit_logging",
            title="API server has audit logging enabled",
            description="API server has audit logging enabled.",
            severity="high",
            provider="kubernetes",
            service="apiserver",
            category="Compliance",
            tags=["apiserver", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="k8s_api_tls_enabled",
            title="API server has TLS enabled",
            description="API server has TLS enabled.",
            severity="critical",
            provider="kubernetes",
            service="apiserver",
            category="Compliance",
            tags=["apiserver", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="k8s_namespace_limit_ranges",
            title="Namespace has LimitRange defined",
            description="Namespace has LimitRange defined.",
            severity="low",
            provider="kubernetes",
            service="namespaces",
            category="Compliance",
            tags=["namespaces"],
        ),
        CheckDefinition(
            check_id="k8s_namespace_network_policy",
            title="Namespace has network policies",
            description="Namespace has network policies.",
            severity="medium",
            provider="kubernetes",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="k8s_namespace_resource_quotas",
            title="Namespace has resource quotas defined",
            description="Namespace has resource quotas defined.",
            severity="medium",
            provider="kubernetes",
            service="namespaces",
            category="Compliance",
            tags=["namespaces"],
        ),
        CheckDefinition(
            check_id="k8s_network_deny_all_default",
            title="Namespace has a default deny-all network policy",
            description="Namespace has a default deny-all network policy.",
            severity="medium",
            provider="kubernetes",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="k8s_network_ingress_rules",
            title="Network policy ingress rule specifies source restrictions",
            description="Network policy ingress rule specifies source restrictions.",
            severity="medium",
            provider="kubernetes",
            service="network",
            category="Networking",
            tags=["network"],
        ),
        CheckDefinition(
            check_id="k8s_no_pods_in_default",
            title="No workload pods in default namespace",
            description="No workload pods in default namespace.",
            severity="medium",
            provider="kubernetes",
            service="namespaces",
            category="Compliance",
            tags=["namespaces"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_limit_secrets_access",
            title="ClusterRole limits access to secrets",
            description="ClusterRole limits access to secrets.",
            severity="high",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_no_default_sa_token",
            title="Default service account token auto-mount is disabled",
            description="Default service account token auto-mount is disabled.",
            severity="medium",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_no_wildcard_cluster_admin",
            title="cluster-admin not bound to broad groups",
            description="cluster-admin not bound to broad groups.",
            severity="critical",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_rbac_no_wildcard_verbs",
            title="ClusterRole does not use wildcard verbs on all resources",
            description="ClusterRole does not use wildcard verbs on all resources.",
            severity="high",
            provider="kubernetes",
            service="rbac",
            category="Compliance",
            tags=["rbac"],
        ),
        CheckDefinition(
            check_id="k8s_secrets_encrypted_etcd",
            title="Secrets encryption at rest is configured for etcd",
            description="Secrets encryption at rest is configured for etcd.",
            severity="high",
            provider="kubernetes",
            service="secrets",
            category="Container",
            tags=["secrets", "encryption"],
        ),
        CheckDefinition(
            check_id="k8s_secrets_no_env_vars",
            title="Secrets are not exposed as environment variables",
            description="Secrets are not exposed as environment variables.",
            severity="medium",
            provider="kubernetes",
            service="secrets",
            category="Container",
            tags=["secrets"],
        ),
        CheckDefinition(
            check_id="k8s_service_no_loadbalancer_public",
            title="LoadBalancer service is not publicly exposed",
            description="LoadBalancer service is not publicly exposed.",
            severity="high",
            provider="kubernetes",
            service="services",
            category="Compliance",
            tags=["services", "public-access"],
        ),
        CheckDefinition(
            check_id="k8s_service_no_nodeport",
            title="Service does not use NodePort type",
            description="Service does not use NodePort type.",
            severity="medium",
            provider="kubernetes",
            service="services",
            category="Compliance",
            tags=["services"],
        ),
    ]
