"""Check definitions for Microsoft 365.

Expanded registry: 103 checks covering CIS M365 v6.0.1 + supplementary scanner checks.
Organized by service section with enriched metadata.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Microsoft 365 check definitions."""
    return [
        # =====================================================================
        # Section 1 - Admin Center / Identity & Authentication (~20 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_cis_admin_cloud_only",
            title="Administrative accounts are cloud-only (CIS 1.1.1)",
            description="Privileged admin accounts must be cloud-only, not synced from on-prem AD.",
            severity="critical",
            provider="m365",
            service="admin_center",
            category="Identity",
            cis_id="1.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Ensure all admin accounts are created directly in Entra ID and not synced from on-premises Active Directory.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-6", "SOC2-CC6.1"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["admin_center", "identity"],
        ),
        CheckDefinition(
            check_id="m365_admin_mfa_enforced",
            title="MFA is enforced for all admin accounts",
            description="All admin accounts must have MFA enabled with phishing-resistant methods.",
            severity="critical",
            provider="m365",
            service="identity",
            category="Identity",
            cis_id="1.1.2",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable MFA for all administrative accounts via Conditional Access or Security Defaults.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-IA-2", "SOC2-CC6.1"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["identity", "mfa"],
        ),
        CheckDefinition(
            check_id="m365_user_mfa_registered",
            title="User has MFA method registered",
            description="All users should have at least one MFA authentication method registered.",
            severity="high",
            provider="m365",
            service="aad_users",
            category="Identity",
            cis_id="1.1.2",
            cis_level="L1",
            cis_profile="E3",
            remediation="Require users to register MFA methods through the authentication methods registration campaign.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-IA-2"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["aad_users", "mfa"],
        ),
        CheckDefinition(
            check_id="m365_user_phishing_resistant_mfa",
            title="User has phishing-resistant MFA (FIDO2/Windows Hello)",
            description="Users should use phishing-resistant MFA methods like FIDO2 or Windows Hello.",
            severity="medium",
            provider="m365",
            service="aad_users",
            category="Identity",
            cis_id="1.1.2",
            cis_level="L2",
            cis_profile="E5",
            remediation="Deploy FIDO2 security keys or Windows Hello for Business for phishing-resistant authentication.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-IA-2(6)"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["aad_users", "mfa"],
        ),
        CheckDefinition(
            check_id="m365_security_defaults_enabled",
            title="Security defaults are enabled (or equivalent CA policies exist)",
            description="Security defaults or equivalent Conditional Access policies must be configured.",
            severity="high",
            provider="m365",
            service="identity",
            category="Identity",
            cis_id="1.1.3",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable Security Defaults in Entra ID or configure equivalent Conditional Access policies.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-2"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_ca_require_mfa",
            title="MFA is required by Conditional Access",
            description="Conditional Access policies must require MFA for all users.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Identity",
            cis_id="1.1.4",
            cis_level="L1",
            cis_profile="E3",
            remediation="Create a Conditional Access policy requiring MFA for all users and cloud apps.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-IA-2"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["conditional_access", "mfa"],
        ),
        CheckDefinition(
            check_id="m365_ca_sign_in_risk",
            title="Sign-in risk-based policy is configured",
            description="Conditional Access must evaluate sign-in risk for adaptive authentication.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Identity",
            cis_id="1.1.4",
            cis_level="L2",
            cis_profile="E5",
            remediation="Configure sign-in risk evaluation in Conditional Access policies with Entra ID P2.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-IA-2"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_ca_require_compliant_device",
            title="Compliant device requirement exists",
            description="Conditional Access requires device compliance for resource access.",
            severity="medium",
            provider="m365",
            service="conditional_access",
            category="Identity",
            cis_id="1.1.5",
            cis_level="L2",
            cis_profile="E3",
            remediation="Create a Conditional Access policy requiring device compliance or Hybrid Azure AD join.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-19"],
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_ca_block_legacy_auth",
            title="Legacy authentication is blocked via CA",
            description="Conditional Access blocks legacy authentication protocols that cannot enforce MFA.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Identity",
            cis_id="1.1.6",
            cis_level="L1",
            cis_profile="E3",
            remediation="Create a Conditional Access policy that blocks legacy authentication for all users.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-17"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_legacy_auth_blocked",
            title="Legacy authentication protocols are blocked tenant-wide",
            description="Legacy authentication protocols are blocked at the tenant level.",
            severity="high",
            provider="m365",
            service="identity",
            category="Identity",
            cis_id="1.1.6",
            cis_level="L1",
            cis_profile="E3",
            remediation="Disable legacy authentication protocols tenant-wide via Authentication Methods policy.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-17"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_ca_policies_configured",
            title="Conditional Access policies are configured and enabled",
            description="At least one Conditional Access policy is configured and in report-only or enabled state.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Identity",
            cis_id="1.1.3",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure Conditional Access policies in Entra ID to enforce authentication requirements.",
            compliance_mappings=["CIS-M365-6.0.1"],
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_cis_shared_mailbox_signin_blocked",
            title="Sign-in to shared mailboxes is blocked (CIS 1.2.1)",
            description="Shared mailboxes must have direct sign-in blocked to prevent MFA bypass.",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Identity",
            cis_id="1.2.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Block sign-in for all shared mailbox accounts in Entra ID user properties.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-2"],
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_privileged_accounts_limited",
            title="Global Administrator accounts are limited (5 or fewer)",
            description="Limit Global Administrator role assignments to reduce attack surface.",
            severity="high",
            provider="m365",
            service="identity",
            category="Identity",
            cis_id="1.2.2",
            cis_level="L1",
            cis_profile="E3",
            remediation="Review and reduce the number of Global Administrators to 5 or fewer. Use least-privilege admin roles.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-6(5)"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_no_high_risk_users",
            title="No high-risk users detected",
            description="Monitor and remediate users flagged as high risk by Entra ID Protection.",
            severity="critical",
            provider="m365",
            service="aad_users",
            category="Identity",
            cis_id="1.2.3",
            cis_level="L1",
            cis_profile="E5",
            remediation="Investigate and remediate high-risk users in Entra ID Protection. Reset passwords and revoke sessions.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-4"],
            rr_relevant=True,
            rr_domains=["D1", "D2"],
            tags=["aad_users"],
        ),
        CheckDefinition(
            check_id="m365_cis_idle_session_timeout",
            title="Idle session timeout <=3 hours for unmanaged devices (CIS 1.3.1)",
            description="Browser sessions on unmanaged devices must have an idle timeout of 3 hours or less.",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Identity",
            cis_id="1.3.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure idle session timeout to 3 hours or less in Microsoft 365 admin center for unmanaged devices.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-12"],
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_password_never_expire_disabled",
            title="Password expiration policy is set to not expire",
            description="Passwords should not expire; rely on MFA and breach detection instead.",
            severity="medium",
            provider="m365",
            service="identity",
            category="Identity",
            cis_id="1.3.2",
            cis_level="L1",
            cis_profile="E3",
            remediation="Set password policy to never expire. Use MFA and Azure AD Password Protection instead.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-63B"],
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_self_service_password_reset",
            title="Self-service password reset is enabled",
            description="Enable SSPR to reduce helpdesk calls and improve security posture.",
            severity="medium",
            provider="m365",
            service="identity",
            category="Identity",
            cis_id="1.3.3",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable Self-Service Password Reset for all users in Entra ID.",
            compliance_mappings=["CIS-M365-6.0.1"],
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_emergency_access_accounts",
            title="Emergency access (break-glass) accounts exist",
            description="At least two emergency access accounts should exist for disaster recovery.",
            severity="critical",
            provider="m365",
            service="identity",
            category="Identity",
            cis_level="L1",
            cis_profile="E3",
            assessment_type="manual",
            remediation="Create at least two cloud-only emergency access accounts excluded from Conditional Access policies.",
            compliance_mappings=["NIST-800-53-AC-2(2)", "SOC2-CC6.1"],
            rr_relevant=True,
            rr_domains=["D1", "D7"],
            source="scanner",
            tags=["identity", "emergency"],
        ),
        CheckDefinition(
            check_id="m365_password_protection_enabled",
            title="Azure AD Password Protection is enabled",
            description="Azure AD Password Protection enforces banned password lists.",
            severity="high",
            provider="m365",
            service="identity",
            category="Identity",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable Azure AD Password Protection with custom banned password list in Entra ID.",
            compliance_mappings=["NIST-800-63B", "SOC2-CC6.1"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_group_creation_restricted",
            title="Group creation is restricted to admins",
            description="Only administrators should be able to create Microsoft 365 groups.",
            severity="medium",
            provider="m365",
            service="identity",
            category="Governance",
            cis_level="L2",
            cis_profile="E3",
            remediation="Restrict Microsoft 365 group creation to a designated security group of administrators.",
            compliance_mappings=["NIST-800-53-AC-6"],
            source="scanner",
            tags=["identity", "governance"],
        ),
        CheckDefinition(
            check_id="m365_user_risk_policy_configured",
            title="User risk-based Conditional Access policy is configured",
            description="A CA policy should evaluate user risk and require password change or block for high-risk users.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Identity",
            cis_level="L2",
            cis_profile="E5",
            remediation="Create a Conditional Access policy that requires password change when user risk is high.",
            compliance_mappings=["NIST-800-53-IA-2", "SOC2-CC6.1"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_named_locations_configured",
            title="Named/trusted locations are configured in Conditional Access",
            description="Define trusted locations for location-based Conditional Access policies.",
            severity="medium",
            provider="m365",
            service="conditional_access",
            category="Identity",
            cis_level="L2",
            cis_profile="E3",
            remediation="Configure named locations in Entra ID Conditional Access for trusted IP ranges and countries.",
            compliance_mappings=["NIST-800-53-AC-2"],
            source="scanner",
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_consent_workflow_enabled",
            title="Admin consent workflow is enabled for apps",
            description="Users should request admin approval instead of self-consenting to app permissions.",
            severity="high",
            provider="m365",
            service="identity",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable the admin consent workflow in Entra ID Enterprise Applications settings.",
            compliance_mappings=["NIST-800-53-AC-6", "SOC2-CC6.1"],
            source="scanner",
            tags=["identity", "governance"],
        ),
        CheckDefinition(
            check_id="m365_app_registration_restricted",
            title="App registration is restricted to admins",
            description="Only admins should be able to register applications in Entra ID.",
            severity="high",
            provider="m365",
            service="identity",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Set 'Users can register applications' to No in Entra ID User Settings.",
            compliance_mappings=["NIST-800-53-CM-7", "SOC2-CC6.1"],
            source="scanner",
            tags=["identity", "governance"],
        ),
        CheckDefinition(
            check_id="m365_guest_expiration_configured",
            title="Guest access expiration is configured",
            description="Guest user access should have expiration policies to prevent stale external access.",
            severity="medium",
            provider="m365",
            service="identity",
            category="Governance",
            cis_level="L2",
            cis_profile="E5",
            remediation="Configure guest access reviews and expiration policies in Entra ID Identity Governance.",
            compliance_mappings=["NIST-800-53-AC-2(3)", "SOC2-CC6.1"],
            source="scanner",
            tags=["identity", "governance"],
        ),
        # =====================================================================
        # Section 2 - Microsoft Defender (~14 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_cis_anti_phishing_advanced",
            title="Anti-phishing policy with aggressive settings (CIS 2.1.1)",
            description="Anti-phishing policies must set phish threshold, enable impersonation protection, and honor DMARC.",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Threat Detection",
            cis_id="2.1.1",
            cis_level="L1",
            cis_profile="E5",
            remediation="Configure anti-phishing policies with advanced phishing threshold >=2 and impersonation protection enabled.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-8"],
            rr_relevant=True,
            rr_domains=["D2"],
            tags=["admin_center", "email_security"],
        ),
        CheckDefinition(
            check_id="m365_anti_phishing_policy",
            title="Anti-phishing policy is configured",
            description="At least one anti-phishing policy is configured and enabled.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Threat Detection",
            cis_id="2.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Create and enable an anti-phishing policy in Microsoft Defender for Office 365.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-8"],
            rr_relevant=True,
            rr_domains=["D2"],
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_safe_attachments_enabled",
            title="Safe Attachments policy is enabled",
            description="Enable Safe Attachments in Exchange Online Protection to scan email attachments.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Threat Detection",
            cis_id="2.1.2",
            cis_level="L1",
            cis_profile="E5",
            remediation="Enable Safe Attachments with Dynamic Delivery in Defender for Office 365.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-3"],
            rr_relevant=True,
            rr_domains=["D2"],
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_safe_links_enabled",
            title="Safe Links policy is enabled",
            description="Enable Safe Links to protect users from malicious URLs in email and documents.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Threat Detection",
            cis_id="2.1.3",
            cis_level="L1",
            cis_profile="E5",
            remediation="Enable Safe Links for email and Microsoft Teams in Defender for Office 365.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-3"],
            rr_relevant=True,
            rr_domains=["D2"],
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_defender_sensor_active",
            title="Defender sensor is active on machine",
            description="Microsoft Defender for Endpoint sensor is active and reporting.",
            severity="high",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            cis_id="2.2.1",
            cis_level="L1",
            cis_profile="E5",
            remediation="Ensure Defender for Endpoint agent is deployed and active on all managed devices.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-3"],
            rr_relevant=True,
            rr_domains=["D2", "D5"],
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_defender_low_exposure",
            title="Machine exposure level is low or none",
            description="Defender for Endpoint reports machine exposure level as low or none.",
            severity="high",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            cis_id="2.2.1",
            cis_level="L1",
            cis_profile="E5",
            remediation="Remediate vulnerabilities identified by Defender for Endpoint to reduce exposure level.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-RA-5"],
            rr_relevant=True,
            rr_domains=["D2", "D5"],
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_defender_low_risk",
            title="Machine risk score is low or none",
            description="Defender for Endpoint reports machine risk score as low or none.",
            severity="critical",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            cis_id="2.2.1",
            cis_level="L1",
            cis_profile="E5",
            remediation="Investigate and remediate active alerts to reduce machine risk score.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-4"],
            rr_relevant=True,
            rr_domains=["D2", "D5"],
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_cis_defender_cloud_apps",
            title="Defender for Cloud Apps is connected (CIS 2.4.1)",
            description="Defender for Cloud Apps must be connected for shadow IT discovery.",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Threat Detection",
            cis_id="2.4.1",
            cis_level="L2",
            cis_profile="E5",
            remediation="Connect Microsoft Defender for Cloud Apps for shadow IT discovery and anomaly detection.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-4"],
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_defender_safe_docs_enabled",
            title="Safe Documents is enabled for Office clients",
            description="Safe Documents scans documents opened in Protected View before allowing editing.",
            severity="medium",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            cis_level="L2",
            cis_profile="E5",
            remediation="Enable Safe Documents in Microsoft 365 Defender settings.",
            compliance_mappings=["NIST-800-53-SI-3"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_defender_impersonation_protection",
            title="Impersonation protection is configured",
            description="Anti-phishing impersonation protection covers key users and domains.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Threat Detection",
            cis_level="L1",
            cis_profile="E5",
            remediation="Add VIPs and custom domains to impersonation protection in anti-phishing policy.",
            compliance_mappings=["NIST-800-53-SI-8"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_defender_auto_investigation",
            title="Automated investigation and response is enabled",
            description="Enable AIR to automatically investigate and remediate threats.",
            severity="medium",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            cis_level="L2",
            cis_profile="E5",
            remediation="Enable Automated Investigation and Response (AIR) in Microsoft 365 Defender.",
            compliance_mappings=["NIST-800-53-IR-4"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_defender_alert_policies",
            title="Alert policies are configured for anomalous activities",
            description="Custom alert policies detect suspicious behavior beyond defaults.",
            severity="medium",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            cis_level="L1",
            cis_profile="E3",
            remediation="Review and configure alert policies in Microsoft 365 Defender for key threat scenarios.",
            compliance_mappings=["NIST-800-53-SI-4"],
            source="scanner",
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_defender_quarantine_policies",
            title="Quarantine policies are reviewed and configured",
            description="Quarantine policies control user access to quarantined messages.",
            severity="low",
            provider="m365",
            service="email_security",
            category="Threat Detection",
            cis_level="L2",
            cis_profile="E3",
            remediation="Review quarantine policies and ensure appropriate notification and release settings.",
            compliance_mappings=["NIST-800-53-SI-8"],
            source="scanner",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_zero_hour_purge_enabled",
            title="Zero-hour auto purge (ZAP) is enabled",
            description="ZAP retroactively detects and neutralizes malicious messages already delivered.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Threat Detection",
            cis_level="L1",
            cis_profile="E3",
            remediation="Ensure ZAP is enabled for spam, phishing, and malware in Exchange Online Protection.",
            compliance_mappings=["NIST-800-53-SI-3"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["email_security"],
        ),
        # =====================================================================
        # Section 3 - Microsoft Purview / Compliance (~12 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_cis_audit_log_enabled",
            title="Microsoft 365 audit log search is enabled (CIS 3.1.1)",
            description="UnifiedAuditLogIngestionEnabled must be True for incident investigation.",
            severity="critical",
            provider="m365",
            service="admin_center",
            category="Compliance",
            cis_id="3.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable audit log search in Microsoft Purview compliance portal.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AU-2", "SOC2-CC7.2"],
            rr_relevant=True,
            rr_domains=["D3"],
            tags=["admin_center", "audit"],
        ),
        CheckDefinition(
            check_id="m365_cis_dlp_policies_enabled",
            title="DLP policies are enabled in Microsoft Purview (CIS 3.2.1)",
            description="Data Loss Prevention policies must detect and prevent exfiltration of sensitive data.",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            cis_id="3.2.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Create and enable DLP policies in Microsoft Purview for sensitive information types.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SC-7", "SOC2-CC6.7"],
            dspm_relevant=True,
            dspm_categories=["data_classification", "dlp"],
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_dlp_policies_configured",
            title="Data Loss Prevention policies are configured",
            description="DLP policies exist and are actively enforcing data protection rules.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            cis_id="3.2.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure DLP policies with appropriate sensitive information types and actions.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SC-7"],
            dspm_relevant=True,
            dspm_categories=["data_classification", "dlp"],
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_cis_sensitivity_labels_published",
            title="Sensitivity label policies are published (CIS 3.3.1)",
            description="Sensitivity labels must be created and published for document/email classification.",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            cis_id="3.3.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Create and publish sensitivity labels in Microsoft Purview Information Protection.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-16"],
            dspm_relevant=True,
            dspm_categories=["data_classification"],
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_sensitivity_labels_enabled",
            title="Sensitivity labels are configured and published",
            description="Sensitivity labels exist for classifying and protecting organizational data.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            cis_id="3.3.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure sensitivity labels with encryption and content marking in Microsoft Purview.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-16"],
            dspm_relevant=True,
            dspm_categories=["data_classification"],
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_aip_encryption_enabled",
            title="Azure Information Protection encryption labels exist",
            description="AIP encryption labels protect sensitive content with rights management.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            cis_id="3.3.2",
            cis_level="L2",
            cis_profile="E5",
            remediation="Create sensitivity labels with encryption enabled using Azure Information Protection.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SC-28"],
            dspm_relevant=True,
            dspm_categories=["encryption"],
            tags=["data_protection", "encryption"],
        ),
        CheckDefinition(
            check_id="m365_purview_retention_policies",
            title="Retention policies are configured",
            description="Data retention policies ensure regulatory compliance and prevent premature deletion.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure retention policies in Microsoft Purview for Exchange, SharePoint, and Teams.",
            compliance_mappings=["NIST-800-53-AU-11", "SOC2-CC7.4"],
            dspm_relevant=True,
            dspm_categories=["data_retention"],
            rr_relevant=True,
            rr_domains=["D3", "D6"],
            source="scanner",
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_purview_audit_premium",
            title="Audit (Premium) is enabled for advanced investigation",
            description="Audit Premium provides extended log retention and high-value audit events.",
            severity="medium",
            provider="m365",
            service="admin_center",
            category="Compliance",
            cis_level="L2",
            cis_profile="E5",
            remediation="Enable Microsoft Purview Audit (Premium) for 1-year log retention and crucial events.",
            compliance_mappings=["NIST-800-53-AU-11"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["admin_center", "audit"],
        ),
        CheckDefinition(
            check_id="m365_audit_log_retention",
            title="Audit log retention is at least 90 days",
            description="Audit logs must be retained for at least 90 days for forensic investigation.",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure audit log retention policy to at least 90 days in Microsoft Purview.",
            compliance_mappings=["NIST-800-53-AU-11", "SOC2-CC7.2"],
            rr_relevant=True,
            rr_domains=["D3"],
            source="scanner",
            tags=["admin_center", "audit"],
        ),
        CheckDefinition(
            check_id="m365_purview_insider_risk",
            title="Insider risk management policies are configured",
            description="Insider risk policies detect and respond to internal threats.",
            severity="medium",
            provider="m365",
            service="data_protection",
            category="Compliance",
            cis_level="L2",
            cis_profile="E5",
            assessment_type="manual",
            remediation="Configure insider risk management policies in Microsoft Purview.",
            compliance_mappings=["NIST-800-53-PM-12"],
            source="scanner",
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_purview_info_barriers",
            title="Information barriers are configured where needed",
            description="Information barriers prevent unauthorized communication between groups.",
            severity="medium",
            provider="m365",
            service="data_protection",
            category="Compliance",
            cis_level="L2",
            cis_profile="E5",
            assessment_type="manual",
            remediation="Configure information barrier policies in Microsoft Purview for regulated departments.",
            compliance_mappings=["NIST-800-53-AC-4"],
            dspm_relevant=True,
            dspm_categories=["access_control"],
            source="scanner",
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_purview_ediscovery_restricted",
            title="eDiscovery access is restricted to authorized users",
            description="eDiscovery Manager/Admin roles should be limited to authorized personnel.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            assessment_type="manual",
            remediation="Review and limit eDiscovery role assignments in Microsoft Purview.",
            compliance_mappings=["NIST-800-53-AC-6(5)"],
            source="scanner",
            tags=["data_protection", "governance"],
        ),
        # =====================================================================
        # Section 4 - Intune / Device Management (~9 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_cis_device_compliance_secure",
            title="Device compliance marks noncompliant devices by default (CIS 4.1)",
            description="Intune must mark devices without a compliance policy as noncompliant.",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_id="4.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Set secureByDefault to True in Intune device compliance settings.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-CM-6"],
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_cis_personal_enrollment_blocked",
            title="Personal device enrollment is blocked (CIS 4.2)",
            description="BYOD enrollment should be restricted to prevent mixing corporate and personal data.",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_id="4.2",
            cis_level="L2",
            cis_profile="E3",
            remediation="Configure enrollment restrictions in Intune to block personal device enrollment.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-19"],
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_intune_app_protection",
            title="App protection policies are configured",
            description="Intune app protection policies (MAM) protect corporate data on mobile devices.",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure app protection policies for iOS and Android in Microsoft Intune.",
            compliance_mappings=["NIST-800-53-AC-19(5)"],
            dspm_relevant=True,
            dspm_categories=["data_protection"],
            source="scanner",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_intune_compliance_actions",
            title="Non-compliance actions are configured (block/wipe)",
            description="Automated actions for non-compliant devices must be defined.",
            severity="medium",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure actions for non-compliance in device compliance policies (notify, block, wipe).",
            compliance_mappings=["NIST-800-53-CM-6"],
            source="scanner",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_intune_disk_encryption",
            title="BitLocker/disk encryption is required",
            description="Device compliance policies must require disk encryption on managed devices.",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Require BitLocker encryption in Windows device compliance policies.",
            compliance_mappings=["NIST-800-53-SC-28"],
            rr_relevant=True,
            rr_domains=["D4"],
            source="scanner",
            tags=["intune_entra", "encryption"],
        ),
        CheckDefinition(
            check_id="m365_intune_config_profiles",
            title="Security configuration profiles are deployed",
            description="Security baselines and configuration profiles are deployed to managed devices.",
            severity="medium",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_level="L2",
            cis_profile="E3",
            assessment_type="manual",
            remediation="Deploy security baseline profiles in Intune for Windows, macOS, and mobile devices.",
            compliance_mappings=["NIST-800-53-CM-6"],
            source="scanner",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_intune_windows_update",
            title="Windows Update rings are configured",
            description="Update rings ensure timely patching of Windows devices.",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure Windows Update rings in Intune with appropriate deferral and deadline settings.",
            compliance_mappings=["NIST-800-53-SI-2"],
            rr_relevant=True,
            rr_domains=["D5"],
            source="scanner",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_intune_endpoint_protection",
            title="Endpoint protection profile is configured",
            description="Endpoint protection configuration profile ensures antivirus and firewall settings.",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Deploy endpoint protection profile with antivirus, firewall, and attack surface reduction rules.",
            compliance_mappings=["NIST-800-53-SI-3"],
            rr_relevant=True,
            rr_domains=["D2", "D5"],
            source="scanner",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_intune_conditional_launch",
            title="Conditional launch settings for mobile apps",
            description="App protection policies enforce conditional launch to block jailbroken/rooted devices.",
            severity="medium",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_level="L2",
            cis_profile="E3",
            remediation="Configure conditional launch settings in app protection policies for OS version and jailbreak detection.",
            compliance_mappings=["NIST-800-53-AC-19"],
            source="scanner",
            tags=["intune_entra"],
        ),
        # =====================================================================
        # Section 5 - Entra / Identity Governance (~4 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_cis_pim_approval_required",
            title="PIM requires approval for Privileged Role Administrator (CIS 5.3.1)",
            description="PIM must require an approval workflow for activating the Privileged Role Administrator role.",
            severity="critical",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_id="5.3.1",
            cis_level="L1",
            cis_profile="E5",
            remediation="Configure PIM to require approval for Global Admin and Privileged Role Admin activations.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-6(1)"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_cis_fabric_guest_restricted",
            title="Microsoft Fabric restricts guest user access",
            description="Guest user access to Microsoft Fabric is restricted.",
            severity="medium",
            provider="m365",
            service="intune_entra",
            category="Governance",
            cis_id="9.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Restrict guest access in Microsoft Fabric admin portal settings.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_guest_access_restricted",
            title="Guest invitation settings are restricted",
            description="Guest invitation settings limit who can invite external users.",
            severity="medium",
            provider="m365",
            service="data_protection",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Restrict guest invitation permissions to admins and users with the Guest Inviter role.",
            compliance_mappings=["NIST-800-53-AC-3"],
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_oauth_app_restrictions",
            title="OAuth app access is restricted",
            description="Third-party OAuth app consents are restricted to admin-approved applications.",
            severity="high",
            provider="m365",
            service="identity",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Set user consent to apps to 'Do not allow user consent' or allow only verified publishers.",
            compliance_mappings=["NIST-800-53-CM-7", "SOC2-CC6.1"],
            source="scanner",
            tags=["identity", "governance"],
        ),
        # =====================================================================
        # Section 6 - Exchange Online (~14 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_cis_mailbox_audit_enabled",
            title="Mailbox auditing is not disabled (CIS 6.1.1)",
            description="AuditDisabled must be False for all mailboxes for forensic investigation.",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_id="6.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Ensure mailbox auditing is enabled for all mailboxes (Set-OrganizationConfig -AuditDisabled $false).",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AU-2"],
            rr_relevant=True,
            rr_domains=["D3"],
            tags=["exchange_online", "audit"],
        ),
        CheckDefinition(
            check_id="m365_spf_configured",
            title="SPF record is configured for domain",
            description="SPF records prevent email spoofing by specifying authorized senders.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            cis_id="6.1.2",
            cis_level="L1",
            cis_profile="E3",
            remediation="Add an SPF TXT record for your domain: v=spf1 include:spf.protection.outlook.com -all.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-8"],
            rr_relevant=True,
            rr_domains=["D2"],
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_dkim_configured",
            title="DKIM is configured for domain",
            description="DKIM signing validates email integrity and prevents tampering.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            cis_id="6.1.3",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable DKIM signing in Exchange Online for all custom domains.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-8"],
            rr_relevant=True,
            rr_domains=["D2"],
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_dmarc_configured",
            title="DMARC record is configured for domain",
            description="DMARC provides email authentication reporting and policy enforcement.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            cis_id="6.1.4",
            cis_level="L1",
            cis_profile="E3",
            remediation="Add DMARC DNS record with p=quarantine or p=reject for your domain.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-8"],
            rr_relevant=True,
            rr_domains=["D2"],
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_cis_external_email_tagging",
            title="External email tagging is enabled (CIS 6.2.1)",
            description="ExternalInOutlook must be Enabled to help users identify phishing.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_id="6.2.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable external email tagging: Set-ExternalInOutlook -Enabled $true.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SI-8"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_outlook_addins_restricted",
            title="Users cannot install Outlook add-ins (CIS 6.3.1)",
            description="Restrict Outlook add-in installation to prevent unrestricted data access.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_id="6.3.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Block user installation of Outlook add-ins via Exchange admin center.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-CM-7"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_modern_auth_exchange",
            title="Modern authentication for Exchange Online is enabled (CIS 6.5.1)",
            description="OAuth 2.0 modern authentication must be enabled replacing deprecated basic auth.",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_id="6.5.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable modern authentication for Exchange Online (Set-OrganizationConfig -OAuth2ClientProfileEnabled $true).",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-IA-2"],
            rr_relevant=True,
            rr_domains=["D1"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_auto_forwarding_disabled",
            title="Auto-forwarding to external domains is disabled",
            description="Prevent automatic email forwarding to external addresses to stop data exfiltration.",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Create a transport rule or remote domain policy to block auto-forwarding to external domains.",
            compliance_mappings=["NIST-800-53-SC-7", "SOC2-CC6.7"],
            dspm_relevant=True,
            dspm_categories=["dlp"],
            rr_relevant=True,
            rr_domains=["D2", "D4"],
            source="scanner",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_transport_rules_reviewed",
            title="Exchange transport rules are reviewed",
            description="Transport rules should be reviewed to prevent unauthorized mail flow changes.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_level="L1",
            cis_profile="E3",
            assessment_type="manual",
            remediation="Review all transport rules in Exchange admin center and remove obsolete or suspicious rules.",
            compliance_mappings=["NIST-800-53-CA-7"],
            source="scanner",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_remote_powershell_restricted",
            title="Remote PowerShell access is restricted",
            description="Remote PowerShell should be disabled for non-admin users.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_level="L2",
            cis_profile="E3",
            remediation="Disable remote PowerShell for regular users (Set-User -RemotePowerShellEnabled $false).",
            compliance_mappings=["NIST-800-53-AC-6"],
            source="scanner",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_mailtips_enabled",
            title="MailTips for external recipients are enabled",
            description="MailTips warn users when sending to external recipients.",
            severity="low",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable MailTips for external recipients in Exchange Online organization config.",
            compliance_mappings=["NIST-800-53-SI-8"],
            source="scanner",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_common_attachment_filter",
            title="Common attachment types filter is enabled",
            description="Filter common malicious attachment types like .exe, .bat, .vbs, etc.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Threat Detection",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable and configure the common attachment types filter in Exchange Online Protection.",
            compliance_mappings=["NIST-800-53-SI-3"],
            rr_relevant=True,
            rr_domains=["D2"],
            source="scanner",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_journal_rules_configured",
            title="Journal rules are configured for compliance",
            description="Journal rules capture email for compliance and regulatory requirements.",
            severity="low",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_level="L2",
            cis_profile="E5",
            assessment_type="manual",
            remediation="Configure journal rules in Exchange Online for regulatory compliance where required.",
            compliance_mappings=["NIST-800-53-AU-2"],
            source="scanner",
            tags=["exchange_online"],
        ),
        # =====================================================================
        # Section 7 - SharePoint & OneDrive (~10 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_sharepoint_sharing_restricted",
            title="SharePoint sharing is restricted to existing guests or disabled",
            description="External sharing in SharePoint and OneDrive is restricted.",
            severity="high",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_id="7.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Set SharePoint external sharing to 'Existing guests' or more restrictive.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            dspm_relevant=True,
            dspm_categories=["access_control"],
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_external_sharing_restricted",
            title="External sharing is restricted (not open to anonymous)",
            description="External sharing does not allow anonymous access links.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            cis_id="7.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Disable 'Anyone' sharing links in SharePoint and OneDrive admin center.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            dspm_relevant=True,
            dspm_categories=["access_control"],
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_cis_sharepoint_default_link_view",
            title="SharePoint default sharing link permission is View (CIS 7.2.1)",
            description="Default sharing links should grant View (read-only) permission.",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_id="7.2.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Set default sharing link permission type to View in SharePoint admin center.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            dspm_relevant=True,
            dspm_categories=["access_control"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_onedrive_sync_domain_joined",
            title="OneDrive sync restricted to domain-joined computers (CIS 7.3.1)",
            description="OneDrive sync must be restricted to domain-joined or managed devices.",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            cis_id="7.3.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Restrict OneDrive sync to domain-joined or compliant devices in SharePoint admin center.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-19"],
            dspm_relevant=True,
            dspm_categories=["data_protection"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_onedrive_sync_restricted",
            title="OneDrive sync is restricted to managed devices",
            description="OneDrive desktop sync client only works on managed/compliant devices.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_id="7.3.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable 'Allow syncing only on PCs joined to specific domains' in OneDrive admin.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-19"],
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_sharepoint_legacy_auth_blocked",
            title="SharePoint legacy authentication is blocked",
            description="Legacy authentication for SharePoint Online is disabled.",
            severity="high",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L1",
            cis_profile="E3",
            remediation="Disable legacy authentication for SharePoint via Set-SPOTenant -LegacyAuthProtocolsEnabled $false.",
            compliance_mappings=["NIST-800-53-AC-17"],
            rr_relevant=True,
            rr_domains=["D1"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_sharepoint_access_control_unmanaged",
            title="Unmanaged device access is restricted for SharePoint",
            description="Access from unmanaged devices is limited to web-only or blocked.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L2",
            cis_profile="E3",
            remediation="Configure access control for unmanaged devices in SharePoint admin center.",
            compliance_mappings=["NIST-800-53-AC-19"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_sharepoint_resharing_restricted",
            title="Re-sharing by guests is restricted",
            description="External guests cannot re-share content with other external users.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L1",
            cis_profile="E3",
            remediation="Disable guest re-sharing in SharePoint admin center sharing settings.",
            compliance_mappings=["NIST-800-53-AC-3"],
            dspm_relevant=True,
            dspm_categories=["access_control"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_sharepoint_site_classification",
            title="Site classification/sensitivity is required",
            description="SharePoint sites must have a classification or sensitivity label assigned.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L2",
            cis_profile="E5",
            assessment_type="manual",
            remediation="Require sensitivity labels for Microsoft 365 groups and SharePoint sites.",
            compliance_mappings=["NIST-800-53-AC-16"],
            dspm_relevant=True,
            dspm_categories=["data_classification"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_onedrive_retention_configured",
            title="OneDrive retention policies are configured",
            description="Retention policies ensure OneDrive data is preserved per compliance requirements.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure OneDrive retention policies in Microsoft Purview.",
            compliance_mappings=["NIST-800-53-AU-11"],
            dspm_relevant=True,
            dspm_categories=["data_retention"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        # =====================================================================
        # Section 8 - Microsoft Teams (~12 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_cis_teams_email_disabled",
            title="Teams email channel integration is disabled (CIS 8.1.1)",
            description="AllowEmailIntoChannel must be False to prevent external email injection.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Collaboration",
            cis_id="8.1.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Disable Teams email channel integration in Teams admin center messaging policies.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-SC-7"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_teams_external_access_restricted",
            title="Teams external access is restricted",
            description="External access in Microsoft Teams is restricted to specific domains or disabled.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_id="8.1.2",
            cis_level="L1",
            cis_profile="E3",
            remediation="Restrict Teams external access to specific allowed domains or disable entirely.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_trial_blocked",
            title="External access with trial tenants is blocked (CIS 8.2.1)",
            description="ExternalAccessWithTrialTenants must be Blocked to prevent social engineering.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Collaboration",
            cis_id="8.2.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Block external access with trial tenants in Teams admin center.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_apps_restricted",
            title="Third-party and custom Teams apps are restricted (CIS 8.4.1)",
            description="Third-party and custom apps should be Off by default in Teams.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Collaboration",
            cis_id="8.4.1",
            cis_level="L2",
            cis_profile="E3",
            remediation="Block third-party and custom apps by default in Teams admin center.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-CM-7"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_external_control",
            title="External participants cannot give/request control (CIS 8.5.1)",
            description="AllowExternalParticipantGiveRequestControl must be False.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Collaboration",
            cis_id="8.5.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Disable external participant control sharing in Teams meeting policies.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_recording_off",
            title="Meeting recording is Off by default (CIS 8.5.8)",
            description="AllowCloudRecording should be False to prevent automatic recording of sensitive meetings.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Collaboration",
            cis_id="8.5.8",
            cis_level="L2",
            cis_profile="E3",
            remediation="Set AllowCloudRecording to False in Teams meeting policy.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-AC-3"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_security_reporting",
            title="Users can report security concerns in Teams (CIS 8.6.1)",
            description="AllowSecurityEndUserReporting must be True for phishing and suspicious content.",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Collaboration",
            cis_id="8.6.1",
            cis_level="L1",
            cis_profile="E3",
            remediation="Enable AllowSecurityEndUserReporting in Teams messaging policy.",
            compliance_mappings=["CIS-M365-6.0.1", "NIST-800-53-IR-6"],
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_teams_meeting_lobby",
            title="Anonymous users must wait in the lobby",
            description="Anonymous and external users must wait in the lobby before joining meetings.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L1",
            cis_profile="E3",
            remediation="Configure meeting policy to require lobby for anonymous and external users.",
            compliance_mappings=["NIST-800-53-AC-3"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_teams_anonymous_join_disabled",
            title="Anonymous users cannot join meetings",
            description="Anonymous users should not be able to join Teams meetings without authentication.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L2",
            cis_profile="E3",
            remediation="Disable anonymous join in Teams meeting policies.",
            compliance_mappings=["NIST-800-53-AC-3"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_teams_dial_in_bypass_disabled",
            title="Dial-in users cannot bypass the lobby",
            description="Users joining by phone must wait in the lobby.",
            severity="low",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L2",
            cis_profile="E3",
            remediation="Set AllowPSTNUsersToBypassLobby to False in Teams meeting policy.",
            compliance_mappings=["NIST-800-53-AC-3"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_teams_cloud_recording_policy",
            title="Teams cloud recording stored in compliant region",
            description="Meeting recordings are stored in a compliant geographic region.",
            severity="low",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L2",
            cis_profile="E3",
            assessment_type="manual",
            remediation="Verify Teams recording storage location complies with data residency requirements.",
            compliance_mappings=["NIST-800-53-SC-28"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_teams_live_events_restricted",
            title="Live events permissions are restricted",
            description="Only authorized users can create and schedule live events.",
            severity="low",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            cis_level="L2",
            cis_profile="E3",
            remediation="Restrict live events creation to specific users in Teams live events policy.",
            compliance_mappings=["NIST-800-53-AC-6"],
            source="scanner",
            tags=["teams_sharepoint"],
        ),
        # =====================================================================
        # Section 9 - Power Platform (~4 checks)
        # =====================================================================
        CheckDefinition(
            check_id="m365_power_platform_dlp",
            title="Power Platform DLP policies are configured",
            description="Data Loss Prevention policies restrict connector usage in Power Apps and Power Automate.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            remediation="Create DLP policies in Power Platform admin center to classify business and non-business connectors.",
            compliance_mappings=["NIST-800-53-SC-7"],
            dspm_relevant=True,
            dspm_categories=["dlp"],
            source="scanner",
            tags=["data_protection", "power_platform"],
        ),
        CheckDefinition(
            check_id="m365_power_platform_env_security",
            title="Power Platform environment security is configured",
            description="Power Platform environments have appropriate security roles and access controls.",
            severity="medium",
            provider="m365",
            service="data_protection",
            category="Governance",
            cis_level="L2",
            cis_profile="E3",
            assessment_type="manual",
            remediation="Review and restrict environment creation and access in Power Platform admin center.",
            compliance_mappings=["NIST-800-53-AC-6"],
            source="scanner",
            tags=["data_protection", "power_platform"],
        ),
        CheckDefinition(
            check_id="m365_power_apps_sharing_restricted",
            title="Power Apps sharing is restricted",
            description="Power Apps cannot be shared broadly without approval.",
            severity="medium",
            provider="m365",
            service="data_protection",
            category="Governance",
            cis_level="L2",
            cis_profile="E3",
            remediation="Configure tenant-level sharing restrictions for Power Apps.",
            compliance_mappings=["NIST-800-53-AC-3"],
            source="scanner",
            tags=["data_protection", "power_platform"],
        ),
        CheckDefinition(
            check_id="m365_enterprise_apps_reviewed",
            title="Enterprise applications are reviewed regularly",
            description="Consented enterprise apps should be reviewed and stale ones removed.",
            severity="medium",
            provider="m365",
            service="identity",
            category="Governance",
            cis_level="L1",
            cis_profile="E3",
            assessment_type="manual",
            remediation="Perform quarterly access reviews of enterprise applications in Entra ID.",
            compliance_mappings=["NIST-800-53-AC-6(10)", "SOC2-CC6.1"],
            source="scanner",
            tags=["identity", "governance"],
        ),
    ]
