"""Check definitions for Microsoft 365.

Auto-generated from m365 scanner. 55 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Microsoft 365 check definitions."""
    return [
        CheckDefinition(
            check_id="m365_admin_mfa_enforced",
            title="MFA is enforced for all admin accounts",
            description="MFA is enforced for all admin accounts.",
            severity="critical",
            provider="m365",
            service="identity",
            category="Identity",
            tags=["identity", "mfa"],
        ),
        CheckDefinition(
            check_id="m365_aip_encryption_enabled",
            title="Azure Information Protection encryption labels exist",
            description="Azure Information Protection encryption labels exist.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            tags=["data_protection", "encryption"],
        ),
        CheckDefinition(
            check_id="m365_anti_phishing_policy",
            title="Anti-phishing policy is configured",
            description="Anti-phishing policy is configured.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_ca_block_legacy_auth",
            title="Legacy authentication is blocked",
            description="Legacy authentication is blocked.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Compliance",
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_ca_policies_configured",
            title="Conditional Access policies are configured and enabled",
            description="Conditional Access policies are configured and enabled.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Compliance",
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_ca_require_compliant_device",
            title="Compliant device requirement exists",
            description="Compliant device requirement exists.",
            severity="medium",
            provider="m365",
            service="conditional_access",
            category="Compliance",
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_ca_require_mfa",
            title="MFA is required by Conditional Access",
            description="MFA is required by Conditional Access.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Compliance",
            tags=["conditional_access", "mfa"],
        ),
        CheckDefinition(
            check_id="m365_ca_sign_in_risk",
            title="Sign-in risk-based policy is configured",
            description="Sign-in risk-based policy is configured.",
            severity="high",
            provider="m365",
            service="conditional_access",
            category="Compliance",
            tags=["conditional_access"],
        ),
        CheckDefinition(
            check_id="m365_cis_admin_cloud_only",
            title="Administrative accounts are cloud-only (CIS 1.1.1)",
            description="Administrative accounts are cloud-only (CIS 1.1.1).",
            severity="critical",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_cis_anti_phishing_advanced",
            title="Anti-phishing policy with aggressive settings (CIS 2.1.1)",
            description="Anti-phishing policy with aggressive settings (CIS 2.1.1).",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_cis_audit_log_enabled",
            title="Microsoft 365 audit log search is enabled (CIS 3.1.1)",
            description="Microsoft 365 audit log search is enabled (CIS 3.1.1).",
            severity="critical",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center", "audit"],
        ),
        CheckDefinition(
            check_id="m365_cis_defender_cloud_apps",
            title="Defender for Cloud Apps is connected (CIS 2.4.1)",
            description="Defender for Cloud Apps is connected (CIS 2.4.1).",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_cis_device_compliance_secure",
            title="Device compliance marks noncompliant devices by default (CIS 4.1)",
            description="Device compliance marks noncompliant devices by default (CIS 4.1).",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_cis_dlp_policies_enabled",
            title="DLP policies are enabled in Microsoft Purview (CIS 3.2.1)",
            description="DLP policies are enabled in Microsoft Purview (CIS 3.2.1).",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_cis_external_email_tagging",
            title="External email tagging is enabled (CIS 6.2.1)",
            description="External email tagging is enabled (CIS 6.2.1).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_fabric_guest_restricted",
            title="Microsoft Fabric restricts guest user access",
            description="Microsoft Fabric restricts guest user access.",
            severity="medium",
            provider="m365",
            service="intune_entra",
            category="Governance",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_cis_idle_session_timeout",
            title="Idle session timeout ≤3 hours for unmanaged devices (CIS 1.3.1)",
            description="Idle session timeout ≤3 hours for unmanaged devices (CIS 1.3.1).",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_cis_mailbox_audit_enabled",
            title="Mailbox auditing is not disabled (CIS 6.1.1)",
            description="Mailbox auditing is not disabled (CIS 6.1.1).",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online", "audit"],
        ),
        CheckDefinition(
            check_id="m365_cis_modern_auth_exchange",
            title="Modern authentication is enabled for Exchange Online (CIS 6.5.1)",
            description="Modern authentication is enabled for Exchange Online (CIS 6.5.1).",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_onedrive_sync_domain_joined",
            title="OneDrive sync restricted to domain-joined computers (CIS 7.3.1)",
            description="OneDrive sync restricted to domain-joined computers (CIS 7.3.1).",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_outlook_addins_restricted",
            title="Users cannot install Outlook add-ins (CIS 6.3.1)",
            description="Users cannot install Outlook add-ins (CIS 6.3.1).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_personal_enrollment_blocked",
            title="Personal device enrollment is blocked (CIS 4.2)",
            description="Personal device enrollment is blocked (CIS 4.2).",
            severity="high",
            provider="m365",
            service="intune_entra",
            category="Governance",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_cis_pim_approval_required",
            title="PIM requires approval for Privileged Role Administrator (CIS 5.3.1)",
            description="PIM requires approval for Privileged Role Administrator (CIS 5.3.1).",
            severity="critical",
            provider="m365",
            service="intune_entra",
            category="Governance",
            tags=["intune_entra"],
        ),
        CheckDefinition(
            check_id="m365_cis_sensitivity_labels_published",
            title="Sensitivity label policies are published (CIS 3.3.1)",
            description="Sensitivity label policies are published (CIS 3.3.1).",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_cis_shared_mailbox_signin_blocked",
            title="Sign-in to shared mailboxes is blocked (CIS 1.2.1)",
            description="Sign-in to shared mailboxes is blocked (CIS 1.2.1).",
            severity="high",
            provider="m365",
            service="admin_center",
            category="Compliance",
            tags=["admin_center"],
        ),
        CheckDefinition(
            check_id="m365_cis_sharepoint_default_link_view",
            title="SharePoint default sharing link permission is View (CIS 7.2.1)",
            description="SharePoint default sharing link permission is View (CIS 7.2.1).",
            severity="high",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_apps_restricted",
            title="Third-party and custom Teams apps are restricted (CIS 8.4.1)",
            description="Third-party and custom Teams apps are restricted (CIS 8.4.1).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_email_disabled",
            title="Teams email channel integration is disabled (CIS 8.1.1)",
            description="Teams email channel integration is disabled (CIS 8.1.1).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_external_control",
            title="External participants cannot give/request control (CIS 8.5.1)",
            description="External participants cannot give/request control (CIS 8.5.1).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_recording_off",
            title="Meeting recording is Off by default (CIS 8.5.8)",
            description="Meeting recording is Off by default (CIS 8.5.8).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_security_reporting",
            title="Users can report security concerns in Teams (CIS 8.6.1)",
            description="Users can report security concerns in Teams (CIS 8.6.1).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_cis_teams_trial_blocked",
            title="External access with trial tenants is blocked (CIS 8.2.1)",
            description="External access with trial tenants is blocked (CIS 8.2.1).",
            severity="medium",
            provider="m365",
            service="exchange_online",
            category="Compliance",
            tags=["exchange_online"],
        ),
        CheckDefinition(
            check_id="m365_defender_low_exposure",
            title="Machine exposure level is low or none",
            description="Machine exposure level is low or none.",
            severity="high",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_defender_low_risk",
            title="Machine risk score is low or none",
            description="Machine risk score is low or none.",
            severity="critical",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_defender_sensor_active",
            title="Defender sensor is active on machine",
            description="Defender sensor is active on machine.",
            severity="high",
            provider="m365",
            service="defender_endpoint",
            category="Threat Detection",
            tags=["defender_endpoint"],
        ),
        CheckDefinition(
            check_id="m365_dkim_configured",
            title="DKIM is configured for domain",
            description="DKIM is configured for domain.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_dlp_policies_configured",
            title="Data Loss Prevention policies are configured",
            description="Data Loss Prevention policies are configured.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_dmarc_configured",
            title="DMARC record is configured for domain",
            description="DMARC record is configured for domain.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_external_sharing_restricted",
            title="External sharing is restricted (not open to anonymous)",
            description="External sharing is restricted (not open to anonymous).",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_guest_access_restricted",
            title="Guest invitation settings are restricted",
            description="Guest invitation settings are restricted.",
            severity="medium",
            provider="m365",
            service="data_protection",
            category="Compliance",
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_legacy_auth_blocked",
            title="Legacy authentication protocols are blocked tenant-wide",
            description="Legacy authentication protocols are blocked tenant-wide.",
            severity="high",
            provider="m365",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_no_high_risk_users",
            title="No high-risk users detected",
            description="No high-risk users detected.",
            severity="critical",
            provider="m365",
            service="aad_users",
            category="Compliance",
            tags=["aad_users"],
        ),
        CheckDefinition(
            check_id="m365_onedrive_sync_restricted",
            title="OneDrive sync is restricted to managed devices",
            description="OneDrive sync is restricted to managed devices.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_password_never_expire_disabled",
            title="Password never expire policy is disabled",
            description="Password never expire policy is disabled.",
            severity="medium",
            provider="m365",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_privileged_accounts_limited",
            title="Global Administrator accounts are limited (5 or fewer)",
            description="Global Administrator accounts are limited (5 or fewer).",
            severity="high",
            provider="m365",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_safe_attachments_enabled",
            title="Safe Attachments policy is enabled",
            description="Safe Attachments policy is enabled.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_safe_links_enabled",
            title="Safe Links policy is enabled",
            description="Safe Links policy is enabled.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_security_defaults_enabled",
            title="Security defaults are enabled (or equivalent CA policies exist)",
            description="Security defaults are enabled (or equivalent CA policies exist).",
            severity="high",
            provider="m365",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_self_service_password_reset",
            title="Self-service password reset is enabled",
            description="Self-service password reset is enabled.",
            severity="medium",
            provider="m365",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="m365_sensitivity_labels_enabled",
            title="Sensitivity labels are configured and published",
            description="Sensitivity labels are configured and published.",
            severity="high",
            provider="m365",
            service="data_protection",
            category="Compliance",
            tags=["data_protection"],
        ),
        CheckDefinition(
            check_id="m365_sharepoint_sharing_restricted",
            title="SharePoint sharing is restricted to existing guests or disabled",
            description="SharePoint sharing is restricted to existing guests or disabled.",
            severity="high",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_spf_configured",
            title="SPF record is configured for domain",
            description="SPF record is configured for domain.",
            severity="high",
            provider="m365",
            service="email_security",
            category="Compliance",
            tags=["email_security"],
        ),
        CheckDefinition(
            check_id="m365_teams_external_access_restricted",
            title="Teams external access is restricted",
            description="Teams external access is restricted.",
            severity="medium",
            provider="m365",
            service="teams_sharepoint",
            category="Collaboration",
            tags=["teams_sharepoint"],
        ),
        CheckDefinition(
            check_id="m365_user_mfa_registered",
            title="User has MFA method registered",
            description="User has MFA method registered.",
            severity="high",
            provider="m365",
            service="aad_users",
            category="Compliance",
            tags=["aad_users", "mfa"],
        ),
        CheckDefinition(
            check_id="m365_user_phishing_resistant_mfa",
            title="User has phishing-resistant MFA (FIDO2/Windows Hello)",
            description="User has phishing-resistant MFA (FIDO2/Windows Hello).",
            severity="medium",
            provider="m365",
            service="aad_users",
            category="Compliance",
            tags=["aad_users", "mfa"],
        ),
    ]
