"""Check definitions for OCI.

Auto-generated from oci scanner. 59 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all OCI check definitions."""
    return [
        CheckDefinition(
            check_id="oci_cloud_guard_enabled",
            title="Cloud Guard should be enabled for the tenancy",
            description="Cloud Guard should be enabled for the tenancy.",
            severity="critical",
            provider="oci",
            service="CloudGuard",
            category="Compliance",
            tags=["cloudguard"],
        ),
        CheckDefinition(
            check_id="oci_compute_boot_volume_transit_encryption",
            title="Boot volumes should have in-transit encryption enabled",
            description="Boot volumes should have in-transit encryption enabled.",
            severity="medium",
            provider="oci",
            service="Compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="oci_compute_imds_v2",
            title="Compute instances should disable legacy IMDS v1 endpoints",
            description="Compute instances should disable legacy IMDS v1 endpoints.",
            severity="high",
            provider="oci",
            service="Compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="oci_compute_secure_boot",
            title="Compute instances should have Secure Boot enabled",
            description="Compute instances should have Secure Boot enabled.",
            severity="medium",
            provider="oci",
            service="Compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="oci_container_instance_graceful_shutdown",
            title="Container instances should have a graceful shutdown timeout configured",
            description="Container instances should have a graceful shutdown timeout configured.",
            severity="low",
            provider="oci",
            service="ContainerInstances",
            category="Compliance",
            tags=["containerinstances"],
        ),
        CheckDefinition(
            check_id="oci_container_instance_restart_policy",
            title="Container instances should have a restart policy defined",
            description="Container instances should have a restart policy defined.",
            severity="medium",
            provider="oci",
            service="ContainerInstances",
            category="Compliance",
            tags=["containerinstances"],
        ),
        CheckDefinition(
            check_id="oci_container_registry_immutable_artifacts",
            title="Container registry should enable immutable artifacts",
            description="Container registry should enable immutable artifacts.",
            severity="medium",
            provider="oci",
            service="ContainerRegistry",
            category="Compliance",
            tags=["containerregistry"],
        ),
        CheckDefinition(
            check_id="oci_container_registry_public_repo",
            title="Container registry repositories should not be public",
            description="Container registry repositories should not be public.",
            severity="high",
            provider="oci",
            service="ContainerRegistry",
            category="Compliance",
            tags=["containerregistry", "public-access"],
        ),
        CheckDefinition(
            check_id="oci_db_autonomous_autoscaling",
            title="Autonomous databases should have auto-scaling enabled",
            description="Autonomous databases should have auto-scaling enabled.",
            severity="low",
            provider="oci",
            service="Database",
            category="Compliance",
            tags=["database"],
        ),
        CheckDefinition(
            check_id="oci_db_autonomous_cmk_encryption",
            title="Autonomous databases should use customer-managed encryption keys",
            description="Autonomous databases should use customer-managed encryption keys.",
            severity="high",
            provider="oci",
            service="Database",
            category="Compliance",
            tags=["database", "encryption"],
        ),
        CheckDefinition(
            check_id="oci_db_autonomous_private_endpoint",
            title="Autonomous databases should use private endpoints",
            description="Autonomous databases should use private endpoints.",
            severity="high",
            provider="oci",
            service="Database",
            category="Compliance",
            tags=["database"],
        ),
        CheckDefinition(
            check_id="oci_db_system_backup_enabled",
            title="Database systems should have automatic backups enabled",
            description="Database systems should have automatic backups enabled.",
            severity="high",
            provider="oci",
            service="Database",
            category="Compliance",
            tags=["database", "backup"],
        ),
        CheckDefinition(
            check_id="oci_events_rule_configured",
            title="oci_events_rule_configured",
            description="oci_events_rule_configured.",
            severity="medium",
            provider="oci",
            service="Events",
            category="Compliance",
            tags=["events"],
        ),
        CheckDefinition(
            check_id="oci_filestorage_cmk_encryption",
            title="File systems should use customer-managed encryption keys",
            description="File systems should use customer-managed encryption keys.",
            severity="high",
            provider="oci",
            service="FileStorage",
            category="Storage",
            tags=["filestorage", "encryption"],
        ),
        CheckDefinition(
            check_id="oci_filestorage_export_privileged_port",
            title="File Storage exports should require privileged source ports",
            description="File Storage exports should require privileged source ports.",
            severity="medium",
            provider="oci",
            service="FileStorage",
            category="Storage",
            tags=["filestorage"],
        ),
        CheckDefinition(
            check_id="oci_filestorage_mount_target_nsg",
            title="File Storage mount targets should have NSGs assigned",
            description="File Storage mount targets should have NSGs assigned.",
            severity="medium",
            provider="oci",
            service="FileStorage",
            category="Storage",
            tags=["filestorage", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="oci_functions_app_nsg_assigned",
            title="Functions applications should have NSGs assigned",
            description="Functions applications should have NSGs assigned.",
            severity="medium",
            provider="oci",
            service="Functions",
            category="Serverless",
            tags=["functions", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="oci_functions_app_tracing_enabled",
            title="Functions applications should have distributed tracing enabled",
            description="Functions applications should have distributed tracing enabled.",
            severity="low",
            provider="oci",
            service="Functions",
            category="Serverless",
            tags=["functions"],
        ),
        CheckDefinition(
            check_id="oci_functions_provisioned_concurrency",
            title="Functions should have provisioned concurrency configured for production",
            description="Functions should have provisioned concurrency configured for production.",
            severity="low",
            provider="oci",
            service="Functions",
            category="Serverless",
            tags=["functions"],
        ),
        CheckDefinition(
            check_id="oci_iam_admin_mfa_enabled",
            title="Administrator users must have MFA enabled",
            description="Administrator users must have MFA enabled.",
            severity="critical",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam", "mfa"],
        ),
        CheckDefinition(
            check_id="oci_iam_admin_no_api_key",
            title="Tenancy administrator users should not have API keys",
            description="Tenancy administrator users should not have API keys.",
            severity="critical",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="oci_iam_api_key_rotation",
            title="IAM API keys should be rotated within 90 days",
            description="IAM API keys should be rotated within 90 days.",
            severity="high",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="oci_iam_auth_token_rotation",
            title="IAM auth tokens should be rotated within 90 days",
            description="IAM auth tokens should be rotated within 90 days.",
            severity="high",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="oci_iam_credentials_unused",
            title="IAM credentials unused for 45+ days should be disabled",
            description="IAM credentials unused for 45+ days should be disabled.",
            severity="high",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="oci_iam_password_expiry",
            title="IAM password policy should expire passwords within 365 days",
            description="IAM password policy should expire passwords within 365 days.",
            severity="medium",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="oci_iam_password_reuse",
            title="IAM password policy should prevent reuse of last 24 passwords",
            description="IAM password policy should prevent reuse of last 24 passwords.",
            severity="medium",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="oci_iam_policy_no_wildcard",
            title="IAM policies should not allow wildcard resource access",
            description="IAM policies should not allow wildcard resource access.",
            severity="high",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="oci_iam_secret_key_rotation",
            title="Customer secret keys should be rotated within 90 days",
            description="Customer secret keys should be rotated within 90 days.",
            severity="high",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam", "rotation"],
        ),
        CheckDefinition(
            check_id="oci_iam_single_api_key",
            title="Each IAM user should have only one active API key",
            description="Each IAM user should have only one active API key.",
            severity="medium",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="oci_iam_user_mfa_enabled",
            title="IAM local users should have MFA enabled",
            description="IAM local users should have MFA enabled.",
            severity="critical",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam", "mfa"],
        ),
        CheckDefinition(
            check_id="oci_iam_user_valid_email",
            title="All IAM local users should have a valid email address",
            description="All IAM local users should have a valid email address.",
            severity="medium",
            provider="oci",
            service="IAM",
            category="Identity",
            tags=["iam"],
        ),
        CheckDefinition(
            check_id="oci_lb_backend_health",
            title="Load balancer backend sets should be healthy",
            description="Load balancer backend sets should be healthy.",
            severity="high",
            provider="oci",
            service="LoadBalancer",
            category="Compliance",
            tags=["loadbalancer"],
        ),
        CheckDefinition(
            check_id="oci_lb_listener_https",
            title="Load balancer listeners should use HTTPS/TLS",
            description="Load balancer listeners should use HTTPS/TLS.",
            severity="high",
            provider="oci",
            service="LoadBalancer",
            category="Compliance",
            tags=["loadbalancer", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="oci_lb_nsg_assigned",
            title="Load balancers should have NSGs assigned",
            description="Load balancers should have NSGs assigned.",
            severity="medium",
            provider="oci",
            service="LoadBalancer",
            category="Compliance",
            tags=["loadbalancer", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="oci_logging_audit_retention",
            title="Audit log retention should be at least 365 days",
            description="Audit log retention should be at least 365 days.",
            severity="high",
            provider="oci",
            service="Logging",
            category="Logging",
            tags=["logging", "audit", "retention"],
        ),
        CheckDefinition(
            check_id="oci_logging_log_groups_exist",
            title="OCI Logging service should have log groups configured",
            description="OCI Logging service should have log groups configured.",
            severity="medium",
            provider="oci",
            service="Logging",
            category="Logging",
            tags=["logging"],
        ),
        CheckDefinition(
            check_id="oci_mysql_backup_enabled",
            title="MySQL DB systems should have automatic backups enabled",
            description="MySQL DB systems should have automatic backups enabled.",
            severity="high",
            provider="oci",
            service="MySQL",
            category="Database",
            tags=["mysql", "backup"],
        ),
        CheckDefinition(
            check_id="oci_mysql_crash_recovery",
            title="MySQL DB systems should have crash recovery enabled",
            description="MySQL DB systems should have crash recovery enabled.",
            severity="high",
            provider="oci",
            service="MySQL",
            category="Database",
            tags=["mysql"],
        ),
        CheckDefinition(
            check_id="oci_mysql_deletion_protection",
            title="MySQL DB systems should have deletion protection enabled",
            description="MySQL DB systems should have deletion protection enabled.",
            severity="high",
            provider="oci",
            service="MySQL",
            category="Database",
            tags=["mysql"],
        ),
        CheckDefinition(
            check_id="oci_mysql_high_availability",
            title="MySQL DB systems should be configured for high availability",
            description="MySQL DB systems should be configured for high availability.",
            severity="medium",
            provider="oci",
            service="MySQL",
            category="Database",
            tags=["mysql"],
        ),
        CheckDefinition(
            check_id="oci_mysql_pitr_enabled",
            title="MySQL DB systems should have point-in-time recovery configured",
            description="MySQL DB systems should have point-in-time recovery configured.",
            severity="high",
            provider="oci",
            service="MySQL",
            category="Database",
            tags=["mysql"],
        ),
        CheckDefinition(
            check_id="oci_network_default_sl_restrict",
            title="Default security list should restrict all traffic except ICMP within VCN",
            description="Default security list should restrict all traffic except ICMP within VCN.",
            severity="high",
            provider="oci",
            service="Networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="oci_network_nsg_no_unrestricted_ingress",
            title="NSGs should not allow unrestricted ingress from 0.0.0.0/0",
            description="NSGs should not allow unrestricted ingress from 0.0.0.0/0.",
            severity="high",
            provider="oci",
            service="Networking",
            category="Networking",
            tags=["networking", "security-group"],
        ),
        CheckDefinition(
            check_id="oci_network_vcn_flow_logs",
            title="VCN flow logs should be enabled for all subnets",
            description="VCN flow logs should be enabled for all subnets.",
            severity="medium",
            provider="oci",
            service="Networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="oci_notifications_security_topic_exists",
            title="At least one notification topic should exist for security events",
            description="At least one notification topic should exist for security events.",
            severity="high",
            provider="oci",
            service="Notifications",
            category="Compliance",
            tags=["notifications"],
        ),
        CheckDefinition(
            check_id="oci_notifications_topic_configured",
            title="Notification topics should have active subscriptions",
            description="Notification topics should have active subscriptions.",
            severity="medium",
            provider="oci",
            service="Notifications",
            category="Compliance",
            tags=["notifications"],
        ),
        CheckDefinition(
            check_id="oci_objectstorage_bucket_cmk_encryption",
            title="Object Storage buckets should be encrypted with customer-managed keys",
            description="Object Storage buckets should be encrypted with customer-managed keys.",
            severity="high",
            provider="oci",
            service="ObjectStorage",
            category="Storage",
            tags=["objectstorage", "encryption"],
        ),
        CheckDefinition(
            check_id="oci_objectstorage_bucket_emit_events",
            title="Object Storage buckets should emit object events",
            description="Object Storage buckets should emit object events.",
            severity="medium",
            provider="oci",
            service="ObjectStorage",
            category="Storage",
            tags=["objectstorage"],
        ),
        CheckDefinition(
            check_id="oci_objectstorage_bucket_public_access",
            title="Object Storage buckets should not allow public access",
            description="Object Storage buckets should not allow public access.",
            severity="critical",
            provider="oci",
            service="ObjectStorage",
            category="Storage",
            tags=["objectstorage", "public-access"],
        ),
        CheckDefinition(
            check_id="oci_objectstorage_bucket_versioning",
            title="Object Storage buckets should have versioning enabled",
            description="Object Storage buckets should have versioning enabled.",
            severity="medium",
            provider="oci",
            service="ObjectStorage",
            category="Storage",
            tags=["objectstorage"],
        ),
        CheckDefinition(
            check_id="oci_oke_cluster_nsg_assigned",
            title="OKE clusters should have NSGs assigned",
            description="OKE clusters should have NSGs assigned.",
            severity="medium",
            provider="oci",
            service="KubernetesEngine",
            category="Compliance",
            tags=["kubernetesengine", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="oci_oke_cluster_public_endpoint",
            title="OKE clusters should not have publicly accessible API servers",
            description="OKE clusters should not have publicly accessible API servers.",
            severity="high",
            provider="oci",
            service="KubernetesEngine",
            category="Compliance",
            tags=["kubernetesengine", "public-access"],
        ),
        CheckDefinition(
            check_id="oci_oke_image_verification",
            title="OKE clusters should have image verification policies enabled",
            description="OKE clusters should have image verification policies enabled.",
            severity="high",
            provider="oci",
            service="KubernetesEngine",
            category="Compliance",
            tags=["kubernetesengine"],
        ),
        CheckDefinition(
            check_id="oci_oke_kubernetes_version",
            title="OKE clusters should use a supported Kubernetes version",
            description="OKE clusters should use a supported Kubernetes version.",
            severity="medium",
            provider="oci",
            service="KubernetesEngine",
            category="Compliance",
            tags=["kubernetesengine"],
        ),
        CheckDefinition(
            check_id="oci_oke_nodepool_nsg_assigned",
            title="OKE node pools should have NSGs assigned",
            description="OKE node pools should have NSGs assigned.",
            severity="medium",
            provider="oci",
            service="KubernetesEngine",
            category="Compliance",
            tags=["kubernetesengine", "networking", "security-group"],
        ),
        CheckDefinition(
            check_id="oci_storage_boot_volume_cmk_encryption",
            title="Boot volumes should be encrypted with customer-managed keys",
            description="Boot volumes should be encrypted with customer-managed keys.",
            severity="high",
            provider="oci",
            service="Storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="oci_storage_volume_cmk_encryption",
            title="Block volumes should be encrypted with customer-managed keys",
            description="Block volumes should be encrypted with customer-managed keys.",
            severity="high",
            provider="oci",
            service="Storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="oci_vault_key_rotation",
            title="Vault master encryption keys should be rotated regularly",
            description="Vault master encryption keys should be rotated regularly.",
            severity="high",
            provider="oci",
            service="Vault",
            category="Compliance",
            tags=["vault", "rotation"],
        ),
        CheckDefinition(
            check_id="oci_vault_private_type",
            title="Vaults should use Virtual Private type for isolation",
            description="Vaults should use Virtual Private type for isolation.",
            severity="medium",
            provider="oci",
            service="Vault",
            category="Compliance",
            tags=["vault"],
        ),
    ]
