"""Check definitions for OpenStack.

Auto-generated from openstack scanner. 55 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all OpenStack check definitions."""
    return [
        CheckDefinition(
            check_id="openstack_compute_default_sg_restrictive",
            title="Default security group does not allow unrestricted ingress",
            description="Default security group does not allow unrestricted ingress.",
            severity="high",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "security-group"],
        ),
        CheckDefinition(
            check_id="openstack_compute_live_migration_encryption",
            title="Live migration encryption should be enabled",
            description="Live migration encryption should be enabled.",
            severity="high",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_compute_metadata_reviewed",
            title="Instance metadata is reviewed for sensitive data",
            description="Instance metadata is reviewed for sensitive data.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="openstack_compute_serial_console",
            title="Serial console access is restricted",
            description="Serial console access is restricted.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="openstack_identity_admin_mfa",
            title="Multi-factor authentication is configured for admin accounts",
            description="Multi-factor authentication is configured for admin accounts.",
            severity="critical",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "mfa"],
        ),
        CheckDefinition(
            check_id="openstack_identity_domain_separation",
            title="Multiple identity domains are configured for separation",
            description="Multiple identity domains are configured for separation.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_federation",
            title="Federated identity (LDAP/SSO) is configured",
            description="Federated identity (LDAP/SSO) is configured.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_password_policy",
            title="Password policy strength requirements are configured",
            description="Password policy strength requirements are configured.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_service_accounts",
            title="Service accounts are identified and reviewed",
            description="Service accounts are identified and reviewed.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_token_expiration",
            title="Token expiration is set to 4 hours or less",
            description="Token expiration is set to 4 hours or less.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_image_public_review",
            title="Public image visibility is justified",
            description="Public image visibility is justified.",
            severity="medium",
            provider="openstack",
            service="image",
            category="Compliance",
            tags=["image", "public-access"],
        ),
        CheckDefinition(
            check_id="openstack_image_signature_verification",
            title="Image signature verification is enabled",
            description="Image signature verification is enabled.",
            severity="high",
            provider="openstack",
            service="image",
            category="Compliance",
            tags=["image"],
        ),
        CheckDefinition(
            check_id="openstack_image_visibility_audit",
            title="Public images are reviewed and minimized",
            description="Public images are reviewed and minimized.",
            severity="medium",
            provider="openstack",
            service="image",
            category="Compliance",
            tags=["image", "audit"],
        ),
        CheckDefinition(
            check_id="openstack_net_anti_spoofing",
            title="Allowed address pairs are minimized (anti-spoofing)",
            description="Allowed address pairs are minimized (anti-spoofing).",
            severity="medium",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_floating_ip_audit",
            title="Floating IPs are associated and reviewed",
            description="Floating IPs are associated and reviewed.",
            severity="medium",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "audit"],
        ),
        CheckDefinition(
            check_id="openstack_net_port_security",
            title="Port security is enabled on all active ports",
            description="Port security is enabled on all active ports.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_port_security_individual",
            title="Port has port security enabled",
            description="Port has port security enabled.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_segmentation",
            title="Network segmentation is implemented",
            description="Network segmentation is implemented.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_sg_restrictive",
            title="Security group does not have unrestricted ingress on all ports",
            description="Security group does not have unrestricted ingress on all ports.",
            severity="critical",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "security-group"],
        ),
        CheckDefinition(
            check_id="openstack_storage_backup_policies",
            title="Volume backups are configured",
            description="Volume backups are configured.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "backup"],
        ),
        CheckDefinition(
            check_id="openstack_storage_object_versioning",
            title="Object versioning is enabled on Swift containers",
            description="Object versioning is enabled on Swift containers.",
            severity="medium",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        CheckDefinition(
            check_id="openstack_storage_swift_acls",
            title="Swift containers do not have public read access",
            description="Swift containers do not have public read access.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        CheckDefinition(
            check_id="openstack_storage_volume_encrypted",
            title="Volume is encrypted",
            description="Volume is encrypted.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_storage_volume_encryption",
            title="Block storage volumes are encrypted",
            description="Block storage volumes are encrypted.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        # --- New checks below ---
        CheckDefinition(
            check_id="openstack_identity_ldap_tls",
            title="LDAP identity backend uses TLS for connections",
            description="LDAP identity backend uses TLS for connections.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "ldap", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_identity_rbac_policies",
            title="RBAC policies are configured for fine-grained access control",
            description="RBAC policies are configured for fine-grained access control.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "rbac"],
        ),
        CheckDefinition(
            check_id="openstack_identity_application_credentials",
            title="Application credentials are used instead of user passwords for automation",
            description="Application credentials are used instead of user passwords for automation.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "credentials"],
        ),
        CheckDefinition(
            check_id="openstack_identity_audit_middleware",
            title="Keystone audit middleware (PyCADF) is enabled",
            description="Keystone audit middleware (PyCADF) is enabled.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "audit"],
        ),
        CheckDefinition(
            check_id="openstack_identity_project_quotas",
            title="Project quotas are configured to prevent resource abuse",
            description="Project quotas are configured to prevent resource abuse.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "quotas"],
        ),
        CheckDefinition(
            check_id="openstack_identity_role_assignments_reviewed",
            title="Role assignments are periodically reviewed for least privilege",
            description="Role assignments are periodically reviewed for least privilege.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "rbac", "audit"],
        ),
        CheckDefinition(
            check_id="openstack_compute_tpm_enabled",
            title="Trusted Platform Module (vTPM) is enabled for sensitive workloads",
            description="Trusted Platform Module (vTPM) is enabled for sensitive workloads.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "tpm"],
        ),
        CheckDefinition(
            check_id="openstack_compute_config_drive_secure",
            title="Config drive is used securely for instance metadata",
            description="Config drive is used securely for instance metadata.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="openstack_compute_vnc_tls",
            title="VNC console access is encrypted with TLS",
            description="VNC console access is encrypted with TLS.",
            severity="high",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "encryption", "console"],
        ),
        CheckDefinition(
            check_id="openstack_compute_spice_tls",
            title="SPICE console access is encrypted with TLS",
            description="SPICE console access is encrypted with TLS.",
            severity="high",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "encryption", "console"],
        ),
        CheckDefinition(
            check_id="openstack_compute_volume_encryption_default",
            title="Default volume encryption is enabled for new compute instances",
            description="Default volume encryption is enabled for new compute instances.",
            severity="high",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_compute_flavor_access_restricted",
            title="Compute flavor access is restricted to authorized projects",
            description="Compute flavor access is restricted to authorized projects.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "access-control"],
        ),
        CheckDefinition(
            check_id="openstack_net_fwaas_configured",
            title="Firewall-as-a-Service (FWaaS) is configured",
            description="Firewall-as-a-Service (FWaaS) is configured.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "firewall"],
        ),
        CheckDefinition(
            check_id="openstack_net_vpnaas_configured",
            title="VPN-as-a-Service (VPNaaS) uses strong encryption",
            description="VPN-as-a-Service (VPNaaS) uses strong encryption.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "vpn", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_net_qos_policies",
            title="QoS policies are configured for network traffic management",
            description="QoS policies are configured for network traffic management.",
            severity="low",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "qos"],
        ),
        CheckDefinition(
            check_id="openstack_net_dns_integration",
            title="DNS integration (Designate) uses authenticated updates",
            description="DNS integration (Designate) uses authenticated updates.",
            severity="medium",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "dns"],
        ),
        CheckDefinition(
            check_id="openstack_net_bgp_authentication",
            title="BGP dynamic routing uses authentication",
            description="BGP dynamic routing uses authentication.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "bgp"],
        ),
        CheckDefinition(
            check_id="openstack_net_tls_proxy",
            title="TLS proxy is configured for internal service communication",
            description="TLS proxy is configured for internal service communication.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "ssl-tls", "proxy"],
        ),
        CheckDefinition(
            check_id="openstack_storage_swift_encryption",
            title="Swift object storage at-rest encryption is enabled",
            description="Swift object storage at-rest encryption is enabled.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_storage_cinder_backup_encryption",
            title="Cinder backup service uses encrypted storage",
            description="Cinder backup service uses encrypted storage.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "encryption", "backup"],
        ),
        CheckDefinition(
            check_id="openstack_storage_manila_access_restricted",
            title="Manila shared file system access rules are restrictive",
            description="Manila shared file system access rules are restrictive.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "manila"],
        ),
        CheckDefinition(
            check_id="openstack_storage_quota_configured",
            title="Storage quotas are configured per project",
            description="Storage quotas are configured per project.",
            severity="medium",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "quotas"],
        ),
        CheckDefinition(
            check_id="openstack_api_rate_limiting",
            title="API rate limiting is configured to prevent abuse",
            description="API rate limiting is configured to prevent abuse.",
            severity="medium",
            provider="openstack",
            service="api",
            category="Compliance",
            tags=["api", "rate-limiting"],
        ),
        CheckDefinition(
            check_id="openstack_api_audit_logging",
            title="API audit logging is enabled across all services",
            description="API audit logging is enabled across all services.",
            severity="high",
            provider="openstack",
            service="api",
            category="Compliance",
            tags=["api", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="openstack_api_tls_v12_minimum",
            title="API endpoints require TLS 1.2 or higher",
            description="API endpoints require TLS 1.2 or higher.",
            severity="high",
            provider="openstack",
            service="api",
            category="Compliance",
            tags=["api", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="openstack_barbican_configured",
            title="Barbican key management service is configured for secrets storage",
            description="Barbican key management service is configured for secrets storage.",
            severity="high",
            provider="openstack",
            service="security",
            category="Compliance",
            tags=["security", "key-management"],
        ),
        CheckDefinition(
            check_id="openstack_octavia_tls_termination",
            title="Octavia load balancer uses TLS termination with valid certificates",
            description="Octavia load balancer uses TLS termination with valid certificates.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "load-balancer", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="openstack_heat_stack_restricted",
            title="Heat stack creation is restricted to authorized projects",
            description="Heat stack creation is restricted to authorized projects.",
            severity="medium",
            provider="openstack",
            service="orchestration",
            category="Compliance",
            tags=["orchestration", "heat"],
        ),
        CheckDefinition(
            check_id="openstack_magnum_cluster_tls",
            title="Magnum container clusters use TLS for API communication",
            description="Magnum container clusters use TLS for API communication.",
            severity="high",
            provider="openstack",
            service="containers",
            category="Compliance",
            tags=["containers", "magnum", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="openstack_ironic_secure_boot",
            title="Ironic bare metal nodes use UEFI Secure Boot when supported",
            description="Ironic bare metal nodes use UEFI Secure Boot when supported.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "ironic", "secure-boot"],
        ),
        CheckDefinition(
            check_id="openstack_designate_zone_restricted",
            title="Designate DNS zone management is restricted to authorized projects",
            description="Designate DNS zone management is restricted to authorized projects.",
            severity="medium",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "dns", "designate"],
        ),
        # --- Supplementary: MITRE orphan resolution ---
        CheckDefinition(
            check_id="openstack_identity_token_expiry",
            title="Identity token expiry is configured appropriately",
            description="Identity token expiry is configured appropriately.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            scanner_check_ids=["openstack_identity_token_expiry"],
            source="scanner",
            tags=["identity", "tokens"],
        ),
        CheckDefinition(
            check_id="openstack_network_sg_no_ssh_open",
            title="Security group does not allow unrestricted SSH access",
            description="Security group does not allow unrestricted SSH access.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            scanner_check_ids=["openstack_network_sg_no_ssh_open"],
            source="scanner",
            tags=["networking", "ssh"],
        ),
    ]
