"""Check definitions for OpenStack.

Auto-generated from openstack scanner. 24 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all OpenStack check definitions."""
    return [
        CheckDefinition(
            check_id="openstack_compute_default_sg_restrictive",
            title="Default security group does not allow unrestricted ingress",
            description="Default security group does not allow unrestricted ingress.",
            severity="high",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "security-group"],
        ),
        CheckDefinition(
            check_id="openstack_compute_live_migration_encryption",
            title="Live migration encryption should be enabled",
            description="Live migration encryption should be enabled.",
            severity="high",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_compute_metadata_reviewed",
            title="Instance metadata is reviewed for sensitive data",
            description="Instance metadata is reviewed for sensitive data.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="openstack_compute_serial_console",
            title="Serial console access is restricted",
            description="Serial console access is restricted.",
            severity="medium",
            provider="openstack",
            service="compute",
            category="Compute",
            tags=["compute"],
        ),
        CheckDefinition(
            check_id="openstack_identity_admin_mfa",
            title="Multi-factor authentication is configured for admin accounts",
            description="Multi-factor authentication is configured for admin accounts.",
            severity="critical",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity", "mfa"],
        ),
        CheckDefinition(
            check_id="openstack_identity_domain_separation",
            title="Multiple identity domains are configured for separation",
            description="Multiple identity domains are configured for separation.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_federation",
            title="Federated identity (LDAP/SSO) is configured",
            description="Federated identity (LDAP/SSO) is configured.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_password_policy",
            title="Password policy strength requirements are configured",
            description="Password policy strength requirements are configured.",
            severity="high",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_service_accounts",
            title="Service accounts are identified and reviewed",
            description="Service accounts are identified and reviewed.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_identity_token_expiration",
            title="Token expiration is set to 4 hours or less",
            description="Token expiration is set to 4 hours or less.",
            severity="medium",
            provider="openstack",
            service="identity",
            category="Identity",
            tags=["identity"],
        ),
        CheckDefinition(
            check_id="openstack_image_public_review",
            title="Public image visibility is justified",
            description="Public image visibility is justified.",
            severity="medium",
            provider="openstack",
            service="image",
            category="Compliance",
            tags=["image", "public-access"],
        ),
        CheckDefinition(
            check_id="openstack_image_signature_verification",
            title="Image signature verification is enabled",
            description="Image signature verification is enabled.",
            severity="high",
            provider="openstack",
            service="image",
            category="Compliance",
            tags=["image"],
        ),
        CheckDefinition(
            check_id="openstack_image_visibility_audit",
            title="Public images are reviewed and minimized",
            description="Public images are reviewed and minimized.",
            severity="medium",
            provider="openstack",
            service="image",
            category="Compliance",
            tags=["image", "audit"],
        ),
        CheckDefinition(
            check_id="openstack_net_anti_spoofing",
            title="Allowed address pairs are minimized (anti-spoofing)",
            description="Allowed address pairs are minimized (anti-spoofing).",
            severity="medium",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_floating_ip_audit",
            title="Floating IPs are associated and reviewed",
            description="Floating IPs are associated and reviewed.",
            severity="medium",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "audit"],
        ),
        CheckDefinition(
            check_id="openstack_net_port_security",
            title="Port security is enabled on all active ports",
            description="Port security is enabled on all active ports.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_port_security_individual",
            title="Port has port security enabled",
            description="Port has port security enabled.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_segmentation",
            title="Network segmentation is implemented",
            description="Network segmentation is implemented.",
            severity="high",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking"],
        ),
        CheckDefinition(
            check_id="openstack_net_sg_restrictive",
            title="Security group does not have unrestricted ingress on all ports",
            description="Security group does not have unrestricted ingress on all ports.",
            severity="critical",
            provider="openstack",
            service="networking",
            category="Networking",
            tags=["networking", "security-group"],
        ),
        CheckDefinition(
            check_id="openstack_storage_backup_policies",
            title="Volume backups are configured",
            description="Volume backups are configured.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "backup"],
        ),
        CheckDefinition(
            check_id="openstack_storage_object_versioning",
            title="Object versioning is enabled on Swift containers",
            description="Object versioning is enabled on Swift containers.",
            severity="medium",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        CheckDefinition(
            check_id="openstack_storage_swift_acls",
            title="Swift containers do not have public read access",
            description="Swift containers do not have public read access.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage"],
        ),
        CheckDefinition(
            check_id="openstack_storage_volume_encrypted",
            title="Volume is encrypted",
            description="Volume is encrypted.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
        CheckDefinition(
            check_id="openstack_storage_volume_encryption",
            title="Block storage volumes are encrypted",
            description="Block storage volumes are encrypted.",
            severity="high",
            provider="openstack",
            service="storage",
            category="Storage",
            tags=["storage", "encryption"],
        ),
    ]
