"""Check definitions for Salesforce.

Auto-generated from salesforce scanner. 57 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Salesforce check definitions."""
    return [
        CheckDefinition(
            check_id="salesforce_api_security_token",
            title="API access requires security token or IP whitelist",
            description="API access requires security token or IP whitelist.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_clickjack_protection",
            title="Clickjack protection is enabled for all pages",
            description="Clickjack protection is enabled for all pages.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_encryption_at_rest",
            title="Shield Platform Encryption is active",
            description="Shield Platform Encryption is active.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "encryption"],
        ),
        CheckDefinition(
            check_id="salesforce_event_monitoring",
            title="Event Monitoring is active and generating logs",
            description="Event Monitoring is active and generating logs.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_failed_login_rate",
            title="Failed login rate is within threshold",
            description="Failed login rate is within threshold.",
            severity="medium",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="salesforce_field_level_security",
            title="Field-level security is configured on permission sets",
            description="Field-level security is configured on permission sets.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_ip_ranges_restricted",
            title="Login IP ranges are configured for profiles",
            description="Login IP ranges are configured for profiles.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_password_complexity",
            title="Password complexity requirements are enforced",
            description="Password complexity requirements are enforced.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_password_history",
            title="Password history enforcement is configured (at least 5 remembered)",
            description="Password history enforcement is configured (at least 5 remembered).",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_session_timeout_configured",
            title="Session timeout is configured (2 hours or less)",
            description="Session timeout is configured (2 hours or less).",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_setup_audit_trail",
            title="Setup Audit Trail is capturing changes",
            description="Setup Audit Trail is capturing changes.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "audit"],
        ),
        CheckDefinition(
            check_id="salesforce_sharing_rules_reviewed",
            title="Organization-wide sharing rules are configured",
            description="Organization-wide sharing rules are configured.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_configured",
            title="SAML SSO is configured",
            description="SAML SSO is configured.",
            severity="high",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_enabled",
            title="SAML SSO configuration is enabled",
            description="SAML SSO configuration is enabled.",
            severity="high",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_jit_provisioning",
            title="JIT provisioning is configured",
            description="JIT provisioning is configured.",
            severity="low",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_my_domain",
            title="My Domain is configured",
            description="My Domain is configured.",
            severity="medium",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_saml_version",
            title="SAML version is 2.0",
            description="SAML version is 2.0.",
            severity="medium",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_tls_enforced",
            title="HTTPS/TLS is enforced for all connections",
            description="HTTPS/TLS is enforced for all connections.",
            severity="critical",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="salesforce_transaction_security_active",
            title="Transaction Security Policies are configured and active",
            description="Transaction Security Policies are configured and active.",
            severity="high",
            provider="salesforce",
            service="threat_detection",
            category="Compliance",
            tags=["threat_detection"],
        ),
        CheckDefinition(
            check_id="salesforce_user_has_logged_in",
            title="Active user has logged in at least once",
            description="Active user has logged in at least once.",
            severity="low",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="salesforce_user_mfa_enabled",
            title="User has MFA enabled",
            description="User has MFA enabled.",
            severity="high",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="salesforce_user_not_stale",
            title="Active user has logged in within 90 days",
            description="Active user has logged in within 90 days.",
            severity="medium",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        # --- New checks below ---
        CheckDefinition(
            check_id="salesforce_admin_count_limited",
            title="System Administrator profile assignments are limited",
            description="System Administrator profile assignments are limited.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "access-control"],
        ),
        CheckDefinition(
            check_id="salesforce_profile_permissions_reviewed",
            title="Profile permissions are reviewed for least privilege",
            description="Profile permissions are reviewed for least privilege.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "access-control"],
        ),
        CheckDefinition(
            check_id="salesforce_permission_set_assignments",
            title="Permission set assignments are reviewed and minimal",
            description="Permission set assignments are reviewed and minimal.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "access-control"],
        ),
        CheckDefinition(
            check_id="salesforce_no_modify_all_data",
            title="Modify All Data permission is restricted to essential profiles",
            description="Modify All Data permission is restricted to essential profiles.",
            severity="critical",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "access-control"],
        ),
        CheckDefinition(
            check_id="salesforce_no_view_all_data",
            title="View All Data permission is restricted to essential profiles",
            description="View All Data permission is restricted to essential profiles.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "access-control"],
        ),
        CheckDefinition(
            check_id="salesforce_api_only_profile",
            title="API-only profiles are used for integration users",
            description="API-only profiles are used for integration users.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "api"],
        ),
        CheckDefinition(
            check_id="salesforce_guest_user_restricted",
            title="Guest user profile permissions are minimized",
            description="Guest user profile permissions are minimized.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "guest-access"],
        ),
        CheckDefinition(
            check_id="salesforce_community_security",
            title="Experience Cloud (Community) security settings are hardened",
            description="Experience Cloud (Community) security settings are hardened.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "community"],
        ),
        CheckDefinition(
            check_id="salesforce_named_credentials_used",
            title="Named credentials are used for external callouts",
            description="Named credentials are used for external callouts.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "integrations"],
        ),
        CheckDefinition(
            check_id="salesforce_remote_site_settings",
            title="Remote site settings are reviewed and minimal",
            description="Remote site settings are reviewed and minimal.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "integrations"],
        ),
        CheckDefinition(
            check_id="salesforce_connected_apps_reviewed",
            title="Connected apps are reviewed and authorized",
            description="Connected apps are reviewed and authorized.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "oauth"],
        ),
        CheckDefinition(
            check_id="salesforce_oauth_scopes_minimal",
            title="OAuth connected app scopes follow least privilege",
            description="OAuth connected app scopes follow least privilege.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "oauth"],
        ),
        CheckDefinition(
            check_id="salesforce_data_export_restricted",
            title="Data export functionality is restricted to authorized users",
            description="Data export functionality is restricted to authorized users.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "data-protection"],
        ),
        CheckDefinition(
            check_id="salesforce_report_export_restricted",
            title="Report export is restricted to authorized profiles",
            description="Report export is restricted to authorized profiles.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "data-protection"],
        ),
        CheckDefinition(
            check_id="salesforce_lightning_enforced",
            title="Lightning Experience is enforced for all users",
            description="Lightning Experience is enforced for all users.",
            severity="low",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "ui"],
        ),
        CheckDefinition(
            check_id="salesforce_classic_disabled",
            title="Salesforce Classic access is disabled",
            description="Salesforce Classic access is disabled.",
            severity="low",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "ui"],
        ),
        CheckDefinition(
            check_id="salesforce_login_hours_configured",
            title="Login hours are configured for sensitive profiles",
            description="Login hours are configured for sensitive profiles.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "access-control"],
        ),
        CheckDefinition(
            check_id="salesforce_login_flows_enabled",
            title="Login flows are enabled for additional authentication controls",
            description="Login flows are enabled for additional authentication controls.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "authentication"],
        ),
        CheckDefinition(
            check_id="salesforce_health_check_score",
            title="Security Health Check score meets minimum threshold",
            description="Security Health Check score meets minimum threshold.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "health-check"],
        ),
        CheckDefinition(
            check_id="salesforce_critical_updates_applied",
            title="Critical security updates are applied",
            description="Critical security updates are applied.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "patching"],
        ),
        CheckDefinition(
            check_id="salesforce_shield_event_monitoring",
            title="Shield Event Monitoring is enabled for security events",
            description="Shield Event Monitoring is enabled for security events.",
            severity="high",
            provider="salesforce",
            service="threat_detection",
            category="Compliance",
            tags=["threat_detection", "monitoring"],
        ),
        CheckDefinition(
            check_id="salesforce_transaction_security_policies",
            title="Transaction Security policies cover critical operations",
            description="Transaction Security policies cover critical operations.",
            severity="high",
            provider="salesforce",
            service="threat_detection",
            category="Compliance",
            tags=["threat_detection"],
        ),
        CheckDefinition(
            check_id="salesforce_real_time_event_monitoring",
            title="Real-Time Event Monitoring is configured",
            description="Real-Time Event Monitoring is configured.",
            severity="high",
            provider="salesforce",
            service="threat_detection",
            category="Compliance",
            tags=["threat_detection", "monitoring"],
        ),
        CheckDefinition(
            check_id="salesforce_threat_detection_enabled",
            title="Threat Detection events are monitored and alerting",
            description="Threat Detection events are monitored and alerting.",
            severity="high",
            provider="salesforce",
            service="threat_detection",
            category="Compliance",
            tags=["threat_detection"],
        ),
        CheckDefinition(
            check_id="salesforce_field_audit_trail",
            title="Field Audit Trail is enabled for sensitive objects",
            description="Field Audit Trail is enabled for sensitive objects.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "audit"],
        ),
        CheckDefinition(
            check_id="salesforce_sandbox_data_masked",
            title="Sandbox environments use masked or synthetic data",
            description="Sandbox environments use masked or synthetic data.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "data-protection"],
        ),
        CheckDefinition(
            check_id="salesforce_change_set_review",
            title="Change sets are reviewed before deployment to production",
            description="Change sets are reviewed before deployment to production.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "change-management"],
        ),
        CheckDefinition(
            check_id="salesforce_deployment_approvals",
            title="Deployment approvals are required for production changes",
            description="Deployment approvals are required for production changes.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "change-management"],
        ),
        CheckDefinition(
            check_id="salesforce_metadata_api_restricted",
            title="Metadata API access is restricted to authorized profiles",
            description="Metadata API access is restricted to authorized profiles.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "api"],
        ),
        CheckDefinition(
            check_id="salesforce_package_installation_review",
            title="Managed package installations are reviewed and authorized",
            description="Managed package installations are reviewed and authorized.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "packages"],
        ),
        CheckDefinition(
            check_id="salesforce_custom_permissions_reviewed",
            title="Custom permissions are reviewed and documented",
            description="Custom permissions are reviewed and documented.",
            severity="low",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "access-control"],
        ),
        CheckDefinition(
            check_id="salesforce_apex_class_security",
            title="Apex class security is configured with appropriate profiles",
            description="Apex class security is configured with appropriate profiles.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "code-security"],
        ),
        CheckDefinition(
            check_id="salesforce_vf_page_security",
            title="Visualforce page security is configured with appropriate profiles",
            description="Visualforce page security is configured with appropriate profiles.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "code-security"],
        ),
        CheckDefinition(
            check_id="salesforce_lwc_security_review",
            title="Lightning Web Components are reviewed for security best practices",
            description="Lightning Web Components are reviewed for security best practices.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "code-security"],
        ),
        CheckDefinition(
            check_id="salesforce_csp_trusted_sites",
            title="Content Security Policy trusted sites are reviewed and minimal",
            description="Content Security Policy trusted sites are reviewed and minimal.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "csp"],
        ),
        # --- Supplementary: MITRE orphan resolution ---
        CheckDefinition(
            check_id="salesforce_login_ip_ranges",
            title="Login IP ranges are configured for profiles",
            description="Login IP ranges are configured for profiles.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Identity",
            scanner_check_ids=["salesforce_login_ip_ranges"],
            source="scanner",
            tags=["platform_security", "ip-restriction"],
        ),
        CheckDefinition(
            check_id="salesforce_session_timeout",
            title="Session timeout is configured appropriately",
            description="Session timeout is configured appropriately.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Identity",
            scanner_check_ids=["salesforce_session_timeout"],
            source="scanner",
            tags=["platform_security", "session"],
        ),
    ]
