"""Check definitions for Salesforce.

Auto-generated from salesforce scanner. 22 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Salesforce check definitions."""
    return [
        CheckDefinition(
            check_id="salesforce_api_security_token",
            title="API access requires security token or IP whitelist",
            description="API access requires security token or IP whitelist.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_clickjack_protection",
            title="Clickjack protection is enabled for all pages",
            description="Clickjack protection is enabled for all pages.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_encryption_at_rest",
            title="Shield Platform Encryption is active",
            description="Shield Platform Encryption is active.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "encryption"],
        ),
        CheckDefinition(
            check_id="salesforce_event_monitoring",
            title="Event Monitoring is active and generating logs",
            description="Event Monitoring is active and generating logs.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_failed_login_rate",
            title="Failed login rate is within threshold",
            description="Failed login rate is within threshold.",
            severity="medium",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="salesforce_field_level_security",
            title="Field-level security is configured on permission sets",
            description="Field-level security is configured on permission sets.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_ip_ranges_restricted",
            title="Login IP ranges are configured for profiles",
            description="Login IP ranges are configured for profiles.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_password_complexity",
            title="Password complexity requirements are enforced",
            description="Password complexity requirements are enforced.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_password_history",
            title="Password history enforcement is configured (at least 5 remembered)",
            description="Password history enforcement is configured (at least 5 remembered).",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_session_timeout_configured",
            title="Session timeout is configured (2 hours or less)",
            description="Session timeout is configured (2 hours or less).",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_setup_audit_trail",
            title="Setup Audit Trail is capturing changes",
            description="Setup Audit Trail is capturing changes.",
            severity="high",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "audit"],
        ),
        CheckDefinition(
            check_id="salesforce_sharing_rules_reviewed",
            title="Organization-wide sharing rules are configured",
            description="Organization-wide sharing rules are configured.",
            severity="medium",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_configured",
            title="SAML SSO is configured",
            description="SAML SSO is configured.",
            severity="high",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_enabled",
            title="SAML SSO configuration is enabled",
            description="SAML SSO configuration is enabled.",
            severity="high",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_jit_provisioning",
            title="JIT provisioning is configured",
            description="JIT provisioning is configured.",
            severity="low",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_my_domain",
            title="My Domain is configured",
            description="My Domain is configured.",
            severity="medium",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_sso_saml_version",
            title="SAML version is 2.0",
            description="SAML version is 2.0.",
            severity="medium",
            provider="salesforce",
            service="sso",
            category="Compliance",
            tags=["sso"],
        ),
        CheckDefinition(
            check_id="salesforce_tls_enforced",
            title="HTTPS/TLS is enforced for all connections",
            description="HTTPS/TLS is enforced for all connections.",
            severity="critical",
            provider="salesforce",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="salesforce_transaction_security_active",
            title="Transaction Security Policies are configured and active",
            description="Transaction Security Policies are configured and active.",
            severity="high",
            provider="salesforce",
            service="threat_detection",
            category="Compliance",
            tags=["threat_detection"],
        ),
        CheckDefinition(
            check_id="salesforce_user_has_logged_in",
            title="Active user has logged in at least once",
            description="Active user has logged in at least once.",
            severity="low",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="salesforce_user_mfa_enabled",
            title="User has MFA enabled",
            description="User has MFA enabled.",
            severity="high",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="salesforce_user_not_stale",
            title="Active user has logged in within 90 days",
            description="Active user has logged in within 90 days.",
            severity="medium",
            provider="salesforce",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
    ]
