"""Check definitions for ServiceNow.

Auto-generated from servicenow scanner. 52 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all ServiceNow check definitions."""
    return [
        CheckDefinition(
            check_id="servicenow_admin_audit_logging",
            title="System audit logging is enabled",
            description="System audit logging is enabled.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="servicenow_api_key_rotation",
            title="OAuth credentials are rotated within 90 days",
            description="OAuth credentials are rotated within 90 days.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "rotation"],
        ),
        CheckDefinition(
            check_id="servicenow_change_management",
            title="Change management process is active",
            description="Change management process is active.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_cmdb_integrity",
            title="CMDB contains active and maintained configuration items",
            description="CMDB contains active and maintained configuration items.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_data_classification",
            title="Data classification is enabled",
            description="Data classification is enabled.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_encryption_at_rest",
            title="Encryption at rest is configured",
            description="Encryption at rest is configured.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "encryption"],
        ),
        CheckDefinition(
            check_id="servicenow_incident_management",
            title="Incident management process is active",
            description="Incident management process is active.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_instance_hardening",
            title="Instance hardening settings are configured (all key settings enabled)",
            description="Instance hardening settings are configured (all key settings enabled).",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_integration_security",
            title="REST integrations use authentication",
            description="REST integrations use authentication.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_ip_access_controls",
            title="IP-based access controls are active",
            description="IP-based access controls are active.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_role_separation",
            title="Admin role assignments are limited (20 or fewer)",
            description="Admin role assignments are limited (20 or fewer).",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_sm_session_timeout",
            title="Session timeout is configured (max 30 minutes)",
            description="Session timeout is configured (max 30 minutes).",
            severity="high",
            provider="servicenow",
            service="session_management",
            category="Compliance",
            tags=["session_management"],
        ),
        CheckDefinition(
            check_id="servicenow_tls_enforced",
            title="HTTPS/TLS is enforced for all connections",
            description="HTTPS/TLS is enforced for all connections.",
            severity="critical",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="servicenow_users_failed_logins",
            title="Failed login rate is within threshold",
            description="Failed login rate is within threshold.",
            severity="medium",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="servicenow_users_lockout_configured",
            title="Account lockout policy is configured",
            description="Account lockout policy is configured.",
            severity="high",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="servicenow_users_mfa_enabled",
            title="ServiceNow MFA is enabled for all users",
            description="ServiceNow MFA is enabled for all users.",
            severity="critical",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="servicenow_users_password_length",
            title="Password minimum length is at least 12 characters",
            description="Password minimum length is at least 12 characters.",
            severity="high",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        # --- New checks below ---
        CheckDefinition(
            check_id="servicenow_acl_rules_configured",
            title="ACL rules are configured to restrict table and field access",
            description="ACL rules are configured to restrict table and field access.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "acl"],
        ),
        CheckDefinition(
            check_id="servicenow_acl_role_hierarchy",
            title="ACL role hierarchy follows least privilege principle",
            description="ACL role hierarchy follows least privilege principle.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "acl"],
        ),
        CheckDefinition(
            check_id="servicenow_high_priv_roles_limited",
            title="High-privilege roles are assigned to limited users",
            description="High-privilege roles are assigned to limited users.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "roles"],
        ),
        CheckDefinition(
            check_id="servicenow_sso_configured",
            title="Single sign-on (SSO) is configured and active",
            description="Single sign-on (SSO) is configured and active.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "sso"],
        ),
        CheckDefinition(
            check_id="servicenow_password_complexity",
            title="Password complexity requirements are enforced",
            description="Password complexity requirements are enforced.",
            severity="high",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users", "password"],
        ),
        CheckDefinition(
            check_id="servicenow_password_history",
            title="Password history enforcement prevents reuse of recent passwords",
            description="Password history enforcement prevents reuse of recent passwords.",
            severity="medium",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users", "password"],
        ),
        CheckDefinition(
            check_id="servicenow_session_invalidation",
            title="Sessions are invalidated on password change or logout",
            description="Sessions are invalidated on password change or logout.",
            severity="high",
            provider="servicenow",
            service="session_management",
            category="Compliance",
            tags=["session_management"],
        ),
        CheckDefinition(
            check_id="servicenow_field_encryption",
            title="Sensitive fields use column-level encryption",
            description="Sensitive fields use column-level encryption.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "encryption"],
        ),
        CheckDefinition(
            check_id="servicenow_data_masking",
            title="Data masking is applied to sensitive fields for non-privileged users",
            description="Data masking is applied to sensitive fields for non-privileged users.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "data-protection"],
        ),
        CheckDefinition(
            check_id="servicenow_attachment_security",
            title="Attachment access is restricted by role-based rules",
            description="Attachment access is restricted by role-based rules.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "attachments"],
        ),
        CheckDefinition(
            check_id="servicenow_attachment_types_restricted",
            title="Allowed attachment file types are restricted",
            description="Allowed attachment file types are restricted.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "attachments"],
        ),
        CheckDefinition(
            check_id="servicenow_debug_disabled",
            title="Debug mode and verbose logging are disabled in production",
            description="Debug mode and verbose logging are disabled in production.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "hardening"],
        ),
        CheckDefinition(
            check_id="servicenow_glide_security_properties",
            title="Glide security system properties are hardened",
            description="Glide security system properties are hardened.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "hardening"],
        ),
        CheckDefinition(
            check_id="servicenow_xml_injection_protection",
            title="XML injection protection is enabled",
            description="XML injection protection is enabled.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "injection"],
        ),
        CheckDefinition(
            check_id="servicenow_csrf_protection",
            title="Cross-site request forgery (CSRF) protection is enabled",
            description="Cross-site request forgery (CSRF) protection is enabled.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "csrf"],
        ),
        CheckDefinition(
            check_id="servicenow_rest_api_auth",
            title="REST API endpoints require authentication",
            description="REST API endpoints require authentication.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "api"],
        ),
        CheckDefinition(
            check_id="servicenow_soap_api_security",
            title="SOAP API access is restricted and authenticated",
            description="SOAP API access is restricted and authenticated.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "api"],
        ),
        CheckDefinition(
            check_id="servicenow_oauth_provider_config",
            title="OAuth provider configuration uses secure settings",
            description="OAuth provider configuration uses secure settings.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "oauth"],
        ),
        CheckDefinition(
            check_id="servicenow_mid_server_security",
            title="MID Server uses validated and authorized configuration",
            description="MID Server uses validated and authorized configuration.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "mid-server"],
        ),
        CheckDefinition(
            check_id="servicenow_mid_server_encrypted",
            title="MID Server communication is encrypted",
            description="MID Server communication is encrypted.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "mid-server", "encryption"],
        ),
        CheckDefinition(
            check_id="servicenow_impersonation_logging",
            title="User impersonation events are logged and audited",
            description="User impersonation events are logged and audited.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "audit", "impersonation"],
        ),
        CheckDefinition(
            check_id="servicenow_table_rotation_audit",
            title="Table rotation and cleanup policies are configured for audit tables",
            description="Table rotation and cleanup policies are configured for audit tables.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "audit"],
        ),
        CheckDefinition(
            check_id="servicenow_login_tracking_enabled",
            title="Login tracking and reporting is enabled",
            description="Login tracking and reporting is enabled.",
            severity="medium",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users", "audit"],
        ),
        CheckDefinition(
            check_id="servicenow_cab_approval_required",
            title="Change Advisory Board approval is required for normal changes",
            description="Change Advisory Board approval is required for normal changes.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "change-management"],
        ),
        CheckDefinition(
            check_id="servicenow_change_risk_assessment",
            title="Change risk assessment is mandatory before deployment",
            description="Change risk assessment is mandatory before deployment.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "change-management"],
        ),
        CheckDefinition(
            check_id="servicenow_emergency_change_policy",
            title="Emergency change policy is defined and enforced",
            description="Emergency change policy is defined and enforced.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "change-management"],
        ),
        CheckDefinition(
            check_id="servicenow_instance_ip_allowlist",
            title="Instance access is restricted to allowed IP ranges",
            description="Instance access is restricted to allowed IP ranges.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "network"],
        ),
        CheckDefinition(
            check_id="servicenow_instance_https_redirect",
            title="HTTP requests are redirected to HTTPS",
            description="HTTP requests are redirected to HTTPS.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="servicenow_update_set_review",
            title="Update sets are reviewed and approved before deployment",
            description="Update sets are reviewed and approved before deployment.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "change-management"],
        ),
        CheckDefinition(
            check_id="servicenow_scope_separation",
            title="Application scope separation is enforced",
            description="Application scope separation is enforced.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "scoping"],
        ),
        CheckDefinition(
            check_id="servicenow_script_include_secure",
            title="Script includes are reviewed for secure coding practices",
            description="Script includes are reviewed for secure coding practices.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "scripting"],
        ),
        CheckDefinition(
            check_id="servicenow_client_script_reviewed",
            title="Client scripts are reviewed for security vulnerabilities",
            description="Client scripts are reviewed for security vulnerabilities.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "scripting"],
        ),
        CheckDefinition(
            check_id="servicenow_business_rule_secure",
            title="Business rules follow secure coding guidelines",
            description="Business rules follow secure coding guidelines.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "scripting"],
        ),
        CheckDefinition(
            check_id="servicenow_scheduled_jobs_reviewed",
            title="Scheduled jobs are reviewed and authorized",
            description="Scheduled jobs are reviewed and authorized.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "jobs"],
        ),
        CheckDefinition(
            check_id="servicenow_knowledge_article_security",
            title="Knowledge articles enforce role-based access controls",
            description="Knowledge articles enforce role-based access controls.",
            severity="low",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "knowledge"],
        ),
        # --- Supplementary: MITRE orphan resolution ---
        CheckDefinition(
            check_id="servicenow_ac_acl_active",
            title="ACL rules are active and properly configured",
            description="ACL rules are active and properly configured.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Identity",
            scanner_check_ids=["servicenow_ac_acl_active"],
            source="scanner",
            tags=["platform_security", "acl"],
        ),
        CheckDefinition(
            check_id="servicenow_iv_escape_script",
            title="Script escaping is enabled to prevent XSS",
            description="Script escaping is enabled to prevent XSS.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            scanner_check_ids=["servicenow_iv_escape_script"],
            source="scanner",
            tags=["platform_security", "xss"],
        ),
        CheckDefinition(
            check_id="servicenow_session_timeout",
            title="Session timeout is configured appropriately",
            description="Session timeout is configured appropriately.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Identity",
            scanner_check_ids=["servicenow_session_timeout"],
            source="scanner",
            tags=["platform_security", "session"],
        ),
    ]
