"""Check definitions for ServiceNow.

Auto-generated from servicenow scanner. 17 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all ServiceNow check definitions."""
    return [
        CheckDefinition(
            check_id="servicenow_admin_audit_logging",
            title="System audit logging is enabled",
            description="System audit logging is enabled.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="servicenow_api_key_rotation",
            title="OAuth credentials are rotated within 90 days",
            description="OAuth credentials are rotated within 90 days.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "rotation"],
        ),
        CheckDefinition(
            check_id="servicenow_change_management",
            title="Change management process is active",
            description="Change management process is active.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_cmdb_integrity",
            title="CMDB contains active and maintained configuration items",
            description="CMDB contains active and maintained configuration items.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_data_classification",
            title="Data classification is enabled",
            description="Data classification is enabled.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_encryption_at_rest",
            title="Encryption at rest is configured",
            description="Encryption at rest is configured.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "encryption"],
        ),
        CheckDefinition(
            check_id="servicenow_incident_management",
            title="Incident management process is active",
            description="Incident management process is active.",
            severity="medium",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_instance_hardening",
            title="Instance hardening settings are configured (all key settings enabled)",
            description="Instance hardening settings are configured (all key settings enabled).",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_integration_security",
            title="REST integrations use authentication",
            description="REST integrations use authentication.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_ip_access_controls",
            title="IP-based access controls are active",
            description="IP-based access controls are active.",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_role_separation",
            title="Admin role assignments are limited (20 or fewer)",
            description="Admin role assignments are limited (20 or fewer).",
            severity="high",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security"],
        ),
        CheckDefinition(
            check_id="servicenow_sm_session_timeout",
            title="Session timeout is configured (max 30 minutes)",
            description="Session timeout is configured (max 30 minutes).",
            severity="high",
            provider="servicenow",
            service="session_management",
            category="Compliance",
            tags=["session_management"],
        ),
        CheckDefinition(
            check_id="servicenow_tls_enforced",
            title="HTTPS/TLS is enforced for all connections",
            description="HTTPS/TLS is enforced for all connections.",
            severity="critical",
            provider="servicenow",
            service="platform_security",
            category="Compliance",
            tags=["platform_security", "ssl-tls"],
        ),
        CheckDefinition(
            check_id="servicenow_users_failed_logins",
            title="Failed login rate is within threshold",
            description="Failed login rate is within threshold.",
            severity="medium",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="servicenow_users_lockout_configured",
            title="Account lockout policy is configured",
            description="Account lockout policy is configured.",
            severity="high",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="servicenow_users_mfa_enabled",
            title="ServiceNow MFA is enabled for all users",
            description="ServiceNow MFA is enabled for all users.",
            severity="critical",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="servicenow_users_password_length",
            title="Password minimum length is at least 12 characters",
            description="Password minimum length is at least 12 characters.",
            severity="high",
            provider="servicenow",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
    ]
