"""Check definitions for Snowflake.

Auto-generated from snowflake scanner. 55 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Snowflake check definitions."""
    return [
        CheckDefinition(
            check_id="snowflake_account_network_policy",
            title="Network policy is configured",
            description="Network policy is configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_password_min_length",
            title="Password minimum length is at least 14 characters",
            description="Password minimum length is at least 14 characters.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_password_policy",
            title="Custom password policy is configured",
            description="Custom password policy is configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_scim_configured",
            title="SCIM integration is configured for user provisioning",
            description="SCIM integration is configured for user provisioning.",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_session_timeout",
            title="Session timeout is configured (15 minutes or less)",
            description="Session timeout is configured (15 minutes or less).",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_sso_configured",
            title="SSO/SAML is configured",
            description="SSO/SAML is configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_admin_count_appropriate",
            title="Account admin count is between 2 and 10",
            description="Account admin count is between 2 and 10.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_admin_has_email",
            title="Admin user has verified email",
            description="Admin user has verified email.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_audit_logging_enabled",
            title="Audit logging is active (login history available)",
            description="Audit logging is active (login history available).",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="snowflake_column_masking_policies",
            title="Column-level masking policies are configured",
            description="Column-level masking policies are configured.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_cortex_access_restricted",
            title="Snowflake Cortex access is restricted to authorized roles",
            description="Snowflake Cortex access is restricted to authorized roles.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_data_retention_configured",
            title="Data retention period is configured (at least 1 day)",
            description="Data retention period is configured (at least 1 day).",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "retention"],
        ),
        CheckDefinition(
            check_id="snowflake_data_sharing_monitored",
            title="Outbound data shares are monitored and limited",
            description="Outbound data shares are monitored and limited.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_external_functions_restricted",
            title="External functions are limited and reviewed",
            description="External functions are limited and reviewed.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_failover_configured",
            title="Account replication/failover is configured",
            description="Account replication/failover is configured.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_query_history_retention",
            title="Query history is retained for audit purposes",
            description="Query history is retained for audit purposes.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "retention"],
        ),
        CheckDefinition(
            check_id="snowflake_row_access_policies",
            title="Row access policies are configured",
            description="Row access policies are configured.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_service_account_rsa",
            title="Service account uses RSA key authentication",
            description="Service account uses RSA key authentication.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_stages_encrypted",
            title="External stages use encryption",
            description="External stages use encryption.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "encryption"],
        ),
        CheckDefinition(
            check_id="snowflake_task_no_admin_owner",
            title="Task is not owned by admin role",
            description="Task is not owned by admin role.",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_user_mfa_enabled",
            title="Password user has MFA enabled",
            description="Password user has MFA enabled.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="snowflake_user_no_admin_default_role",
            title="User does not have admin as default role",
            description="User does not have admin as default role.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_user_not_inactive",
            title="User has logged in within 90 days",
            description="User has logged in within 90 days.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_user_password_rotation",
            title="User password has been rotated within 90 days",
            description="User password has been rotated within 90 days.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "rotation"],
        ),
        CheckDefinition(
            check_id="snowflake_warehouse_auto_suspend",
            title="Warehouse has auto-suspend configured (10 minutes or less)",
            description="Warehouse has auto-suspend configured (10 minutes or less).",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        # --- New checks below ---
        CheckDefinition(
            check_id="snowflake_object_tagging_enabled",
            title="Object tagging is used for data governance classification",
            description="Object tagging is used for data governance classification.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "governance"],
        ),
        CheckDefinition(
            check_id="snowflake_access_history_enabled",
            title="Access history is enabled for data access auditing",
            description="Access history is enabled for data access auditing.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "audit"],
        ),
        CheckDefinition(
            check_id="snowflake_network_policy_all_users",
            title="Network policy is applied to all users",
            description="Network policy is applied to all users.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "network"],
        ),
        CheckDefinition(
            check_id="snowflake_private_link_configured",
            title="AWS PrivateLink or Azure Private Link is configured",
            description="AWS PrivateLink or Azure Private Link is configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "network"],
        ),
        CheckDefinition(
            check_id="snowflake_triSecretSecure_enabled",
            title="Tri-Secret Secure (customer-managed key) is enabled",
            description="Tri-Secret Secure (customer-managed key) is enabled.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "encryption"],
        ),
        CheckDefinition(
            check_id="snowflake_account_replication_security",
            title="Account replication is restricted to authorized accounts",
            description="Account replication is restricted to authorized accounts.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "replication"],
        ),
        CheckDefinition(
            check_id="snowflake_database_replication_encrypted",
            title="Database replication uses encrypted channels",
            description="Database replication uses encrypted channels.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "encryption", "replication"],
        ),
        CheckDefinition(
            check_id="snowflake_share_restricted_accounts",
            title="Data shares are restricted to specific accounts",
            description="Data shares are restricted to specific accounts.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "sharing"],
        ),
        CheckDefinition(
            check_id="snowflake_reader_account_limited",
            title="Reader accounts are limited and monitored",
            description="Reader accounts are limited and monitored.",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "sharing"],
        ),
        CheckDefinition(
            check_id="snowflake_storage_integration_restricted",
            title="Storage integrations are restricted to specific paths",
            description="Storage integrations are restricted to specific paths.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "integrations"],
        ),
        CheckDefinition(
            check_id="snowflake_external_stage_encrypted",
            title="External stages enforce server-side encryption",
            description="External stages enforce server-side encryption.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "encryption"],
        ),
        CheckDefinition(
            check_id="snowflake_pipe_ownership_reviewed",
            title="Snowpipe ownership is reviewed and restricted",
            description="Snowpipe ownership is reviewed and restricted.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_stream_ownership_reviewed",
            title="Stream ownership is reviewed and assigned to appropriate roles",
            description="Stream ownership is reviewed and assigned to appropriate roles.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_materialized_view_security",
            title="Materialized view access is restricted by role",
            description="Materialized view access is restricted by role.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_dynamic_table_ownership",
            title="Dynamic table ownership follows least privilege",
            description="Dynamic table ownership follows least privilege.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_role_hierarchy_reviewed",
            title="Role hierarchy is reviewed for excessive privilege inheritance",
            description="Role hierarchy is reviewed for excessive privilege inheritance.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "roles"],
        ),
        CheckDefinition(
            check_id="snowflake_future_grants_minimal",
            title="Future grants are minimal and scoped appropriately",
            description="Future grants are minimal and scoped appropriately.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "grants"],
        ),
        CheckDefinition(
            check_id="snowflake_database_roles_used",
            title="Database roles are used for fine-grained access control",
            description="Database roles are used for fine-grained access control.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "roles"],
        ),
        CheckDefinition(
            check_id="snowflake_object_ownership_transferred",
            title="Object ownership is transferred from personal to functional roles",
            description="Object ownership is transferred from personal to functional roles.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "roles"],
        ),
        CheckDefinition(
            check_id="snowflake_system_defined_roles_minimal",
            title="System-defined role grants are minimized",
            description="System-defined role grants are minimized.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "roles"],
        ),
        CheckDefinition(
            check_id="snowflake_warehouse_resource_monitor",
            title="Warehouse has resource monitor configured with credit limits",
            description="Warehouse has resource monitor configured with credit limits.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "cost"],
        ),
        CheckDefinition(
            check_id="snowflake_warehouse_statement_timeout",
            title="Warehouse statement timeout is configured to prevent runaway queries",
            description="Warehouse statement timeout is configured to prevent runaway queries.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_query_tag_required",
            title="Query tagging is required for workload identification",
            description="Query tagging is required for workload identification.",
            severity="low",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "governance"],
        ),
        CheckDefinition(
            check_id="snowflake_session_policy_configured",
            title="Session policy is configured for idle timeout and token refresh",
            description="Session policy is configured for idle timeout and token refresh.",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "session"],
        ),
        CheckDefinition(
            check_id="snowflake_password_policy_lockout",
            title="Password policy includes account lockout after failed attempts",
            description="Password policy includes account lockout after failed attempts.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "password"],
        ),
        CheckDefinition(
            check_id="snowflake_oauth_integration_scoped",
            title="OAuth integration is scoped to specific roles",
            description="OAuth integration is scoped to specific roles.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "oauth"],
        ),
        CheckDefinition(
            check_id="snowflake_external_oauth_validated",
            title="External OAuth token validation is properly configured",
            description="External OAuth token validation is properly configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account", "oauth"],
        ),
        CheckDefinition(
            check_id="snowflake_key_pair_rotation",
            title="RSA key pairs are rotated within 365 days",
            description="RSA key pairs are rotated within 365 days.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "rotation"],
        ),
        CheckDefinition(
            check_id="snowflake_ip_restriction_per_user",
            title="Per-user network policies are configured for privileged accounts",
            description="Per-user network policies are configured for privileged accounts.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "network"],
        ),
        CheckDefinition(
            check_id="snowflake_data_classification_enabled",
            title="Automatic data classification is enabled for sensitive data discovery",
            description="Automatic data classification is enabled for sensitive data discovery.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "governance"],
        ),
    ]
