"""Check definitions for Snowflake.

Auto-generated from snowflake scanner. 25 checks.
"""

from scanner.registry.models import CheckDefinition


def get_checks() -> list[CheckDefinition]:
    """Return all Snowflake check definitions."""
    return [
        CheckDefinition(
            check_id="snowflake_account_network_policy",
            title="Network policy is configured",
            description="Network policy is configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_password_min_length",
            title="Password minimum length is at least 14 characters",
            description="Password minimum length is at least 14 characters.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_password_policy",
            title="Custom password policy is configured",
            description="Custom password policy is configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_scim_configured",
            title="SCIM integration is configured for user provisioning",
            description="SCIM integration is configured for user provisioning.",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_session_timeout",
            title="Session timeout is configured (15 minutes or less)",
            description="Session timeout is configured (15 minutes or less).",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_account_sso_configured",
            title="SSO/SAML is configured",
            description="SSO/SAML is configured.",
            severity="high",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_admin_count_appropriate",
            title="Account admin count is between 2 and 10",
            description="Account admin count is between 2 and 10.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_admin_has_email",
            title="Admin user has verified email",
            description="Admin user has verified email.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_audit_logging_enabled",
            title="Audit logging is active (login history available)",
            description="Audit logging is active (login history available).",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "audit", "logging"],
        ),
        CheckDefinition(
            check_id="snowflake_column_masking_policies",
            title="Column-level masking policies are configured",
            description="Column-level masking policies are configured.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_cortex_access_restricted",
            title="Snowflake Cortex access is restricted to authorized roles",
            description="Snowflake Cortex access is restricted to authorized roles.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_data_retention_configured",
            title="Data retention period is configured (at least 1 day)",
            description="Data retention period is configured (at least 1 day).",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "retention"],
        ),
        CheckDefinition(
            check_id="snowflake_data_sharing_monitored",
            title="Outbound data shares are monitored and limited",
            description="Outbound data shares are monitored and limited.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_external_functions_restricted",
            title="External functions are limited and reviewed",
            description="External functions are limited and reviewed.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_failover_configured",
            title="Account replication/failover is configured",
            description="Account replication/failover is configured.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_query_history_retention",
            title="Query history is retained for audit purposes",
            description="Query history is retained for audit purposes.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "retention"],
        ),
        CheckDefinition(
            check_id="snowflake_row_access_policies",
            title="Row access policies are configured",
            description="Row access policies are configured.",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
        CheckDefinition(
            check_id="snowflake_service_account_rsa",
            title="Service account uses RSA key authentication",
            description="Service account uses RSA key authentication.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_stages_encrypted",
            title="External stages use encryption",
            description="External stages use encryption.",
            severity="high",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations", "encryption"],
        ),
        CheckDefinition(
            check_id="snowflake_task_no_admin_owner",
            title="Task is not owned by admin role",
            description="Task is not owned by admin role.",
            severity="medium",
            provider="snowflake",
            service="account",
            category="Compliance",
            tags=["account"],
        ),
        CheckDefinition(
            check_id="snowflake_user_mfa_enabled",
            title="Password user has MFA enabled",
            description="Password user has MFA enabled.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "mfa"],
        ),
        CheckDefinition(
            check_id="snowflake_user_no_admin_default_role",
            title="User does not have admin as default role",
            description="User does not have admin as default role.",
            severity="high",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_user_not_inactive",
            title="User has logged in within 90 days",
            description="User has logged in within 90 days.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users"],
        ),
        CheckDefinition(
            check_id="snowflake_user_password_rotation",
            title="User password has been rotated within 90 days",
            description="User password has been rotated within 90 days.",
            severity="medium",
            provider="snowflake",
            service="users",
            category="Compliance",
            tags=["users", "rotation"],
        ),
        CheckDefinition(
            check_id="snowflake_warehouse_auto_suspend",
            title="Warehouse has auto-suspend configured (10 minutes or less)",
            description="Warehouse has auto-suspend configured (10 minutes or less).",
            severity="medium",
            provider="snowflake",
            service="data_operations",
            category="Compliance",
            tags=["data_operations"],
        ),
    ]
