"""GWS CIS v1.3.0 Evaluator Registry — 89 controls mapped."""
from .section_1_4_5_6_admin_sec import (
    SECTION_1_EVALUATORS, SECTION_1_2_EVALUATORS,
    SECTION_4_1_EVALUATORS, SECTION_4_2_EVALUATORS, SECTION_4_3_EVALUATORS,
    SECTION_5_EVALUATORS, SECTION_6_EVALUATORS,
)
from .section_3_apps import SECTION_3_EVALUATORS
from .supplements import SUPPLEMENTS

EVALUATOR_REGISTRY: dict[str, callable] = {}
EVALUATOR_REGISTRY.update(SECTION_1_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_1_2_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_3_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_4_1_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_4_2_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_4_3_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_5_EVALUATORS)
EVALUATOR_REGISTRY.update(SECTION_6_EVALUATORS)
EVALUATOR_REGISTRY.update(SUPPLEMENTS)  # Override manual stubs

assert len(EVALUATOR_REGISTRY) == 89, f"Expected 89, got {len(EVALUATOR_REGISTRY)}"
__all__ = ["EVALUATOR_REGISTRY"]
